using AnisotropicFiltering = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.AnisotropicFiltering;
using AspectRatio = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.AspectRatio;
using AudioBufferMs = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.AudioBufferMs;
using AxisDeadzone = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.AxisDeadzone;
using AxisScale = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.AxisScale;
using BlendingAccuracy = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.BlendingAccuracy;
using CasMode = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.CasMode;
using FrameLimiter = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.FrameLimiter;
using HwDownloadMode = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.HwDownloadMode;
using Lightgun = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.Lightgun;
using Multitap = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.Multitap;
using Renderer = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.Renderer;
using TextureFiltering = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.TextureFiltering;
using TrilinearFiltering = GWGUI.Emulation.Sony.Emulators.Pcee2.Enums.TrilinearFiltering;
using GWGUI.Emulation.Sony.Emulators.Pcee2.Functions;
using GWGUI.Emulation.Sony.Emulators.Common.Interop.Functions;
using GWGUI.Emulation.Sony.Emulators.Common.Interop.Constants;
using GWGUI.Emulation.Sony.Emulators.Common.Interop.Enums;

namespace GWGUI.Emulation.Sony.Emulators.Pcee2.Constants;

internal static class OptionConstants
{
    internal const string FastBootKey = "pcsx2_fast_boot";
    internal const string FastBootLabelResource = "Emulation.Option.pcee2.pcsx2_fast_boot.Label";
    internal const string FastBootHelpResource = "Emulation.Option.pcee2.pcsx2_fast_boot.Help";
    internal const string RendererKey = "pcsx2_renderer";
    internal const string RendererLabelResource = "Emulation.Option.pcee2.pcsx2_renderer.Label";
    internal const string RendererHelpResource = "Emulation.Option.pcee2.pcsx2_renderer.Help";
    internal const string RendererOpengl = "opengl";
    internal const string RendererSoftware = "software";
    internal static readonly string RendererDefaultValue = OptionValueFunctions.ToNative(Renderer.Opengl);
    internal const string UpscaleMultiplierKey = "pcsx2_upscale_multiplier";
    internal const string UpscaleMultiplierLabelResource = "Emulation.Option.pcee2.pcsx2_upscale_multiplier.Label";
    internal const string UpscaleMultiplierHelpResource = "Emulation.Option.pcee2.pcsx2_upscale_multiplier.Help";
    internal static IReadOnlyList<EmulationSettingsNumericRange> UpscaleMultiplierRanges { get; } =
    [
        new(1, 4, 1),
    ];
    internal const string UpscaleMultiplierDefaultValue = "1";
    internal const string HwDownloadModeKey = "pcsx2_hw_download_mode";
    internal const string HwDownloadModeLabelResource = "Emulation.Option.pcee2.pcsx2_hw_download_mode.Label";
    internal const string HwDownloadModeHelpResource = "Emulation.Option.pcee2.pcsx2_hw_download_mode.Help";
    internal const string HwDownloadModeAccurate = "accurate";
    internal const string HwDownloadModeUnsynchronized = "unsynchronized";
    internal const string HwDownloadModeDisabled = "disabled";
    internal static readonly string HwDownloadModeDefaultValue = OptionValueFunctions.ToNative(HwDownloadMode.Accurate);
    internal const string BlendingAccuracyKey = "pcsx2_blending_accuracy";
    internal const string BlendingAccuracyLabelResource = "Emulation.Option.pcee2.pcsx2_blending_accuracy.Label";
    internal const string BlendingAccuracyHelpResource = "Emulation.Option.pcee2.pcsx2_blending_accuracy.Help";
    internal const string BlendingAccuracyMinimum = "minimum";
    internal const string BlendingAccuracyBasic = "basic";
    internal const string BlendingAccuracyMedium = "medium";
    internal const string BlendingAccuracyHigh = "high";
    internal const string BlendingAccuracyFull = "full";
    internal const string BlendingAccuracyMaximum = "maximum";
    internal static readonly string BlendingAccuracyDefaultValue = OptionValueFunctions.ToNative(BlendingAccuracy.Basic);
    internal const string TextureFilteringKey = "pcsx2_texture_filtering";
    internal const string TextureFilteringLabelResource = "Emulation.Option.pcee2.pcsx2_texture_filtering.Label";
    internal const string TextureFilteringHelpResource = "Emulation.Option.pcee2.pcsx2_texture_filtering.Help";
    internal const string TextureFilteringNearest = "nearest";
    internal const string TextureFilteringBilinearPs2 = "bilinear_ps2";
    internal const string TextureFilteringBilinearForced = "bilinear_forced";
    internal const string TextureFilteringBilinearForcedSprite = "bilinear_forced_sprite";
    internal static readonly string TextureFilteringDefaultValue = OptionValueFunctions.ToNative(TextureFiltering.BilinearPs2);
    internal const string TrilinearFilteringKey = "pcsx2_trilinear_filtering";
    internal const string TrilinearFilteringLabelResource = "Emulation.Option.pcee2.pcsx2_trilinear_filtering.Label";
    internal const string TrilinearFilteringAuto = "auto";
    internal const string TrilinearFilteringOff = "off";
    internal const string TrilinearFilteringPs2 = "ps2";
    internal const string TrilinearFilteringForced = "forced";
    internal static readonly string TrilinearFilteringDefaultValue = OptionValueFunctions.ToNative(TrilinearFiltering.Auto);
    internal const string AnisotropicFilteringKey = "pcsx2_anisotropic_filtering";
    internal const string AnisotropicFilteringLabelResource = "Emulation.Option.pcee2.pcsx2_anisotropic_filtering.Label";
    internal const string AnisotropicFilteringHelpResource = "Emulation.Option.pcee2.pcsx2_anisotropic_filtering.Help";
    internal const string AnisotropicFiltering2DisplayName = "2x";
    internal const string AnisotropicFiltering4DisplayName = "4x";
    internal const string AnisotropicFiltering8DisplayName = "8x";
    internal const string AnisotropicFiltering16DisplayName = "16x";
    internal static readonly string AnisotropicFilteringDefaultValue = OptionValueFunctions.ToNative(AnisotropicFiltering._0);
    internal const string DitheringKey = "pcsx2_dithering";
    internal const string DitheringLabelResource = "Emulation.Option.pcee2.pcsx2_dithering.Label";
    internal const string DitheringHelpResource = "Emulation.Option.pcee2.pcsx2_dithering.Help";
    internal static IReadOnlyList<EmulationSettingsNumericRange> DitheringRanges { get; } =
    [
        new(0, 2, 1),
    ];
    internal const string DitheringDefaultValue = "2";
    internal const string MipmappingKey = "pcsx2_mipmapping";
    internal const string MipmappingLabelResource = "Emulation.Option.pcee2.pcsx2_mipmapping.Label";
    internal const string DeinterlaceModeKey = "pcsx2_deinterlace_mode";
    internal const string DeinterlaceModeLabelResource = "Emulation.Option.pcee2.pcsx2_deinterlace_mode.Label";
    internal const string DeinterlaceModeHelpResource = "Emulation.Option.pcee2.pcsx2_deinterlace_mode.Help";
    internal static EmulationSettingsNumericRange DeinterlaceModeRange { get; } = new(0, 9, 1);
    internal const string DeinterlaceModeDefaultValue = "0";
    internal const string FxaaKey = "pcsx2_fxaa";
    internal const string FxaaLabelResource = "Emulation.Option.pcee2.pcsx2_fxaa.Label";
    internal const string FxaaHelpResource = "Emulation.Option.pcee2.pcsx2_fxaa.Help";
    internal const string CasModeKey = "pcsx2_cas_mode";
    internal const string CasModeLabelResource = "Emulation.Option.pcee2.pcsx2_cas_mode.Label";
    internal const string CasModeDisabled = "disabled";
    internal const string CasModeSharpen = "sharpen";
    internal static readonly string CasModeDefaultValue = OptionValueFunctions.ToNative(CasMode.Disabled);
    internal const string AudioBufferMsKey = "pcsx2_audio_buffer_ms";
    internal const string AudioBufferMsLabelResource = "Emulation.Option.pcee2.pcsx2_audio_buffer_ms.Label";
    internal const string AudioBufferMsHelpResource = "Emulation.Option.pcee2.pcsx2_audio_buffer_ms.Help";
    internal const string AudioBufferMs50DisplayName = "50 ms";
    internal const string AudioBufferMs75DisplayName = "75 ms";
    internal const string AudioBufferMs100DisplayName = "100 ms";
    internal const string AudioBufferMs150DisplayName = "150 ms";
    internal const string AudioBufferMs200DisplayName = "200 ms";
    internal static readonly string AudioBufferMsDefaultValue = OptionValueFunctions.ToNative(AudioBufferMs._100);
    internal const string FrameLimiterKey = "pcsx2_frame_limiter";
    internal const string FrameLimiterLabelResource = "Emulation.Option.pcee2.pcsx2_frame_limiter.Label";
    internal const string FrameLimiterHelpResource = "Emulation.Option.pcee2.pcsx2_frame_limiter.Help";
    internal const string FrameLimiterFrontend = "frontend";
    internal const string FrameLimiterInternal = "internal";
    internal static readonly string FrameLimiterDefaultValue = OptionValueFunctions.ToNative(FrameLimiter.Frontend);
    internal const string SkipDuplicateFramesKey = "pcsx2_skip_duplicate_frames";
    internal const string SkipDuplicateFramesLabelResource = "Emulation.Option.pcee2.pcsx2_skip_duplicate_frames.Label";
    internal const string SkipDuplicateFramesHelpResource = "Emulation.Option.pcee2.pcsx2_skip_duplicate_frames.Help";
    internal const string CasSharpnessKey = "pcsx2_cas_sharpness";
    internal const string CasSharpnessLabelResource = "Emulation.Option.pcee2.pcsx2_cas_sharpness.Label";
    internal static EmulationSettingsNumericRange CasSharpnessRange { get; } = new(10, 100, 10);
    internal const string CasSharpnessDefaultValue = "50";
    internal const string AspectRatioKey = "pcsx2_aspect_ratio";
    internal const string AspectRatioLabelResource = "Emulation.Option.pcee2.pcsx2_aspect_ratio.Label";
    internal const string AspectRatioHelpResource = "Emulation.Option.pcee2.pcsx2_aspect_ratio.Help";
    internal const string AspectRatioAuto = "auto";
    internal const string AspectRatio43 = "4:3";
    internal const string AspectRatio169 = "16:9";
    internal static readonly string AspectRatioDefaultValue = OptionValueFunctions.ToNative(AspectRatio.Auto);
    internal const string MultitapKey = "pcsx2_multitap";
    internal const string MultitapLabelResource = "Emulation.Option.pcee2.pcsx2_multitap.Label";
    internal const string MultitapHelpResource = "Emulation.Option.pcee2.pcsx2_multitap.Help";
    internal const string MultitapDisabled = "disabled";
    internal const string MultitapPort1 = "port1";
    internal const string MultitapPort2 = "port2";
    internal const string MultitapBoth = "both";
    internal static readonly string MultitapDefaultValue = OptionValueFunctions.ToNative(Multitap.Disabled);
    internal const string LightgunKey = "pcsx2_lightgun";
    internal const string LightgunLabelResource = "Emulation.Option.pcee2.pcsx2_lightgun.Label";
    internal const string LightgunHelpResource = "Emulation.Option.pcee2.pcsx2_lightgun.Help";
    internal const string LightgunDisabled = "disabled";
    internal const string LightgunUsb1 = "usb1";
    internal const string LightgunUsb2 = "usb2";
    internal const string LightgunBoth = "both";
    internal static readonly string LightgunDefaultValue = OptionValueFunctions.ToNative(Lightgun.Disabled);
    internal const string RumbleKey = "pcsx2_rumble";
    internal const string RumbleLabelResource = "Emulation.Option.pcee2.pcsx2_rumble.Label";
    internal const string RumbleHelpResource = "Emulation.Option.pcee2.pcsx2_rumble.Help";
    internal const string AxisScaleKey = "pcsx2_axis_scale";
    internal const string AxisScaleLabelResource = "Emulation.Option.pcee2.pcsx2_axis_scale.Label";
    internal const string AxisScaleHelpResource = "Emulation.Option.pcee2.pcsx2_axis_scale.Help";
    internal const string AxisScale100DisplayName = "100%";
    internal const string AxisScale115DisplayName = "115%";
    internal const string AxisScale150DisplayName = "150%";
    internal static readonly string AxisScaleDefaultValue = OptionValueFunctions.ToNative(AxisScale._133);
    internal const string AxisDeadzoneKey = "pcsx2_axis_deadzone";
    internal const string AxisDeadzoneLabelResource = "Emulation.Option.pcee2.pcsx2_axis_deadzone.Label";
    internal const string AxisDeadzoneHelpResource = "Emulation.Option.pcee2.pcsx2_axis_deadzone.Help";
    internal const string AxisDeadzone5DisplayName = "5%";
    internal const string AxisDeadzone10DisplayName = "10%";
    internal const string AxisDeadzone15DisplayName = "15%";
    internal const string AxisDeadzone20DisplayName = "20%";
    internal const string AxisDeadzone30DisplayName = "30%";
    internal static readonly string AxisDeadzoneDefaultValue = OptionValueFunctions.ToNative(AxisDeadzone._0);
    internal const string WidescreenPatchesKey = "pcsx2_widescreen_patches";
    internal const string WidescreenPatchesLabelResource = "Emulation.Option.pcee2.pcsx2_widescreen_patches.Label";
    internal const string WidescreenPatchesHelpResource = "Emulation.Option.pcee2.pcsx2_widescreen_patches.Help";
    internal const string NoInterlacingPatchesKey = "pcsx2_no_interlacing_patches";
    internal const string NoInterlacingPatchesLabelResource = "Emulation.Option.pcee2.pcsx2_no_interlacing_patches.Label";
    internal const string NoInterlacingPatchesHelpResource = "Emulation.Option.pcee2.pcsx2_no_interlacing_patches.Help";
    internal const string MtvuKey = "pcsx2_mtvu";
    internal const string MtvuLabelResource = "Emulation.Option.pcee2.pcsx2_mtvu.Label";
    internal const string MtvuHelpResource = "Emulation.Option.pcee2.pcsx2_mtvu.Help";
    internal const string InstantVu1Key = "pcsx2_instant_vu1";
    internal const string InstantVu1LabelResource = "Emulation.Option.pcee2.pcsx2_instant_vu1.Label";
    internal const string InstantVu1HelpResource = "Emulation.Option.pcee2.pcsx2_instant_vu1.Help";
    internal const string EeCycleRateKey = "pcsx2_ee_cycle_rate";
    internal const string EeCycleRateLabelResource = "Emulation.Option.pcee2.pcsx2_ee_cycle_rate.Label";
    internal const string EeCycleRateHelpResource = "Emulation.Option.pcee2.pcsx2_ee_cycle_rate.Help";
    internal static IReadOnlyList<EmulationSettingsNumericRange> EeCycleRateRanges { get; } =
    [
        new(-3, 3, 1),
    ];
    internal const string EeCycleRateDefaultValue = "0";
    internal const string EeCycleSkipKey = "pcsx2_ee_cycle_skip";
    internal const string EeCycleSkipLabelResource = "Emulation.Option.pcee2.pcsx2_ee_cycle_skip.Label";
    internal const string EeCycleSkipHelpResource = "Emulation.Option.pcee2.pcsx2_ee_cycle_skip.Help";
    internal static IReadOnlyList<EmulationSettingsNumericRange> EeCycleSkipRanges { get; } =
    [
        new(0, 3, 1),
    ];
    internal const string EeCycleSkipDefaultValue = "0";
    internal const string CpuRecompilerKey = "pcsx2_cpu_recompiler";
    internal const string CpuRecompilerLabelResource = "Emulation.Option.pcee2.pcsx2_cpu_recompiler.Label";
    internal const string CpuRecompilerHelpResource = "Emulation.Option.pcee2.pcsx2_cpu_recompiler.Help";
    internal const string RecEeKey = "pcsx2_rec_ee";
    internal const string RecEeLabelResource = "Emulation.Option.pcee2.pcsx2_rec_ee.Label";
    internal const string RecEeHelpResource = "Emulation.Option.pcee2.pcsx2_rec_ee.Help";
    internal const string RecIopKey = "pcsx2_rec_iop";
    internal const string RecIopLabelResource = "Emulation.Option.pcee2.pcsx2_rec_iop.Label";
    internal const string RecIopHelpResource = "Emulation.Option.pcee2.pcsx2_rec_iop.Help";
    internal const string RecVu0Key = "pcsx2_rec_vu0";
    internal const string RecVu0LabelResource = "Emulation.Option.pcee2.pcsx2_rec_vu0.Label";
    internal const string RecVu0HelpResource = "Emulation.Option.pcee2.pcsx2_rec_vu0.Help";
    internal const string RecVu1Key = "pcsx2_rec_vu1";
    internal const string RecVu1LabelResource = "Emulation.Option.pcee2.pcsx2_rec_vu1.Label";
    internal const string RecVu1HelpResource = "Emulation.Option.pcee2.pcsx2_rec_vu1.Help";
    internal const string MemcardSlot1EnableKey = "pcsx2_memcard_slot1_enable";
    internal const string MemcardSlot1EnableLabelResource = "Emulation.Option.pcee2.pcsx2_memcard_slot1_enable.Label";
    internal const string MemcardSlot1EnableHelpResource = "Emulation.Option.pcee2.pcsx2_memcard_slot1_enable.Help";
    internal const string MemcardSlot2EnableKey = "pcsx2_memcard_slot2_enable";
    internal const string MemcardSlot2EnableLabelResource = "Emulation.Option.pcee2.pcsx2_memcard_slot2_enable.Label";
    internal const string MemcardSlot2EnableHelpResource = "Emulation.Option.pcee2.pcsx2_memcard_slot2_enable.Help";
}
