namespace GWGUI.Emulation.Sega.Common.Machines.Common.Constants;

internal static partial class SettingsDescriptionFunctionsConstants
{
    internal const string Enabled = "enabled";
    internal const string Disabled = "disabled";
    internal const string General = "general";
    internal const string Hardware = "hardware";
    internal const string Cpu = "cpu";
    internal const string Memory = "memory";
    internal const string Firmware = "firmware";
    internal const string Video = "video";
    internal const string Audio = "audio";
    internal const string ResourceGeneral = "Emulation.Tab.General";
    internal const string ResourceHardware = "Emulation.Sega.Hardware";
    internal const string ResourceMachineModel = "Emulation.Machine.Model";
    internal const string ResourceEmulator = "Emulation.Core.Emulator";
    internal const string ResourceCpuProcessor = "Emulation.Cpu.Processor";
    internal const string ResourceCpuModel = "Emulation.Cpu.Model";
    internal const string ResourceCpuSpeed = "Emulation.Cpu.SpeedOriginal";
    internal const string ResourceMemoryMain = "Emulation.Memory.Main";
    internal const string ResourceRom = "Emulation.Tab.Rom";
    internal const string ResourceFirmwareSystemRom = "Emulation.Firmware.Rom.System";
    internal const string ResourceFirmwareIntegrated = "Emulation.Sega.Firmware.Integrated";
    internal const string ResourceVideo = "Emulation.Video.Settings.Display";
    internal const string ResourceVideoResolution = "Emulation.Video.Resolution";
    internal const string ResourceVideoMonitor = "Emulation.Sega.Video.Monitor";
    internal const string ResourceVideoIntensity = "Emulation.Sega.Video.Intensity";
    internal const string ResourceVideoCrop = "Emulation.Video.Crop";
    internal const string ResourceAudio = "Emulation.Audio";
    internal const string ResourceAudioEnabled = "Emulation.Audio.Enabled";
    internal const string ResourceAudioDevice = "Emulation.Audio.Device";
    internal const string ResourceAudioLatency = "Emulation.Audio.LatencyLabel";
    internal const string ResourceAudioFloppySound = "Emulation.Audio.Floppy.Enabled";
    internal const string ResourceMasterSystemVariant = "Emulation.Sega.MasterSystem.Variant";
    internal const string ResourceMasterSystemThreeDGlasses = "Emulation.Sega.MasterSystem.ThreeDGlasses";
    internal const string ResourceMegaDriveModel = "Emulation.Sega.MegaDrive.Model";
    internal const string ResourceMegaCdModel = "Emulation.Sega.MegaDrive.MegaCd";
    internal const string ResourceMegaCdEnabled = "Emulation.Sega.MegaDrive.MegaCd.Enabled";
    internal const string ResourceMegaDriveThirtyTwoX = "Emulation.Sega.MegaDrive.32X";
    internal const string ResourceMegaDriveRegion = "Emulation.Sega.MegaDrive.Region";
    internal const string ResourceMegaDriveVideoStandard = "Emulation.Sega.MegaDrive.VideoStandard";
    internal const string CpuFrequency = "—";
    internal const string IconGeneral = "\uE713";
    internal const string IconCpu = "\uE950";
    internal const string IconMemory = "\uE964";
    internal const string IconFirmware = "\uE8B7";
    internal const string IconVideo = "\uE7F4";
    internal const string IconAudio = "\uE767";
}
