using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.DeSmuME.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("desmume_firmware_language", "Emulation.Option.desmume.desmume_firmware_language", "Emulation.Option.desmume.desmume_firmware_language.Help", "system", "Auto", "Auto", [new("Auto", "Emulation.Option.desmume.desmume_firmware_language.Value.Auto"), new("Japanese", "Emulation.Option.desmume.desmume_firmware_language.Value.Japanese"), new("English", "Emulation.Option.desmume.desmume_firmware_language.Value.English"), new("French", "Emulation.Option.desmume.desmume_firmware_language.Value.French"), new("German", "Emulation.Option.desmume.desmume_firmware_language.Value.German"), new("Italian", "Emulation.Option.desmume.desmume_firmware_language.Value.Italian"), new("Spanish", "Emulation.Option.desmume.desmume_firmware_language.Value.Spanish")], Tab: EmulationMachineTab.Rom),
        new("desmume_use_external_bios", "Emulation.Option.desmume.desmume_use_external_bios", "Emulation.Option.desmume.desmume_use_external_bios.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_use_external_bios.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_use_external_bios.Value.enabled")], Tab: EmulationMachineTab.Rom, RequiresRestart: true),
        new("desmume_boot_into_bios", "Emulation.Option.desmume.desmume_boot_into_bios", "Emulation.Option.desmume.desmume_boot_into_bios.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_boot_into_bios.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_boot_into_bios.Value.enabled")], Tab: EmulationMachineTab.Rom),
        new("desmume_load_to_memory", "Emulation.Option.desmume.desmume_load_to_memory", "Emulation.Option.desmume.desmume_load_to_memory.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_load_to_memory.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_load_to_memory.Value.enabled")], Tab: EmulationMachineTab.Ram, RequiresRestart: true),
        new("desmume_num_cores", "Emulation.Option.desmume.desmume_num_cores", "Emulation.Option.desmume.desmume_num_cores.Help", "system", "1", "1", [new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4")], Tab: EmulationMachineTab.Cpu),
        new("desmume_cpu_mode", "Emulation.Option.desmume.desmume_cpu_mode", "Emulation.Option.desmume.desmume_cpu_mode.Help", "system", "interpreter", "interpreter", [new("interpreter", "Emulation.Option.desmume.desmume_cpu_mode.Value.interpreter"), new("jit", "Emulation.Option.desmume.desmume_cpu_mode.Value.jit")], Tab: EmulationMachineTab.Cpu, RequiresRestart: true),
        new("desmume_jit_block_size", "Emulation.Option.desmume.desmume_jit_block_size", "Emulation.Option.desmume.desmume_jit_block_size.Help", "system", "12", "12", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24"), new("25", "25"), new("26", "26"), new("27", "27"), new("28", "28"), new("29", "29"), new("30", "30"), new("31", "31"), new("32", "32"), new("33", "33"), new("34", "34"), new("35", "35"), new("36", "36"), new("37", "37"), new("38", "38"), new("39", "39"), new("40", "40"), new("41", "41"), new("42", "42"), new("43", "43"), new("44", "44"), new("45", "45"), new("46", "46"), new("47", "47"), new("48", "48"), new("49", "49"), new("50", "50"), new("51", "51"), new("52", "52"), new("53", "53"), new("54", "54"), new("55", "55"), new("56", "56"), new("57", "57"), new("58", "58"), new("59", "59"), new("60", "60"), new("61", "61"), new("62", "62"), new("63", "63"), new("64", "64"), new("65", "65"), new("66", "66"), new("67", "67"), new("68", "68"), new("69", "69"), new("70", "70"), new("71", "71"), new("72", "72"), new("73", "73"), new("74", "74"), new("75", "75"), new("76", "76"), new("77", "77"), new("78", "78"), new("79", "79"), new("80", "80"), new("81", "81"), new("82", "82"), new("83", "83"), new("84", "84"), new("85", "85"), new("86", "86"), new("87", "87"), new("88", "88"), new("89", "89"), new("90", "90"), new("91", "91"), new("92", "92"), new("93", "93"), new("94", "94"), new("95", "95"), new("96", "96"), new("97", "97"), new("98", "98"), new("99", "99"), new("100", "100")], Tab: EmulationMachineTab.Cpu),
        new("desmume_advanced_timing", "Emulation.Option.desmume.desmume_advanced_timing", "Emulation.Option.desmume.desmume_advanced_timing.Help", "system", "enabled", "enabled", [new("enabled", "Emulation.Option.desmume.desmume_advanced_timing.Value.enabled"), new("disabled", "Emulation.Option.desmume.desmume_advanced_timing.Value.disabled")], Tab: EmulationMachineTab.Cpu),
        new("desmume_frameskip", "Emulation.Option.desmume.desmume_frameskip", "Emulation.Option.desmume.desmume_frameskip.Help", "video", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9")], Tab: EmulationMachineTab.Video),
        new("desmume_internal_resolution", "Emulation.Option.desmume.desmume_internal_resolution", "Emulation.Option.desmume.desmume_internal_resolution.Help", "video", "256x192", "256x192", [new("256x192", "1x (256x192)"), new("512x384", "2x (512x384)"), new("768x576", "3x (768x576)"), new("1024x768", "4x (1024x768)"), new("1280x960", "5x (1280x960)"), new("1536x1152", "6x (1536x1152)"), new("1792x1344", "7x (1792x1344)"), new("2048x1536", "8x (2048x1536)"), new("2304x1728", "9x (2304x1728)"), new("2560x1920", "10x (2560x1920)")], Tab: EmulationMachineTab.Video),
        new("desmume_opengl_mode", "Emulation.Option.desmume.desmume_opengl_mode", "Emulation.Option.desmume.desmume_opengl_mode.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_opengl_mode.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_opengl_mode.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: true),
        new("desmume_color_depth", "Emulation.Option.desmume.desmume_color_depth", "Emulation.Option.desmume.desmume_color_depth.Help", "video", "16-bit", "16-bit", [new("16-bit", "Emulation.Option.desmume.desmume_color_depth.Value.16-bit"), new("32-bit", "Emulation.Option.desmume.desmume_color_depth.Value.32-bit")], Tab: EmulationMachineTab.Video, RequiresRestart: true),
        new("desmume_gfx_multisampling", "Emulation.Option.desmume.desmume_gfx_multisampling", "Emulation.Option.desmume.desmume_gfx_multisampling.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_gfx_multisampling.Value.disabled"), new("2", "2"), new("4", "4"), new("8", "8"), new("16", "16"), new("32", "32")], Tab: EmulationMachineTab.Video),
        new("desmume_gfx_texture_smoothing", "Emulation.Option.desmume.desmume_gfx_texture_smoothing", "Emulation.Option.desmume.desmume_gfx_texture_smoothing.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_gfx_texture_smoothing.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_gfx_texture_smoothing.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_opengl_shadow_polygon", "Emulation.Option.desmume.desmume_opengl_shadow_polygon", "Emulation.Option.desmume.desmume_opengl_shadow_polygon.Help", "video", "enabled", "enabled", [new("disabled", "Emulation.Option.desmume.desmume_opengl_shadow_polygon.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_opengl_shadow_polygon.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_opengl_special_zero_alpha", "Emulation.Option.desmume.desmume_opengl_special_zero_alpha", "Emulation.Option.desmume.desmume_opengl_special_zero_alpha.Help", "video", "enabled", "enabled", [new("disabled", "Emulation.Option.desmume.desmume_opengl_special_zero_alpha.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_opengl_special_zero_alpha.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_opengl_nds_depth_calculation", "Emulation.Option.desmume.desmume_opengl_nds_depth_calculation", "Emulation.Option.desmume.desmume_opengl_nds_depth_calculation.Help", "video", "enabled", "enabled", [new("disabled", "Emulation.Option.desmume.desmume_opengl_nds_depth_calculation.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_opengl_nds_depth_calculation.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_opengl_depth_lequal_polygon_facing", "Emulation.Option.desmume.desmume_opengl_depth_lequal_polygon_facing", "Emulation.Option.desmume.desmume_opengl_depth_lequal_polygon_facing.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_opengl_depth_lequal_polygon_facing.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_opengl_depth_lequal_polygon_facing.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_gfx_highres_interpolate_color", "Emulation.Option.desmume.desmume_gfx_highres_interpolate_color", "Emulation.Option.desmume.desmume_gfx_highres_interpolate_color.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_gfx_highres_interpolate_color.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_gfx_highres_interpolate_color.Value.enabled")], Tab: EmulationMachineTab.Audio),
        new("desmume_gfx_linehack", "Emulation.Option.desmume.desmume_gfx_linehack", "Emulation.Option.desmume.desmume_gfx_linehack.Help", "video", "enabled", "enabled", [new("disabled", "Emulation.Option.desmume.desmume_gfx_linehack.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_gfx_linehack.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_gfx_txthack", "Emulation.Option.desmume.desmume_gfx_txthack", "Emulation.Option.desmume.desmume_gfx_txthack.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_gfx_txthack.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_gfx_txthack.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_gfx_edgemark", "Emulation.Option.desmume.desmume_gfx_edgemark", "Emulation.Option.desmume.desmume_gfx_edgemark.Help", "video", "enabled", "enabled", [new("disabled", "Emulation.Option.desmume.desmume_gfx_edgemark.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_gfx_edgemark.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_gfx_texture_scaling", "Emulation.Option.desmume.desmume_gfx_texture_scaling", "Emulation.Option.desmume.desmume_gfx_texture_scaling.Help", "video", "1", "1", [new("1", "1"), new("2", "2"), new("4", "4")], Tab: EmulationMachineTab.Video),
        new("desmume_gfx_texture_deposterize", "Emulation.Option.desmume.desmume_gfx_texture_deposterize", "Emulation.Option.desmume.desmume_gfx_texture_deposterize.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_gfx_texture_deposterize.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_gfx_texture_deposterize.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_screens_layout", "Emulation.Option.desmume.desmume_screens_layout", "Emulation.Option.desmume.desmume_screens_layout.Help", "screen", "top/bottom", "top/bottom", [new("top/bottom", "Emulation.Option.desmume.desmume_screens_layout.Value.top/bottom"), new("bottom/top", "Emulation.Option.desmume.desmume_screens_layout.Value.bottom/top"), new("left/right", "Emulation.Option.desmume.desmume_screens_layout.Value.left/right"), new("right/left", "Emulation.Option.desmume.desmume_screens_layout.Value.right/left"), new("top only", "Emulation.Option.desmume.desmume_screens_layout.Value.top only"), new("bottom only", "Emulation.Option.desmume.desmume_screens_layout.Value.bottom only"), new("hybrid/top", "Emulation.Option.desmume.desmume_screens_layout.Value.hybrid/top"), new("hybrid/bottom", "Emulation.Option.desmume.desmume_screens_layout.Value.hybrid/bottom")], Tab: EmulationMachineTab.Video),
        new("desmume_screens_gap", "Emulation.Option.desmume.desmume_screens_gap", "Emulation.Option.desmume.desmume_screens_gap.Help", "screen", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24"), new("25", "25"), new("26", "26"), new("27", "27"), new("28", "28"), new("29", "29"), new("30", "30"), new("31", "31"), new("32", "32"), new("33", "33"), new("34", "34"), new("35", "35"), new("36", "36"), new("37", "37"), new("38", "38"), new("39", "39"), new("40", "40"), new("41", "41"), new("42", "42"), new("43", "43"), new("44", "44"), new("45", "45"), new("46", "46"), new("47", "47"), new("48", "48"), new("49", "49"), new("50", "50"), new("51", "51"), new("52", "52"), new("53", "53"), new("54", "54"), new("55", "55"), new("56", "56"), new("57", "57"), new("58", "58"), new("59", "59"), new("60", "60"), new("61", "61"), new("62", "62"), new("63", "63"), new("64", "64"), new("65", "65"), new("66", "66"), new("67", "67"), new("68", "68"), new("69", "69"), new("70", "70"), new("71", "71"), new("72", "72"), new("73", "73"), new("74", "74"), new("75", "75"), new("76", "76"), new("77", "77"), new("78", "78"), new("79", "79"), new("80", "80"), new("81", "81"), new("82", "82"), new("83", "83"), new("84", "84"), new("85", "85"), new("86", "86"), new("87", "87"), new("88", "88"), new("89", "89"), new("90", "90"), new("91", "91"), new("92", "92"), new("93", "93"), new("94", "94"), new("95", "95"), new("96", "96"), new("97", "97"), new("98", "98"), new("99", "99"), new("100", "100")], Tab: EmulationMachineTab.Video),
        new("desmume_hybrid_layout_ratio", "Emulation.Option.desmume.desmume_hybrid_layout_ratio", "Emulation.Option.desmume.desmume_hybrid_layout_ratio.Help", "screen", "3:1", "3:1", [new("3:1", "3:1"), new("2:1", "2:1")], Tab: EmulationMachineTab.Video),
        new("desmume_hybrid_layout_scale", "Emulation.Option.desmume.desmume_hybrid_layout_scale", "Emulation.Option.desmume.desmume_hybrid_layout_scale.Help", "screen", "disabled", "disabled", [new("disabled", "Emulation.Option.desmume.desmume_hybrid_layout_scale.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_hybrid_layout_scale.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_hybrid_showboth_screens", "Emulation.Option.desmume.desmume_hybrid_showboth_screens", "Emulation.Option.desmume.desmume_hybrid_showboth_screens.Help", "screen", "enabled", "enabled", [new("disabled", "Emulation.Option.desmume.desmume_hybrid_showboth_screens.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_hybrid_showboth_screens.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_hybrid_cursor_always_smallscreen", "Emulation.Option.desmume.desmume_hybrid_cursor_always_smallscreen", "Emulation.Option.desmume.desmume_hybrid_cursor_always_smallscreen.Help", "screen", "enabled", "enabled", [new("disabled", "Emulation.Option.desmume.desmume_hybrid_cursor_always_smallscreen.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_hybrid_cursor_always_smallscreen.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("desmume_pointer_mouse", "Emulation.Option.desmume.desmume_pointer_mouse", "Emulation.Option.desmume.desmume_pointer_mouse.Help", "input", "enabled", "enabled", [new("disabled", "Emulation.Option.desmume.desmume_pointer_mouse.Value.disabled"), new("enabled", "Emulation.Option.desmume.desmume_pointer_mouse.Value.enabled")], Tab: EmulationMachineTab.Mouse),
        new("desmume_pointer_type", "Emulation.Option.desmume.desmume_pointer_type", "Emulation.Option.desmume.desmume_pointer_type.Help", "input", "mouse", "mouse", [new("mouse", "Emulation.Option.desmume.desmume_pointer_type.Value.mouse"), new("touch", "Emulation.Option.desmume.desmume_pointer_type.Value.touch")], Tab: EmulationMachineTab.Mouse),
        new("desmume_mouse_speed", "Emulation.Option.desmume.desmume_mouse_speed", "Emulation.Option.desmume.desmume_mouse_speed.Help", "input", "1.0", "1.0", [new("1.0", "1.0"), new("1.5", "1.5"), new("2.0", "2.0"), new("0.01", "0.01"), new("0.02", "0.02"), new("0.03", "0.03"), new("0.04", "0.04"), new("0.05", "0.05"), new("0.125", "0.125"), new("0.25", "0.25"), new("0.5", "0.5")], Tab: EmulationMachineTab.Mouse),
        new("desmume_input_rotation", "Emulation.Option.desmume.desmume_input_rotation", "Emulation.Option.desmume.desmume_input_rotation.Help", "input", "0", "0", [new("0", "0"), new("90", "90"), new("180", "180"), new("270", "270")], Tab: EmulationMachineTab.Controllers),
        new("desmume_pointer_device_l", "Emulation.Option.desmume.desmume_pointer_device_l", "Emulation.Option.desmume.desmume_pointer_device_l.Help", "input", "none", "none", [new("none", "Emulation.Option.desmume.desmume_pointer_device_l.Value.none"), new("emulated", "Emulation.Option.desmume.desmume_pointer_device_l.Value.emulated"), new("absolute", "Emulation.Option.desmume.desmume_pointer_device_l.Value.absolute"), new("pressed", "Emulation.Option.desmume.desmume_pointer_device_l.Value.pressed")], Tab: EmulationMachineTab.Mouse),
        new("desmume_pointer_device_r", "Emulation.Option.desmume.desmume_pointer_device_r", "Emulation.Option.desmume.desmume_pointer_device_r.Help", "input", "none", "none", [new("none", "Emulation.Option.desmume.desmume_pointer_device_r.Value.none"), new("emulated", "Emulation.Option.desmume.desmume_pointer_device_r.Value.emulated"), new("absolute", "Emulation.Option.desmume.desmume_pointer_device_r.Value.absolute"), new("pressed", "Emulation.Option.desmume.desmume_pointer_device_r.Value.pressed")], Tab: EmulationMachineTab.Mouse),
        new("desmume_pointer_device_deadzone", "Emulation.Option.desmume.desmume_pointer_device_deadzone", "Emulation.Option.desmume.desmume_pointer_device_deadzone.Help", "input", "15", "15", [new("0", "0"), new("5", "5"), new("10", "10"), new("15", "15"), new("20", "20"), new("25", "25"), new("30", "30"), new("35", "35")], Tab: EmulationMachineTab.Mouse),
        new("desmume_pointer_device_acceleration_mod", "Emulation.Option.desmume.desmume_pointer_device_acceleration_mod", "Emulation.Option.desmume.desmume_pointer_device_acceleration_mod.Help", "input", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24"), new("25", "25"), new("26", "26"), new("27", "27"), new("28", "28"), new("29", "29"), new("30", "30"), new("31", "31"), new("32", "32"), new("33", "33"), new("34", "34"), new("35", "35"), new("36", "36"), new("37", "37"), new("38", "38"), new("39", "39"), new("40", "40"), new("41", "41"), new("42", "42"), new("43", "43"), new("44", "44"), new("45", "45"), new("46", "46"), new("47", "47"), new("48", "48"), new("49", "49"), new("50", "50"), new("51", "51"), new("52", "52"), new("53", "53"), new("54", "54"), new("55", "55"), new("56", "56"), new("57", "57"), new("58", "58"), new("59", "59"), new("60", "60"), new("61", "61"), new("62", "62"), new("63", "63"), new("64", "64"), new("65", "65"), new("66", "66"), new("67", "67"), new("68", "68"), new("69", "69"), new("70", "70"), new("71", "71"), new("72", "72"), new("73", "73"), new("74", "74"), new("75", "75"), new("76", "76"), new("77", "77"), new("78", "78"), new("79", "79"), new("80", "80"), new("81", "81"), new("82", "82"), new("83", "83"), new("84", "84"), new("85", "85"), new("86", "86"), new("87", "87"), new("88", "88"), new("89", "89"), new("90", "90"), new("91", "91"), new("92", "92"), new("93", "93"), new("94", "94"), new("95", "95"), new("96", "96"), new("97", "97"), new("98", "98"), new("99", "99"), new("100", "100")], Tab: EmulationMachineTab.Mouse),
        new("desmume_pointer_stylus_pressure", "Emulation.Option.desmume.desmume_pointer_stylus_pressure", "Emulation.Option.desmume.desmume_pointer_stylus_pressure.Help", "input", "50", "50", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24"), new("25", "25"), new("26", "26"), new("27", "27"), new("28", "28"), new("29", "29"), new("30", "30"), new("31", "31"), new("32", "32"), new("33", "33"), new("34", "34"), new("35", "35"), new("36", "36"), new("37", "37"), new("38", "38"), new("39", "39"), new("40", "40"), new("41", "41"), new("42", "42"), new("43", "43"), new("44", "44"), new("45", "45"), new("46", "46"), new("47", "47"), new("48", "48"), new("49", "49"), new("50", "50"), new("51", "51"), new("52", "52"), new("53", "53"), new("54", "54"), new("55", "55"), new("56", "56"), new("57", "57"), new("58", "58"), new("59", "59"), new("60", "60"), new("61", "61"), new("62", "62"), new("63", "63"), new("64", "64"), new("65", "65"), new("66", "66"), new("67", "67"), new("68", "68"), new("69", "69"), new("70", "70"), new("71", "71"), new("72", "72"), new("73", "73"), new("74", "74"), new("75", "75"), new("76", "76"), new("77", "77"), new("78", "78"), new("79", "79"), new("80", "80"), new("81", "81"), new("82", "82"), new("83", "83"), new("84", "84"), new("85", "85"), new("86", "86"), new("87", "87"), new("88", "88"), new("89", "89"), new("90", "90"), new("91", "91"), new("92", "92"), new("93", "93"), new("94", "94"), new("95", "95"), new("96", "96"), new("97", "97"), new("98", "98"), new("99", "99"), new("100", "100")], Tab: EmulationMachineTab.Mouse),
        new("desmume_pointer_colour", "Emulation.Option.desmume.desmume_pointer_colour", "Emulation.Option.desmume.desmume_pointer_colour.Help", "input", "white", "white", [new("white", "Emulation.Option.desmume.desmume_pointer_colour.Value.white"), new("black", "Emulation.Option.desmume.desmume_pointer_colour.Value.black"), new("red", "Emulation.Option.desmume.desmume_pointer_colour.Value.red"), new("blue", "Emulation.Option.desmume.desmume_pointer_colour.Value.blue"), new("yellow", "Emulation.Option.desmume.desmume_pointer_colour.Value.yellow")], Tab: EmulationMachineTab.Mouse),
        new("desmume_mic_mode", "Emulation.Option.desmume.desmume_mic_mode", "Emulation.Option.desmume.desmume_mic_mode.Help", "", "pattern", "pattern", [new("pattern", "Emulation.Option.desmume.desmume_mic_mode.Value.pattern"), new("random", "Emulation.Option.desmume.desmume_mic_mode.Value.random")], Tab: EmulationMachineTab.Audio)
    ];
}
