<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>gwgui.emulation.nec</AssemblyName>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <None Update="module.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <InternalsVisibleTo Include="GWGUI.Tests" />
    <ProjectReference Include="..\GWGUI.Emulation\GWGUI.Emulation.csproj" />
    <ProjectReference Include="..\GWGUI.MediaEngine\GWGUI.MediaEngine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\*.png"
                      LogicalName="GWGUI.Emulation.Nec.Assets.%(Filename)%(Extension)" />
    <EmbeddedResource Include="Assets\Machines\*.png"
                      LogicalName="GWGUI.Emulation.Nec.Assets.Machines.%(Filename)%(Extension)" />
    <EmbeddedResource Update="Resources\*\*.resx">
      <WithCulture>false</WithCulture>
      <LogicalName>GWGUI.Emulation.Nec.Resources.%(Filename).$([System.IO.Path]::GetFileName($([System.IO.Path]::GetDirectoryName('%(Identity)')))).resources</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
