using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.VbaM.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("vbam_usebios", "Emulation.Option.vbam.vbam_usebios", "Emulation.Option.vbam.vbam_usebios.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.vbam.vbam_usebios.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_usebios.Value.enabled")]),
        new("vbam_forceRTCenable", "Emulation.Option.vbam.vbam_forceRTCenable", "Emulation.Option.vbam.vbam_forceRTCenable.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.vbam.vbam_forceRTCenable.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_forceRTCenable.Value.enabled")]),
        new("vbam_gbHardware", "Emulation.Option.vbam.vbam_gbHardware", "Emulation.Option.vbam.vbam_gbHardware.Help", "system", "gbc", "gbc", [new("gbc", "Emulation.Option.vbam.vbam_gbHardware.Value.gbc"), new("auto", "Emulation.Option.vbam.vbam_gbHardware.Value.auto"), new("sgb", "Emulation.Option.vbam.vbam_gbHardware.Value.sgb"), new("gb", "Emulation.Option.vbam.vbam_gbHardware.Value.gb"), new("gba", "Emulation.Option.vbam.vbam_gbHardware.Value.gba"), new("sgb2", "Emulation.Option.vbam.vbam_gbHardware.Value.sgb2")]),
        new("vbam_allowcolorizerhack", "Emulation.Option.vbam.vbam_allowcolorizerhack", "Emulation.Option.vbam.vbam_allowcolorizerhack.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.vbam.vbam_allowcolorizerhack.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_allowcolorizerhack.Value.enabled")]),
        new("vbam_palettes", "Emulation.Option.vbam.vbam_palettes", "Emulation.Option.vbam.vbam_palettes.Help", "video", "black and white", "black and white", [new("black and white", "Emulation.Option.vbam.vbam_palettes.Value.black and white"), new("blue sea", "Emulation.Option.vbam.vbam_palettes.Value.blue sea"), new("dark knight", "Emulation.Option.vbam.vbam_palettes.Value.dark knight"), new("green forest", "Emulation.Option.vbam.vbam_palettes.Value.green forest"), new("hot desert", "Emulation.Option.vbam.vbam_palettes.Value.hot desert"), new("pink dreams", "Emulation.Option.vbam.vbam_palettes.Value.pink dreams"), new("wierd colors", "Emulation.Option.vbam.vbam_palettes.Value.wierd colors"), new("original gameboy", "Emulation.Option.vbam.vbam_palettes.Value.original gameboy"), new("gba sp", "Emulation.Option.vbam.vbam_palettes.Value.gba sp")]),
        new("vbam_showborders", "Emulation.Option.vbam.vbam_showborders", "Emulation.Option.vbam.vbam_showborders.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.vbam.vbam_showborders.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_showborders.Value.enabled"), new("auto", "Emulation.Option.vbam.vbam_showborders.Value.auto")]),
        new("vbam_gbcoloroption", "Emulation.Option.vbam.vbam_gbcoloroption", "Emulation.Option.vbam.vbam_gbcoloroption.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.vbam.vbam_gbcoloroption.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_gbcoloroption.Value.enabled")]),
        new("vbam_lcdfilter", "Emulation.Option.vbam.vbam_lcdfilter", "Emulation.Option.vbam.vbam_lcdfilter.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.vbam.vbam_lcdfilter.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_lcdfilter.Value.enabled")]),
        new("vbam_interframeblending", "Emulation.Option.vbam.vbam_interframeblending", "Emulation.Option.vbam.vbam_interframeblending.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.vbam.vbam_interframeblending.Value.disabled"), new("smart", "Emulation.Option.vbam.vbam_interframeblending.Value.smart"), new("motion blur", "Emulation.Option.vbam.vbam_interframeblending.Value.motion blur")]),
        new("vbam_soundinterpolation", "Emulation.Option.vbam.vbam_soundinterpolation", "Emulation.Option.vbam.vbam_soundinterpolation.Help", "audio", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_soundinterpolation.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_soundinterpolation.Value.enabled")]),
        new("vbam_soundfiltering", "Emulation.Option.vbam.vbam_soundfiltering", "Emulation.Option.vbam.vbam_soundfiltering.Help", "audio", "5", "5", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10")]),
        new("vbam_turboenable", "Emulation.Option.vbam.vbam_turboenable", "Emulation.Option.vbam.vbam_turboenable.Help", "input", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_turboenable.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_turboenable.Value.enabled")]),
        new("vbam_turbodelay", "Emulation.Option.vbam.vbam_turbodelay", "Emulation.Option.vbam.vbam_turbodelay.Help", "input", "3", "3", [new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15")]),
        new("vbam_solarsensor", "Emulation.Option.vbam.vbam_solarsensor", "Emulation.Option.vbam.vbam_solarsensor.Help", "input", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10")]),
        new("vbam_astick_deadzone", "Emulation.Option.vbam.vbam_astick_deadzone", "Emulation.Option.vbam.vbam_astick_deadzone.Help", "input", "15", "15", [new("0", "0"), new("5", "5"), new("10", "10"), new("15", "15"), new("20", "20"), new("25", "25"), new("30", "30")]),
        new("vbam_gyro_sensitivity", "Emulation.Option.vbam.vbam_gyro_sensitivity", "Emulation.Option.vbam.vbam_gyro_sensitivity.Help", "input", "100", "100", [new("10", "10"), new("15", "15"), new("20", "20"), new("25", "25"), new("30", "30"), new("35", "35"), new("40", "40"), new("45", "45"), new("50", "50"), new("55", "55"), new("60", "60"), new("65", "65"), new("70", "70"), new("75", "75"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100"), new("105", "105"), new("110", "110"), new("115", "115"), new("120", "120")]),
        new("vbam_tilt_sensitivity", "Emulation.Option.vbam.vbam_tilt_sensitivity", "Emulation.Option.vbam.vbam_tilt_sensitivity.Help", "input", "100", "100", [new("10", "10"), new("15", "15"), new("20", "20"), new("25", "25"), new("30", "30"), new("35", "35"), new("40", "40"), new("45", "45"), new("50", "50"), new("55", "55"), new("60", "60"), new("65", "65"), new("70", "70"), new("75", "75"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100"), new("105", "105"), new("110", "110"), new("115", "115"), new("120", "120")]),
        new("vbam_swap_astick", "Emulation.Option.vbam.vbam_swap_astick", "Emulation.Option.vbam.vbam_swap_astick.Help", "input", "disabled", "disabled", [new("disabled", "Emulation.Option.vbam.vbam_swap_astick.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_swap_astick.Value.enabled")]),
        new("vbam_sound_1", "Emulation.Option.vbam.vbam_sound_1", "Emulation.Option.vbam.vbam_sound_1.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_sound_1.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_sound_1.Value.enabled")]),
        new("vbam_sound_2", "Emulation.Option.vbam.vbam_sound_2", "Emulation.Option.vbam.vbam_sound_2.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_sound_2.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_sound_2.Value.enabled")]),
        new("vbam_sound_3", "Emulation.Option.vbam.vbam_sound_3", "Emulation.Option.vbam.vbam_sound_3.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_sound_3.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_sound_3.Value.enabled")]),
        new("vbam_sound_4", "Emulation.Option.vbam.vbam_sound_4", "Emulation.Option.vbam.vbam_sound_4.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_sound_4.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_sound_4.Value.enabled")]),
        new("vbam_sound_5", "Emulation.Option.vbam.vbam_sound_5", "Emulation.Option.vbam.vbam_sound_5.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_sound_5.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_sound_5.Value.enabled")]),
        new("vbam_sound_6", "Emulation.Option.vbam.vbam_sound_6", "Emulation.Option.vbam.vbam_sound_6.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_sound_6.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_sound_6.Value.enabled")]),
        new("vbam_layer_1", "Emulation.Option.vbam.vbam_layer_1", "Emulation.Option.vbam.vbam_layer_1.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_layer_1.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_layer_1.Value.enabled")]),
        new("vbam_layer_2", "Emulation.Option.vbam.vbam_layer_2", "Emulation.Option.vbam.vbam_layer_2.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_layer_2.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_layer_2.Value.enabled")]),
        new("vbam_layer_3", "Emulation.Option.vbam.vbam_layer_3", "Emulation.Option.vbam.vbam_layer_3.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_layer_3.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_layer_3.Value.enabled")]),
        new("vbam_layer_4", "Emulation.Option.vbam.vbam_layer_4", "Emulation.Option.vbam.vbam_layer_4.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_layer_4.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_layer_4.Value.enabled")]),
        new("vbam_layer_5", "Emulation.Option.vbam.vbam_layer_5", "Emulation.Option.vbam.vbam_layer_5.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_layer_5.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_layer_5.Value.enabled")]),
        new("vbam_layer_6", "Emulation.Option.vbam.vbam_layer_6", "Emulation.Option.vbam.vbam_layer_6.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_layer_6.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_layer_6.Value.enabled")]),
        new("vbam_layer_7", "Emulation.Option.vbam.vbam_layer_7", "Emulation.Option.vbam.vbam_layer_7.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_layer_7.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_layer_7.Value.enabled")]),
        new("vbam_layer_8", "Emulation.Option.vbam.vbam_layer_8", "Emulation.Option.vbam.vbam_layer_8.Help", "advanced", "enabled", "enabled", [new("disabled", "Emulation.Option.vbam.vbam_layer_8.Value.disabled"), new("enabled", "Emulation.Option.vbam.vbam_layer_8.Value.enabled")])
    ];
}
