using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Panda3ds.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("panda3ds_use_fastmem", "Emulation.Option.panda3ds.panda3ds_use_fastmem", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_use_fastmem.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_use_fastmem.Value.disabled")], Tab: EmulationMachineTab.Cpu),
        new("panda3ds_use_shader_jit", "Emulation.Option.panda3ds.panda3ds_use_shader_jit", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_use_shader_jit.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_use_shader_jit.Value.disabled")], Tab: EmulationMachineTab.Video),
        new("panda3ds_accelerate_shaders", "Emulation.Option.panda3ds.panda3ds_accelerate_shaders", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_accelerate_shaders.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_accelerate_shaders.Value.disabled")], Tab: EmulationMachineTab.Video),
        new("panda3ds_accurate_shader_mul", "Emulation.Option.panda3ds.panda3ds_accurate_shader_mul", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.panda3ds.panda3ds_accurate_shader_mul.Value.disabled"), new("enabled", "Emulation.Option.panda3ds.panda3ds_accurate_shader_mul.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("panda3ds_use_ubershader", "Emulation.Option.panda3ds.panda3ds_use_ubershader", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_use_ubershader.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_use_ubershader.Value.disabled")], Tab: EmulationMachineTab.Video),
        new("panda3ds_use_vsync", "Emulation.Option.panda3ds.panda3ds_use_vsync", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_use_vsync.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_use_vsync.Value.disabled")], Tab: EmulationMachineTab.Video),
        new("panda3ds_hash_textures", "Emulation.Option.panda3ds.panda3ds_hash_textures", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_hash_textures.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_hash_textures.Value.disabled")], Tab: EmulationMachineTab.Video),
        new("panda3ds_system_language", "Emulation.Option.panda3ds.panda3ds_system_language", null, "", "En", "En", [new("En", "En"), new("Fr", "Fr"), new("Es", "Es"), new("De", "De"), new("It", "It"), new("Pt", "Pt"), new("Nl", "Nl"), new("Ru", "Ru"), new("Ja", "Ja"), new("Zh", "Zh"), new("Ko", "Ko"), new("Tw", "Tw")], Tab: EmulationMachineTab.General),
        new("panda3ds_dsp_emulation", "Emulation.Option.panda3ds.panda3ds_dsp_emulation", null, "", "HLE", "HLE", [new("HLE", "Emulation.Option.panda3ds.panda3ds_dsp_emulation.Value.HLE"), new("LLE", "Emulation.Option.panda3ds.panda3ds_dsp_emulation.Value.LLE"), new("Null", "Emulation.Option.panda3ds.panda3ds_dsp_emulation.Value.Null")], Tab: EmulationMachineTab.Audio),
        new("panda3ds_use_audio", "Emulation.Option.panda3ds.panda3ds_use_audio", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_use_audio.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_use_audio.Value.disabled")], Tab: EmulationMachineTab.Audio),
        new("panda3ds_audio_volume", "Emulation.Option.panda3ds.panda3ds_audio_volume", null, "", "100", "100", [new("100", "100"), new("0", "0"), new("10", "10"), new("20", "20"), new("40", "40"), new("60", "60"), new("80", "80"), new("90", "90"), new("120", "120"), new("140", "140"), new("150", "150"), new("180", "180"), new("200", "200")], Tab: EmulationMachineTab.Audio),
        new("panda3ds_mute_audio", "Emulation.Option.panda3ds.panda3ds_mute_audio", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.panda3ds.panda3ds_mute_audio.Value.disabled"), new("enabled", "Emulation.Option.panda3ds.panda3ds_mute_audio.Value.enabled")], Tab: EmulationMachineTab.Audio),
        new("panda3ds_enable_aac", "Emulation.Option.panda3ds.panda3ds_enable_aac", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_enable_aac.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_enable_aac.Value.disabled")], Tab: EmulationMachineTab.Audio),
        new("panda3ds_ubershader_lighting_override", "Emulation.Option.panda3ds.panda3ds_ubershader_lighting_override", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_ubershader_lighting_override.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_ubershader_lighting_override.Value.disabled")], Tab: EmulationMachineTab.Video),
        new("panda3ds_ubershader_lighting_override_threshold", "Emulation.Option.panda3ds.panda3ds_ubershader_lighting_override_threshold", null, "", "1", "1", [new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8")], Tab: EmulationMachineTab.Video),
        new("panda3ds_use_virtual_sd", "Emulation.Option.panda3ds.panda3ds_use_virtual_sd", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_use_virtual_sd.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_use_virtual_sd.Value.disabled")], Tab: EmulationMachineTab.Storage),
        new("panda3ds_write_protect_virtual_sd", "Emulation.Option.panda3ds.panda3ds_write_protect_virtual_sd", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.panda3ds.panda3ds_write_protect_virtual_sd.Value.disabled"), new("enabled", "Emulation.Option.panda3ds.panda3ds_write_protect_virtual_sd.Value.enabled")], Tab: EmulationMachineTab.Storage),
        new("panda3ds_battery_level", "Emulation.Option.panda3ds.panda3ds_battery_level", null, "", "5", "5", [new("5", "5"), new("10", "10"), new("20", "20"), new("30", "30"), new("50", "50"), new("70", "70"), new("90", "90"), new("100", "100")], Tab: EmulationMachineTab.General),
        new("panda3ds_use_charger", "Emulation.Option.panda3ds.panda3ds_use_charger", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.panda3ds.panda3ds_use_charger.Value.enabled"), new("disabled", "Emulation.Option.panda3ds.panda3ds_use_charger.Value.disabled")], Tab: EmulationMachineTab.General)
    ];
}
