using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.MelonDs.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("melonds_console_mode", "Emulation.Option.melonds.melonds_console_mode", null, "system", "DS", "DS", [new("DS", "DS"), new("DSi", "Emulation.Option.melonds.melonds_console_mode.Value.DSi")], Tab: EmulationMachineTab.General),
        new("melonds_boot_directly", "Emulation.Option.melonds.melonds_boot_directly", "Emulation.Option.melonds.melonds_boot_directly.Help", "system", "enabled", "enabled", [new("disabled", "Emulation.Option.melonds.melonds_boot_directly.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_boot_directly.Value.enabled")], Tab: EmulationMachineTab.Rom),
        new("melonds_use_fw_settings", "Emulation.Option.melonds.melonds_use_fw_settings", "Emulation.Option.melonds.melonds_use_fw_settings.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.melonds.melonds_use_fw_settings.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_use_fw_settings.Value.enabled")], Tab: EmulationMachineTab.Rom),
        new("melonds_language", "Emulation.Option.melonds.melonds_language", "Emulation.Option.melonds.melonds_language.Help", "system", "English", "English", [new("Japanese", "Emulation.Option.melonds.melonds_language.Value.Japanese"), new("English", "Emulation.Option.melonds.melonds_language.Value.English"), new("French", "Emulation.Option.melonds.melonds_language.Value.French"), new("German", "Emulation.Option.melonds.melonds_language.Value.German"), new("Italian", "Emulation.Option.melonds.melonds_language.Value.Italian"), new("Spanish", "Emulation.Option.melonds.melonds_language.Value.Spanish")], Tab: EmulationMachineTab.General),
        new("melonds_randomize_mac_address", "Emulation.Option.melonds.melonds_randomize_mac_address", null, "system", "disabled", "disabled", [new("disabled", "Emulation.Option.melonds.melonds_randomize_mac_address.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_randomize_mac_address.Value.enabled")], Tab: EmulationMachineTab.General),
        new("melonds_dsi_sdcard", "Emulation.Option.melonds.melonds_dsi_sdcard", null, "system", "disabled", "disabled", [new("disabled", "Emulation.Option.melonds.melonds_dsi_sdcard.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_dsi_sdcard.Value.enabled")], Tab: EmulationMachineTab.Storage),
        new("melonds_threaded_renderer", "Emulation.Option.melonds.melonds_threaded_renderer", null, "video", "disabled", "disabled", [new("disabled", "Emulation.Option.melonds.melonds_threaded_renderer.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_threaded_renderer.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("melonds_opengl_renderer", "Emulation.Option.melonds.melonds_opengl_renderer", null, "video", "disabled", "disabled", [new("disabled", "Emulation.Option.melonds.melonds_opengl_renderer.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_opengl_renderer.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: true),
        new("melonds_opengl_resolution", "Emulation.Option.melonds.melonds_opengl_resolution", null, "video", "1x native (256x192)", "1x native (256x192)", [new("1x native (256x192)", "Emulation.Option.melonds.melonds_opengl_resolution.Value.1x native (256x192)"), new("2x native (512x384)", "Emulation.Option.melonds.melonds_opengl_resolution.Value.2x native (512x384)"), new("3x native (768x576)", "Emulation.Option.melonds.melonds_opengl_resolution.Value.3x native (768x576)"), new("4x native (1024x768)", "Emulation.Option.melonds.melonds_opengl_resolution.Value.4x native (1024x768)"), new("5x native (1280x960)", "Emulation.Option.melonds.melonds_opengl_resolution.Value.5x native (1280x960)"), new("6x native (1536x1152)", "Emulation.Option.melonds.melonds_opengl_resolution.Value.6x native (1536x1152)"), new("7x native (1792x1344)", "Emulation.Option.melonds.melonds_opengl_resolution.Value.7x native (1792x1344)"), new("8x native (2048x1536)", "Emulation.Option.melonds.melonds_opengl_resolution.Value.8x native (2048x1536)")], Tab: EmulationMachineTab.Video),
        new("melonds_opengl_better_polygons", "Emulation.Option.melonds.melonds_opengl_better_polygons", null, "video", "disabled", "disabled", [new("disabled", "Emulation.Option.melonds.melonds_opengl_better_polygons.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_opengl_better_polygons.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("melonds_opengl_filtering", "Emulation.Option.melonds.melonds_opengl_filtering", null, "video", "nearest", "nearest", [new("nearest", "Emulation.Option.melonds.melonds_opengl_filtering.Value.nearest"), new("linear", "Emulation.Option.melonds.melonds_opengl_filtering.Value.linear")], Tab: EmulationMachineTab.Video),
        new("melonds_mic_input", "Emulation.Option.melonds.melonds_mic_input", "Emulation.Option.melonds.melonds_mic_input.Help", "audio", "Blow Noise", "Blow Noise", [new("Blow Noise", "Emulation.Option.melonds.melonds_mic_input.Value.Blow Noise"), new("White Noise", "Emulation.Option.melonds.melonds_mic_input.Value.White Noise")], Tab: EmulationMachineTab.Audio),
        new("melonds_audio_bitrate", "Emulation.Option.melonds.melonds_audio_bitrate", null, "audio", "Automatic", "Automatic", [new("Automatic", "Emulation.Option.melonds.melonds_audio_bitrate.Value.Automatic"), new("10-bit", "Emulation.Option.melonds.melonds_audio_bitrate.Value.10-bit"), new("16-bit", "Emulation.Option.melonds.melonds_audio_bitrate.Value.16-bit")], Tab: EmulationMachineTab.Audio),
        new("melonds_audio_interpolation", "Emulation.Option.melonds.melonds_audio_interpolation", null, "audio", "None", "None", [new("None", "Emulation.Option.melonds.melonds_audio_interpolation.Value.None"), new("Linear", "Emulation.Option.melonds.melonds_audio_interpolation.Value.Linear"), new("Cosine", "Emulation.Option.melonds.melonds_audio_interpolation.Value.Cosine"), new("Cubic", "Emulation.Option.melonds.melonds_audio_interpolation.Value.Cubic")], Tab: EmulationMachineTab.Audio),
        new("melonds_touch_mode", "Emulation.Option.melonds.melonds_touch_mode", "Emulation.Option.melonds.melonds_touch_mode.Help", "screen", "Mouse", "Mouse", [new("Mouse", "Emulation.Option.melonds.melonds_touch_mode.Value.Mouse"), new("Touch", "Emulation.Option.melonds.melonds_touch_mode.Value.Touch"), new("Joystick", "Emulation.Option.melonds.melonds_touch_mode.Value.Joystick"), new("disabled", "Emulation.Option.melonds.melonds_touch_mode.Value.disabled")], Tab: EmulationMachineTab.Mouse),
        new("melonds_swapscreen_mode", "Emulation.Option.melonds.melonds_swapscreen_mode", "Emulation.Option.melonds.melonds_swapscreen_mode.Help", "screen", "Toggle", "Toggle", [new("Toggle", "Emulation.Option.melonds.melonds_swapscreen_mode.Value.Toggle"), new("Hold", "Emulation.Option.melonds.melonds_swapscreen_mode.Value.Hold")], Tab: EmulationMachineTab.Video),
        new("melonds_screen_layout", "Emulation.Option.melonds.melonds_screen_layout", "Emulation.Option.melonds.melonds_screen_layout.Help", "screen", "Top/Bottom", "Top/Bottom", [new("Top/Bottom", "Emulation.Option.melonds.melonds_screen_layout.Value.Top/Bottom"), new("Bottom/Top", "Emulation.Option.melonds.melonds_screen_layout.Value.Bottom/Top"), new("Left/Right", "Emulation.Option.melonds.melonds_screen_layout.Value.Left/Right"), new("Right/Left", "Emulation.Option.melonds.melonds_screen_layout.Value.Right/Left"), new("Top Only", "Emulation.Option.melonds.melonds_screen_layout.Value.Top Only"), new("Bottom Only", "Emulation.Option.melonds.melonds_screen_layout.Value.Bottom Only"), new("Hybrid Top", "Emulation.Option.melonds.melonds_screen_layout.Value.Hybrid Top"), new("Hybrid Bottom", "Emulation.Option.melonds.melonds_screen_layout.Value.Hybrid Bottom")], Tab: EmulationMachineTab.Video),
        new("melonds_screen_gap", "Emulation.Option.melonds.melonds_screen_gap", "Emulation.Option.melonds.melonds_screen_gap.Help", "screen", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24"), new("25", "25"), new("26", "26"), new("27", "27"), new("28", "28"), new("29", "29"), new("30", "30"), new("31", "31"), new("32", "32"), new("33", "33"), new("34", "34"), new("35", "35"), new("36", "36"), new("37", "37"), new("38", "38"), new("39", "39"), new("40", "40"), new("41", "41"), new("42", "42"), new("43", "43"), new("44", "44"), new("45", "45"), new("46", "46"), new("47", "47"), new("48", "48"), new("49", "49"), new("50", "50"), new("51", "51"), new("52", "52"), new("53", "53"), new("54", "54"), new("55", "55"), new("56", "56"), new("57", "57"), new("58", "58"), new("59", "59"), new("60", "60"), new("61", "61"), new("62", "62"), new("63", "63"), new("64", "64"), new("65", "65"), new("66", "66"), new("67", "67"), new("68", "68"), new("69", "69"), new("70", "70"), new("71", "71"), new("72", "72"), new("73", "73"), new("74", "74"), new("75", "75"), new("76", "76"), new("77", "77"), new("78", "78"), new("79", "79"), new("80", "80"), new("81", "81"), new("82", "82"), new("83", "83"), new("84", "84"), new("85", "85"), new("86", "86"), new("87", "87"), new("88", "88"), new("89", "89"), new("90", "90"), new("91", "91"), new("92", "92"), new("93", "93"), new("94", "94"), new("95", "95"), new("96", "96"), new("97", "97"), new("98", "98"), new("99", "99"), new("100", "100"), new("101", "101"), new("102", "102"), new("103", "103"), new("104", "104"), new("105", "105"), new("106", "106"), new("107", "107"), new("108", "108"), new("109", "109"), new("110", "110"), new("111", "111"), new("112", "112"), new("113", "113"), new("114", "114"), new("115", "115"), new("116", "116"), new("117", "117"), new("118", "118"), new("119", "119"), new("120", "120"), new("121", "121"), new("122", "122"), new("123", "123"), new("124", "124"), new("125", "125"), new("126", "126")], Tab: EmulationMachineTab.Video),
        new("melonds_hybrid_small_screen", "Emulation.Option.melonds.melonds_hybrid_small_screen", "Emulation.Option.melonds.melonds_hybrid_small_screen.Help", "screen", "Bottom", "Bottom", [new("Bottom", "Emulation.Option.melonds.melonds_hybrid_small_screen.Value.Bottom"), new("Top", "Emulation.Option.melonds.melonds_hybrid_small_screen.Value.Top"), new("Duplicate", "Emulation.Option.melonds.melonds_hybrid_small_screen.Value.Duplicate")], Tab: EmulationMachineTab.Video),
        new("melonds_hybrid_ratio", "Emulation.Option.melonds.melonds_hybrid_ratio", null, "screen", "2", "2", [new("2", "2"), new("3", "3")], Tab: EmulationMachineTab.Video),
        new("melonds_jit_enable", "Emulation.Option.melonds.melonds_jit_enable", null, "cpu", "enabled", "enabled", [new("disabled", "Emulation.Option.melonds.melonds_jit_enable.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_jit_enable.Value.enabled")], Tab: EmulationMachineTab.Cpu, RequiresRestart: true),
        new("melonds_jit_block_size", "Emulation.Option.melonds.melonds_jit_block_size", null, "cpu", "32", "32", [new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24"), new("25", "25"), new("26", "26"), new("27", "27"), new("28", "28"), new("29", "29"), new("30", "30"), new("31", "31"), new("32", "32")], Tab: EmulationMachineTab.Cpu),
        new("melonds_jit_branch_optimisations", "Emulation.Option.melonds.melonds_jit_branch_optimisations", null, "cpu", "enabled", "enabled", [new("disabled", "Emulation.Option.melonds.melonds_jit_branch_optimisations.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_jit_branch_optimisations.Value.enabled")], Tab: EmulationMachineTab.Cpu),
        new("melonds_jit_literal_optimisations", "Emulation.Option.melonds.melonds_jit_literal_optimisations", null, "cpu", "enabled", "enabled", [new("disabled", "Emulation.Option.melonds.melonds_jit_literal_optimisations.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_jit_literal_optimisations.Value.enabled")], Tab: EmulationMachineTab.Cpu),
        new("melonds_jit_fast_memory", "Emulation.Option.melonds.melonds_jit_fast_memory", null, "cpu", "enabled", "enabled", [new("disabled", "Emulation.Option.melonds.melonds_jit_fast_memory.Value.disabled"), new("enabled", "Emulation.Option.melonds.melonds_jit_fast_memory.Value.enabled")], Tab: EmulationMachineTab.Ram)
    ];
}
