<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <VSTestTestCaseFilter>(Category!=LocalAssets)&amp;(Category!=GpuExhaustive)</VSTestTestCaseFilter>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GWGUI.Domain\GWGUI.Domain.csproj" />
    <ProjectReference Include="..\..\src\GWGUI.Infrastructure\GWGUI.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\GWGUI.MediaEngine\GWGUI.MediaEngine.csproj" />
    <ProjectReference Include="..\..\src\GWGUI.App\GWGUI.App.csproj" />
    <ProjectReference Include="..\..\src\GWGUI.Emulation\GWGUI.Emulation.csproj" />
    <ProjectReference Include="..\..\src\GWGUI.Emulation.Amiga\GWGUI.Emulation.Amiga.csproj" />
    <ProjectReference Include="..\..\src\GWGUI.Emulation.Atari\GWGUI.Emulation.Atari.csproj" />
  </ItemGroup>

</Project>
