using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Bsnes.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("bsnes_aspect_ratio", "Emulation.Option.bsnes.bsnes_aspect_ratio", "Emulation.Option.bsnes.bsnes_aspect_ratio.Help", "video", "Auto", "Auto", [new("Auto", "Emulation.Option.bsnes.bsnes_aspect_ratio.Value.Auto"), new("1:1", "Emulation.Option.bsnes.bsnes_aspect_ratio.Value.1:1"), new("4:3", "Emulation.Option.bsnes.bsnes_aspect_ratio.Value.4:3"), new("NTSC", "Emulation.Option.bsnes.bsnes_aspect_ratio.Value.NTSC"), new("PAL", "Emulation.Option.bsnes.bsnes_aspect_ratio.Value.PAL")], Tab: EmulationMachineTab.Video),
        new("bsnes_ppu_overscan_v", "Emulation.Option.bsnes.bsnes_ppu_overscan_v", "Emulation.Option.bsnes.bsnes_ppu_overscan_v.Help", "video", "8", "8", [new("0", "Emulation.Option.bsnes.bsnes_ppu_overscan_v.Value.0"), new("8", "Emulation.Option.bsnes.bsnes_ppu_overscan_v.Value.8"), new("12", "Emulation.Option.bsnes.bsnes_ppu_overscan_v.Value.12"), new("16", "Emulation.Option.bsnes.bsnes_ppu_overscan_v.Value.16")], Tab: EmulationMachineTab.Video),
        new("bsnes_blur_emulation", "Emulation.Option.bsnes.bsnes_blur_emulation", "Emulation.Option.bsnes.bsnes_blur_emulation.Help", "video", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_blur_emulation.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_blur_emulation.Value.ON")], Tab: EmulationMachineTab.Video),
        new("bsnes_video_filter", "Emulation.Option.bsnes.bsnes_video_filter", "Emulation.Option.bsnes.bsnes_video_filter.Help", "video", "None", "None", [new("None", "Emulation.Option.bsnes.bsnes_video_filter.Value.None"), new("NTSC (RF)", "Emulation.Option.bsnes.bsnes_video_filter.Value.NTSC (RF)"), new("NTSC (Composite)", "Emulation.Option.bsnes.bsnes_video_filter.Value.NTSC (Composite)"), new("NTSC (S-Video)", "Emulation.Option.bsnes.bsnes_video_filter.Value.NTSC (S-Video)"), new("NTSC (RGB)", "Emulation.Option.bsnes.bsnes_video_filter.Value.NTSC (RGB)")], Tab: EmulationMachineTab.Video),
        new("bsnes_video_luminance", "Emulation.Option.bsnes.bsnes_video_luminance", "Emulation.Option.bsnes.bsnes_video_luminance.Help", "video", "100", "100", [new("0", "0%"), new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "Emulation.Option.bsnes.bsnes_video_luminance.Value.100")], Tab: EmulationMachineTab.Video),
        new("bsnes_video_saturation", "Emulation.Option.bsnes.bsnes_video_saturation", "Emulation.Option.bsnes.bsnes_video_saturation.Help", "video", "100", "100", [new("0", "0%"), new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "Emulation.Option.bsnes.bsnes_video_saturation.Value.100"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%")], Tab: EmulationMachineTab.Video),
        new("bsnes_video_gamma", "Emulation.Option.bsnes.bsnes_video_gamma", "Emulation.Option.bsnes.bsnes_video_gamma.Help", "video", "150", "150", [new("100", "100%"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "Emulation.Option.bsnes.bsnes_video_gamma.Value.150"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%")], Tab: EmulationMachineTab.Video),
        new("bsnes_ppu_fast", "Emulation.Option.bsnes.bsnes_ppu_fast", "Emulation.Option.bsnes.bsnes_ppu_fast.Help", "video", "ON", "ON", [new("ON", "Emulation.Option.bsnes.bsnes_ppu_fast.Value.ON"), new("OFF", "Emulation.Option.bsnes.bsnes_ppu_fast.Value.OFF")], Tab: EmulationMachineTab.Video),
        new("bsnes_ppu_deinterlace", "Emulation.Option.bsnes.bsnes_ppu_deinterlace", "Emulation.Option.bsnes.bsnes_ppu_deinterlace.Help", "video", "ON", "ON", [new("ON", "Emulation.Option.bsnes.bsnes_ppu_deinterlace.Value.ON"), new("OFF", "Emulation.Option.bsnes.bsnes_ppu_deinterlace.Value.OFF")], Tab: EmulationMachineTab.Video),
        new("bsnes_ppu_no_sprite_limit", "Emulation.Option.bsnes.bsnes_ppu_no_sprite_limit", "Emulation.Option.bsnes.bsnes_ppu_no_sprite_limit.Help", "video", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_ppu_no_sprite_limit.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_ppu_no_sprite_limit.Value.ON")], Tab: EmulationMachineTab.Video),
        new("bsnes_ppu_no_vram_blocking", "Emulation.Option.bsnes.bsnes_ppu_no_vram_blocking", "Emulation.Option.bsnes.bsnes_ppu_no_vram_blocking.Help", "video", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_ppu_no_vram_blocking.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_ppu_no_vram_blocking.Value.ON")], Tab: EmulationMachineTab.Video),
        new("bsnes_dsp_fast", "Emulation.Option.bsnes.bsnes_dsp_fast", "Emulation.Option.bsnes.bsnes_dsp_fast.Help", "audio", "ON", "ON", [new("ON", "Emulation.Option.bsnes.bsnes_dsp_fast.Value.ON"), new("OFF", "Emulation.Option.bsnes.bsnes_dsp_fast.Value.OFF")], Tab: EmulationMachineTab.Audio),
        new("bsnes_dsp_cubic", "Emulation.Option.bsnes.bsnes_dsp_cubic", "Emulation.Option.bsnes.bsnes_dsp_cubic.Help", "audio", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_dsp_cubic.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_dsp_cubic.Value.ON")], Tab: EmulationMachineTab.Audio),
        new("bsnes_dsp_echo_shadow", "Emulation.Option.bsnes.bsnes_dsp_echo_shadow", "Emulation.Option.bsnes.bsnes_dsp_echo_shadow.Help", "audio", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_dsp_echo_shadow.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_dsp_echo_shadow.Value.ON")], Tab: EmulationMachineTab.Audio),
        new("bsnes_mode7_scale", "Emulation.Option.bsnes.bsnes_mode7_scale", "Emulation.Option.bsnes.bsnes_mode7_scale.Help", "mode7", "1x", "1x", [new("1x", "240p (1x)"), new("2x", "480p (2x)"), new("3x", "720p (3x)"), new("4x", "960p (4x)"), new("5x", "1200p (5x)"), new("6x", "1440p (6x)"), new("7x", "1680p (7x)"), new("8x", "1920p (8x)")], Tab: EmulationMachineTab.Video),
        new("bsnes_mode7_perspective", "Emulation.Option.bsnes.bsnes_mode7_perspective", "Emulation.Option.bsnes.bsnes_mode7_perspective.Help", "mode7", "ON", "ON", [new("ON", "Emulation.Option.bsnes.bsnes_mode7_perspective.Value.ON"), new("OFF", "Emulation.Option.bsnes.bsnes_mode7_perspective.Value.OFF")], Tab: EmulationMachineTab.Video),
        new("bsnes_mode7_supersample", "Emulation.Option.bsnes.bsnes_mode7_supersample", "Emulation.Option.bsnes.bsnes_mode7_supersample.Help", "mode7", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_mode7_supersample.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_mode7_supersample.Value.ON")], Tab: EmulationMachineTab.Video),
        new("bsnes_mode7_mosaic", "Emulation.Option.bsnes.bsnes_mode7_mosaic", "Emulation.Option.bsnes.bsnes_mode7_mosaic.Help", "mode7", "ON", "ON", [new("ON", "Emulation.Option.bsnes.bsnes_mode7_mosaic.Value.ON"), new("OFF", "Emulation.Option.bsnes.bsnes_mode7_mosaic.Value.OFF")], Tab: EmulationMachineTab.Video),
        new("bsnes_run_ahead_frames", "Emulation.Option.bsnes.bsnes_run_ahead_frames", "Emulation.Option.bsnes.bsnes_run_ahead_frames.Help", "hack", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_run_ahead_frames.Value.OFF"), new("1", "Emulation.Option.bsnes.bsnes_run_ahead_frames.Value.1"), new("2", "Emulation.Option.bsnes.bsnes_run_ahead_frames.Value.2"), new("3", "Emulation.Option.bsnes.bsnes_run_ahead_frames.Value.3"), new("4", "Emulation.Option.bsnes.bsnes_run_ahead_frames.Value.4")], Tab: EmulationMachineTab.General),
        new("bsnes_coprocessor_delayed_sync", "Emulation.Option.bsnes.bsnes_coprocessor_delayed_sync", "Emulation.Option.bsnes.bsnes_coprocessor_delayed_sync.Help", "hack", "ON", "ON", [new("ON", "Emulation.Option.bsnes.bsnes_coprocessor_delayed_sync.Value.ON"), new("OFF", "Emulation.Option.bsnes.bsnes_coprocessor_delayed_sync.Value.OFF")], Tab: EmulationMachineTab.Cpu),
        new("bsnes_coprocessor_prefer_hle", "Emulation.Option.bsnes.bsnes_coprocessor_prefer_hle", "Emulation.Option.bsnes.bsnes_coprocessor_prefer_hle.Help", "hack", "ON", "ON", [new("ON", "Emulation.Option.bsnes.bsnes_coprocessor_prefer_hle.Value.ON"), new("OFF", "Emulation.Option.bsnes.bsnes_coprocessor_prefer_hle.Value.OFF")], Tab: EmulationMachineTab.Rom),
        new("bsnes_hotfixes", "Emulation.Option.bsnes.bsnes_hotfixes", "Emulation.Option.bsnes.bsnes_hotfixes.Help", "hack", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_hotfixes.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_hotfixes.Value.ON")], Tab: EmulationMachineTab.General),
        new("bsnes_entropy", "Emulation.Option.bsnes.bsnes_entropy", "Emulation.Option.bsnes.bsnes_entropy.Help", "hack", "Low", "Low", [new("Low", "Emulation.Option.bsnes.bsnes_entropy.Value.Low"), new("High", "Emulation.Option.bsnes.bsnes_entropy.Value.High"), new("None", "Emulation.Option.bsnes.bsnes_entropy.Value.None")], Tab: EmulationMachineTab.Ram),
        new("bsnes_cpu_fastmath", "Emulation.Option.bsnes.bsnes_cpu_fastmath", "Emulation.Option.bsnes.bsnes_cpu_fastmath.Help", "hack", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_cpu_fastmath.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_cpu_fastmath.Value.ON")], Tab: EmulationMachineTab.Cpu),
        new("bsnes_cpu_overclock", "Emulation.Option.bsnes.bsnes_cpu_overclock", "Emulation.Option.bsnes.bsnes_cpu_overclock.Help", "overclock", "100", "100", [new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "Emulation.Option.bsnes.bsnes_cpu_overclock.Value.100"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%"), new("210", "210%"), new("220", "220%"), new("230", "230%"), new("240", "240%"), new("250", "250%"), new("260", "260%"), new("270", "270%"), new("280", "280%"), new("290", "290%"), new("300", "300%"), new("310", "310%"), new("320", "320%"), new("330", "330%"), new("340", "340%"), new("350", "350%"), new("360", "360%"), new("370", "370%"), new("380", "380%"), new("390", "390%"), new("400", "400%")], Tab: EmulationMachineTab.Cpu),
        new("bsnes_cpu_sa1_overclock", "Emulation.Option.bsnes.bsnes_cpu_sa1_overclock", "Emulation.Option.bsnes.bsnes_cpu_sa1_overclock.Help", "overclock", "100", "100", [new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "Emulation.Option.bsnes.bsnes_cpu_sa1_overclock.Value.100"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%"), new("210", "210%"), new("220", "220%"), new("230", "230%"), new("240", "240%"), new("250", "250%"), new("260", "260%"), new("270", "270%"), new("280", "280%"), new("290", "290%"), new("300", "300%"), new("310", "310%"), new("320", "320%"), new("330", "330%"), new("340", "340%"), new("350", "350%"), new("360", "360%"), new("370", "370%"), new("380", "380%"), new("390", "390%"), new("400", "400%")], Tab: EmulationMachineTab.Cpu),
        new("bsnes_cpu_sfx_overclock", "Emulation.Option.bsnes.bsnes_cpu_sfx_overclock", "Emulation.Option.bsnes.bsnes_cpu_sfx_overclock.Help", "overclock", "100", "100", [new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "Emulation.Option.bsnes.bsnes_cpu_sfx_overclock.Value.100"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%"), new("210", "210%"), new("220", "220%"), new("230", "230%"), new("240", "240%"), new("250", "250%"), new("260", "260%"), new("270", "270%"), new("280", "280%"), new("290", "290%"), new("300", "300%"), new("310", "310%"), new("320", "320%"), new("330", "330%"), new("340", "340%"), new("350", "350%"), new("360", "360%"), new("370", "370%"), new("380", "380%"), new("390", "390%"), new("400", "400%"), new("410", "410%"), new("420", "420%"), new("430", "430%"), new("440", "440%"), new("450", "450%"), new("460", "460%"), new("470", "470%"), new("480", "480%"), new("490", "490%"), new("500", "500%"), new("510", "510%"), new("520", "520%"), new("530", "530%"), new("540", "540%"), new("550", "550%"), new("560", "560%"), new("570", "570%"), new("580", "580%"), new("590", "590%"), new("600", "600%"), new("610", "610%"), new("620", "620%"), new("630", "630%"), new("640", "640%"), new("650", "650%"), new("660", "660%"), new("670", "670%"), new("680", "680%"), new("690", "690%"), new("700", "700%"), new("710", "710%"), new("720", "720%"), new("730", "730%"), new("740", "740%"), new("750", "750%"), new("760", "760%"), new("770", "770%"), new("780", "780%"), new("790", "790%"), new("800", "800%")], Tab: EmulationMachineTab.Cpu),
        new("bsnes_sgb_bios", "Emulation.Option.bsnes.bsnes_sgb_bios", "Emulation.Option.bsnes.bsnes_sgb_bios.Help", "sgb", "SGB1.sfc", "SGB1.sfc", [new("SGB1.sfc", "Emulation.Option.bsnes.bsnes_sgb_bios.Value.SGB1.sfc"), new("SGB2.sfc", "Emulation.Option.bsnes.bsnes_sgb_bios.Value.SGB2.sfc")], Tab: EmulationMachineTab.Rom, RequiresRestart: true),
        new("bsnes_hide_sgb_border", "Emulation.Option.bsnes.bsnes_hide_sgb_border", "Emulation.Option.bsnes.bsnes_hide_sgb_border.Help", "sgb", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_hide_sgb_border.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_hide_sgb_border.Value.ON")], Tab: EmulationMachineTab.Video),
        new("bsnes_touchscreen_lightgun", "Emulation.Option.bsnes.bsnes_touchscreen_lightgun", "Emulation.Option.bsnes.bsnes_touchscreen_lightgun.Help", "lightgun", "ON", "ON", [new("ON", "Emulation.Option.bsnes.bsnes_touchscreen_lightgun.Value.ON"), new("OFF", "Emulation.Option.bsnes.bsnes_touchscreen_lightgun.Value.OFF")], Tab: EmulationMachineTab.Mouse),
        new("bsnes_touchscreen_lightgun_superscope_reverse", "Emulation.Option.bsnes.bsnes_touchscreen_lightgun_superscope_reverse", "Emulation.Option.bsnes.bsnes_touchscreen_lightgun_superscope_reverse.Help", "lightgun", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes.bsnes_touchscreen_lightgun_superscope_reverse.Value.OFF"), new("ON", "Emulation.Option.bsnes.bsnes_touchscreen_lightgun_superscope_reverse.Value.ON")], Tab: EmulationMachineTab.Mouse)
    ];
}
