using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Azahar.Constants;

internal static class OptionConstants
{
    internal const string GraphicsApiOption = "citra_graphics_api";
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("citra_use_cpu_jit", "Emulation.Option.azahar.citra_use_cpu_jit", "Emulation.Option.azahar.citra_use_cpu_jit.Help", "cpu", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_use_cpu_jit.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_use_cpu_jit.Value.disabled")]),
        new("citra_cpu_clock_percentage", "Emulation.Option.azahar.citra_cpu_clock_percentage", "Emulation.Option.azahar.citra_cpu_clock_percentage.Help", "cpu", "100", "100", [new("25", "25%"), new("50", "50%"), new("75", "75%"), new("100", "Emulation.Option.azahar.citra_cpu_clock_percentage.Value.100"), new("125", "125%"), new("150", "150%"), new("175", "175%"), new("200", "200%"), new("225", "225%"), new("250", "250%"), new("275", "275%"), new("300", "300%"), new("325", "325%"), new("350", "350%"), new("375", "375%"), new("400", "400%")]),
        new("citra_is_new_3ds", "Emulation.Option.azahar.citra_is_new_3ds", "Emulation.Option.azahar.citra_is_new_3ds.Help", "system", "New 3DS", "New 3DS", [new("New 3DS", "Emulation.Option.azahar.citra_is_new_3ds.Value.New 3DS"), new("Old 3DS", "Emulation.Option.azahar.citra_is_new_3ds.Value.Old 3DS")]),
        new("citra_region_value", "Emulation.Option.azahar.citra_region_value", "Emulation.Option.azahar.citra_region_value.Help", "system", "Auto", "Auto", [new("Auto", "Emulation.Option.azahar.citra_region_value.Value.Auto"), new("Japan", "Emulation.Option.azahar.citra_region_value.Value.Japan"), new("USA", "Emulation.Option.azahar.citra_region_value.Value.USA"), new("Europe", "Emulation.Option.azahar.citra_region_value.Value.Europe"), new("Australia", "Emulation.Option.azahar.citra_region_value.Value.Australia"), new("China", "Emulation.Option.azahar.citra_region_value.Value.China"), new("Korea", "Emulation.Option.azahar.citra_region_value.Value.Korea"), new("Taiwan", "Emulation.Option.azahar.citra_region_value.Value.Taiwan")]),
        new("citra_language_value", "Emulation.Option.azahar.citra_language_value", "Emulation.Option.azahar.citra_language_value.Help", "system", "English", "English", [new("English", "Emulation.Option.azahar.citra_language_value.Value.English"), new("Japanese", "Emulation.Option.azahar.citra_language_value.Value.Japanese"), new("French", "Emulation.Option.azahar.citra_language_value.Value.French"), new("Spanish", "Emulation.Option.azahar.citra_language_value.Value.Spanish"), new("German", "Emulation.Option.azahar.citra_language_value.Value.German"), new("Italian", "Emulation.Option.azahar.citra_language_value.Value.Italian"), new("Dutch", "Emulation.Option.azahar.citra_language_value.Value.Dutch"), new("Portuguese", "Emulation.Option.azahar.citra_language_value.Value.Portuguese"), new("Russian", "Emulation.Option.azahar.citra_language_value.Value.Russian"), new("Korean", "Emulation.Option.azahar.citra_language_value.Value.Korean"), new("Traditional Chinese", "Emulation.Option.azahar.citra_language_value.Value.Traditional Chinese"), new("Simplified Chinese", "Emulation.Option.azahar.citra_language_value.Value.Simplified Chinese")]),
        new("citra_audio_emulation", "Emulation.Option.azahar.citra_audio_emulation", "Emulation.Option.azahar.citra_audio_emulation.Help", "audio", "hle", "hle", [new("hle", "Emulation.Option.azahar.citra_audio_emulation.Value.hle"), new("lle", "Emulation.Option.azahar.citra_audio_emulation.Value.lle"), new("lle_multithread", "Emulation.Option.azahar.citra_audio_emulation.Value.lle_multithread")]),
        new("citra_input_type", "Emulation.Option.azahar.citra_input_type", "Emulation.Option.azahar.citra_input_type.Help", "audio", "auto", "auto", [new("auto", "Emulation.Option.azahar.citra_input_type.Value.auto"), new("none", "Emulation.Option.azahar.citra_input_type.Value.none"), new("static_noise", "Emulation.Option.azahar.citra_input_type.Value.static_noise"), new("frontend", "Emulation.Option.azahar.citra_input_type.Value.frontend")]),
        new(GraphicsApiOption, "Emulation.Option.azahar.citra_graphics_api", "Emulation.Option.azahar.citra_graphics_api.Help", "graphics", "Auto", "Auto", [new("Auto", "Emulation.Option.azahar.citra_graphics_api.Value.Auto"), new("Vulkan", "Emulation.Option.azahar.citra_graphics_api.Value.Vulkan"), new("OpenGL", "Emulation.Option.azahar.citra_graphics_api.Value.OpenGL"), new("Software", "Emulation.Option.azahar.citra_graphics_api.Value.Software")]),
        new("citra_use_hw_shader", "Emulation.Option.azahar.citra_use_hw_shader", "Emulation.Option.azahar.citra_use_hw_shader.Help", "graphics", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_use_hw_shader.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_use_hw_shader.Value.disabled")]),
        new("citra_use_shader_jit", "Emulation.Option.azahar.citra_use_shader_jit", "Emulation.Option.azahar.citra_use_shader_jit.Help", "graphics", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_use_shader_jit.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_use_shader_jit.Value.disabled")]),
        new("citra_shaders_accurate_mul", "Emulation.Option.azahar.citra_shaders_accurate_mul", "Emulation.Option.azahar.citra_shaders_accurate_mul.Help", "graphics", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_shaders_accurate_mul.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_shaders_accurate_mul.Value.disabled")]),
        new("citra_use_disk_shader_cache", "Emulation.Option.azahar.citra_use_disk_shader_cache", "Emulation.Option.azahar.citra_use_disk_shader_cache.Help", "graphics", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_use_disk_shader_cache.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_use_disk_shader_cache.Value.disabled")]),
        new("citra_resolution_factor", "Emulation.Option.azahar.citra_resolution_factor", "Emulation.Option.azahar.citra_resolution_factor.Help", "graphics", "1", "1", [new("1", "Emulation.Option.azahar.citra_resolution_factor.Value.1"), new("2", "2x (800x480)"), new("3", "3x (1200x720)"), new("4", "4x (1600x960)"), new("5", "5x (2000x1200)"), new("6", "6x (2400x1440)"), new("7", "7x (2800x1680)"), new("8", "8x (3200x1920)"), new("9", "9x (3600x2160)"), new("10", "10x (4000x2400)"), new("11", "11x (4400x2640)"), new("12", "12x (4800x2880)"), new("13", "13x (5200x3120)"), new("14", "14x (5600x3360)"), new("15", "15x (6000x3600)"), new("16", "16x (6400x3840)"), new("17", "17x (6800x4080)"), new("18", "18x (7200x4320)")]),
        new("citra_texture_filter", "Emulation.Option.azahar.citra_texture_filter", "Emulation.Option.azahar.citra_texture_filter.Help", "graphics", "none", "none", [new("none", "Emulation.Option.azahar.citra_texture_filter.Value.none"), new("Anime4K Ultrafast", "Emulation.Option.azahar.citra_texture_filter.Value.Anime4K Ultrafast"), new("Bicubic", "Emulation.Option.azahar.citra_texture_filter.Value.Bicubic"), new("ScaleForce", "Emulation.Option.azahar.citra_texture_filter.Value.ScaleForce"), new("xBRZ", "Emulation.Option.azahar.citra_texture_filter.Value.xBRZ"), new("MMPX", "Emulation.Option.azahar.citra_texture_filter.Value.MMPX")]),
        new("citra_texture_sampling", "Emulation.Option.azahar.citra_texture_sampling", "Emulation.Option.azahar.citra_texture_sampling.Help", "graphics", "GameControlled", "GameControlled", [new("GameControlled", "Emulation.Option.azahar.citra_texture_sampling.Value.GameControlled"), new("NearestNeighbor", "Emulation.Option.azahar.citra_texture_sampling.Value.NearestNeighbor"), new("Linear", "Emulation.Option.azahar.citra_texture_sampling.Value.Linear")]),
        new("citra_custom_textures", "Emulation.Option.azahar.citra_custom_textures", "Emulation.Option.azahar.citra_custom_textures.Help", "graphics", "disabled", "disabled", [new("enabled", "Emulation.Option.azahar.citra_custom_textures.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_custom_textures.Value.disabled")]),
        new("citra_dump_textures", "Emulation.Option.azahar.citra_dump_textures", "Emulation.Option.azahar.citra_dump_textures.Help", "graphics", "disabled", "disabled", [new("enabled", "Emulation.Option.azahar.citra_dump_textures.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_dump_textures.Value.disabled")]),
        new("citra_layout_option", "Emulation.Option.azahar.citra_layout_option", "Emulation.Option.azahar.citra_layout_option.Help", "layout", "default", "default", [new("default", "Emulation.Option.azahar.citra_layout_option.Value.default"), new("single_screen", "Emulation.Option.azahar.citra_layout_option.Value.single_screen"), new("large_screen", "Emulation.Option.azahar.citra_layout_option.Value.large_screen"), new("side_by_side", "Emulation.Option.azahar.citra_layout_option.Value.side_by_side")]),
        new("citra_swap_screen", "Emulation.Option.azahar.citra_swap_screen", "Emulation.Option.azahar.citra_swap_screen.Help", "layout", "Top", "Top", [new("Top", "Emulation.Option.azahar.citra_swap_screen.Value.Top"), new("Bottom", "Emulation.Option.azahar.citra_swap_screen.Value.Bottom")]),
        new("citra_swap_screen_mode", "Emulation.Option.azahar.citra_swap_screen_mode", "Emulation.Option.azahar.citra_swap_screen_mode.Help", "layout", "Toggle", "Toggle", [new("Toggle", "Emulation.Option.azahar.citra_swap_screen_mode.Value.Toggle"), new("Hold", "Emulation.Option.azahar.citra_swap_screen_mode.Value.Hold")]),
        new("citra_large_screen_proportion", "Emulation.Option.azahar.citra_large_screen_proportion", "Emulation.Option.azahar.citra_large_screen_proportion.Help", "layout", "4.00", "4.00", [new("1.00", "Emulation.Option.azahar.citra_large_screen_proportion.Value.1.00"), new("1.25", "1.25x"), new("1.50", "1.50x"), new("1.75", "1.75x"), new("2.00", "2.00x"), new("2.25", "2.25x"), new("2.50", "2.50x"), new("2.75", "2.75x"), new("3.00", "3.00x"), new("3.25", "3.25x"), new("3.50", "3.50x"), new("3.75", "3.75x"), new("4.00", "Emulation.Option.azahar.citra_large_screen_proportion.Value.4.00"), new("4.25", "4.25x"), new("4.50", "4.50x"), new("4.75", "4.75x"), new("5.00", "5.00x"), new("5.25", "5.25x"), new("5.50", "5.50x"), new("5.75", "5.75x"), new("6.00", "6.00x")]),
        new("citra_render_3d", "Emulation.Option.azahar.citra_render_3d", "Emulation.Option.azahar.citra_render_3d.Help", "layout", "off", "off", [new("off", "Emulation.Option.azahar.citra_render_3d.Value.off"), new("side-by-side", "Emulation.Option.azahar.citra_render_3d.Value.side-by-side"), new("side-by-side-full", "Emulation.Option.azahar.citra_render_3d.Value.side-by-side-full"), new("anaglyph", "Emulation.Option.azahar.citra_render_3d.Value.anaglyph"), new("interlaced", "Emulation.Option.azahar.citra_render_3d.Value.interlaced"), new("reverse-interlaced", "Emulation.Option.azahar.citra_render_3d.Value.reverse-interlaced"), new("cardboard", "Emulation.Option.azahar.citra_render_3d.Value.cardboard")]),
        new("citra_factor_3d", "Emulation.Option.azahar.citra_factor_3d", "Emulation.Option.azahar.citra_factor_3d.Help", "layout", "0", "0", [new("0", "0%"), new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "100%")]),
        new("citra_use_virtual_sd", "Emulation.Option.azahar.citra_use_virtual_sd", "Emulation.Option.azahar.citra_use_virtual_sd.Help", "storage", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_use_virtual_sd.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_use_virtual_sd.Value.disabled")]),
        new("citra_use_libretro_save_path", "Emulation.Option.azahar.citra_use_libretro_save_path", "Emulation.Option.azahar.citra_use_libretro_save_path.Help", "storage", "LibRetro Default", "LibRetro Default", [new("LibRetro Default", "Emulation.Option.azahar.citra_use_libretro_save_path.Value.LibRetro Default"), new("Azahar Default", "Emulation.Option.azahar.citra_use_libretro_save_path.Value.Azahar Default")]),
        new("citra_analog_function", "Emulation.Option.azahar.citra_analog_function", "Emulation.Option.azahar.citra_analog_function.Help", "input", "c_stick_and_touchscreen", "c_stick_and_touchscreen", [new("c_stick_and_touchscreen", "Emulation.Option.azahar.citra_analog_function.Value.c_stick_and_touchscreen"), new("touchscreen_pointer", "Emulation.Option.azahar.citra_analog_function.Value.touchscreen_pointer"), new("c_stick", "Emulation.Option.azahar.citra_analog_function.Value.c_stick")]),
        new("citra_analog_deadzone", "Emulation.Option.azahar.citra_analog_deadzone", "Emulation.Option.azahar.citra_analog_deadzone.Help", "input", "15", "15", [new("0", "0%"), new("5", "5%"), new("10", "10%"), new("15", "15%"), new("20", "20%"), new("25", "25%"), new("30", "30%"), new("35", "35%")]),
        new("citra_enable_mouse_touchscreen", "Emulation.Option.azahar.citra_enable_mouse_touchscreen", "Emulation.Option.azahar.citra_enable_mouse_touchscreen.Help", "input", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_enable_mouse_touchscreen.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_enable_mouse_touchscreen.Value.disabled")]),
        new("citra_enable_touch_touchscreen", "Emulation.Option.azahar.citra_enable_touch_touchscreen", "Emulation.Option.azahar.citra_enable_touch_touchscreen.Help", "input", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_enable_touch_touchscreen.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_enable_touch_touchscreen.Value.disabled")]),
        new("citra_enable_touch_pointer_timeout", "Emulation.Option.azahar.citra_enable_touch_pointer_timeout", "Emulation.Option.azahar.citra_enable_touch_pointer_timeout.Help", "input", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_enable_touch_pointer_timeout.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_enable_touch_pointer_timeout.Value.disabled")]),
        new("citra_enable_motion", "Emulation.Option.azahar.citra_enable_motion", "Emulation.Option.azahar.citra_enable_motion.Help", "input", "enabled", "enabled", [new("enabled", "Emulation.Option.azahar.citra_enable_motion.Value.enabled"), new("disabled", "Emulation.Option.azahar.citra_enable_motion.Value.disabled")]),
        new("citra_motion_sensitivity", "Emulation.Option.azahar.citra_motion_sensitivity", "Emulation.Option.azahar.citra_motion_sensitivity.Help", "input", "1.0", "1.0", [new("0.1", "10%"), new("0.25", "25%"), new("0.5", "50%"), new("0.75", "75%"), new("1.0", "100%"), new("1.25", "125%"), new("1.5", "150%"), new("2.0", "200%")])
    ];
}
