namespace GWGUI.Emulation.Amiga.Constants;

internal static class AmigaInputSettingsFunctionsConstants
{
    internal const string OptionTurboFire = "puae_turbo_fire";
    internal const string L2 = "L2";
    internal const string Enabled = "enabled";
    internal const string Disabled = "disabled";
    internal const string OptionTurboFireButton = "puae_turbo_fire_button";
    internal const string ResourceKeyHelp = "Emulation.Key.Help";
    internal const string Insert = "Insert";
    internal const string ResourceKeyLeftAmiga = "Emulation.Key.LeftAmiga";
    internal const string PageUp = "PageUp";
    internal const string ResourceKeyRightAmiga = "Emulation.Key.RightAmiga";
    internal const string PageDown = "PageDown";
    internal const string ResourceMouseButtonLeft = "Emulation.Mouse.Button.Left";
    internal const string MouseLeft = "Mouse:Left";
    internal const string ResourceMouseButtonRight = "Emulation.Mouse.Button.Right";
    internal const string MouseRight = "Mouse:Right";
    internal const string ResourceMouseButtonMiddle = "Emulation.Mouse.Button.Middle";
    internal const string MouseMiddle = "Mouse:Middle";
    internal const string Up = "Up";
    internal const string ResourceControllerActionUp = "Emulation.Controller.Action.Up";
    internal const string Down = "Down";
    internal const string ResourceControllerActionDown = "Emulation.Controller.Action.Down";
    internal const string Left = "Left";
    internal const string ResourceControllerActionLeft = "Emulation.Controller.Action.Left";
    internal const string Right = "Right";
    internal const string ResourceControllerActionRight = "Emulation.Controller.Action.Right";
    internal const string B = "B";
    internal const string ResourceAmigaControllerCd32Red = "Emulation.Amiga.Controller.Cd32.Red";
    internal const string A = "A";
    internal const string ResourceAmigaControllerCd32Blue = "Emulation.Amiga.Controller.Cd32.Blue";
    internal const string Y = "Y";
    internal const string ResourceAmigaControllerCd32Green = "Emulation.Amiga.Controller.Cd32.Green";
    internal const string X = "X";
    internal const string ResourceAmigaControllerCd32Yellow = "Emulation.Amiga.Controller.Cd32.Yellow";
    internal const string L = "L";
    internal const string ResourceAmigaControllerCd32Rewind = "Emulation.Amiga.Controller.Cd32.Rewind";
    internal const string R = "R";
    internal const string ResourceAmigaControllerCd32FastForward = "Emulation.Amiga.Controller.Cd32.FastForward";
    internal const string Start = "Start";
    internal const string ResourceAmigaControllerCd32PlayPause = "Emulation.Amiga.Controller.Cd32.PlayPause";
    internal const string ResourceControllerActionFire1 = "Emulation.Controller.Action.Fire1";
    internal const string ResourceControllerActionFire2 = "Emulation.Controller.Action.Fire2";
    internal const string ResourceControllerActionTurboFire = "Emulation.Controller.Action.TurboFire";
    internal const string ResourceAmigaControllerJoystick = "Emulation.Amiga.Controller.Joystick";
    internal const string ResourceControllerAnalogJoystick = "Emulation.Controller.AnalogJoystick";
    internal const string ResourceAmigaControllerCd32 = "Emulation.Amiga.Controller.Cd32";
    internal const string ResourceControllerAutomatic = "Emulation.Controller.Automatic";
    internal const string ResourceControllerNone = "Emulation.Controller.None";
}
