using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Nestopia.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("nestopia_favored_system", "Emulation.Option.nestopia.nestopia_favored_system", "Emulation.Option.nestopia.nestopia_favored_system.Help", "system", "ntsc", "ntsc", [new("ntsc", "Emulation.Option.nestopia.nestopia_favored_system.Value.ntsc"), new("pal", "Emulation.Option.nestopia.nestopia_favored_system.Value.pal"), new("famicom", "Emulation.Option.nestopia.nestopia_favored_system.Value.famicom"), new("dendy", "Emulation.Option.nestopia.nestopia_favored_system.Value.dendy")], Tab: EmulationMachineTab.General),
        new("nestopia_force_system", "Emulation.Option.nestopia.nestopia_force_system", "Emulation.Option.nestopia.nestopia_force_system.Help", "system", "auto", "auto", [new("auto", "Emulation.Option.nestopia.nestopia_force_system.Value.auto"), new("ntsc", "Emulation.Option.nestopia.nestopia_force_system.Value.ntsc"), new("pal", "Emulation.Option.nestopia.nestopia_force_system.Value.pal"), new("famicom", "Emulation.Option.nestopia.nestopia_force_system.Value.famicom"), new("dendy", "Emulation.Option.nestopia.nestopia_force_system.Value.dendy")], Tab: EmulationMachineTab.General),
        new("nestopia_fds_auto_insert", "Emulation.Option.nestopia.nestopia_fds_auto_insert", "Emulation.Option.nestopia.nestopia_fds_auto_insert.Help", "system", "enabled", "enabled", [new("disabled", "Emulation.Option.nestopia.nestopia_fds_auto_insert.Value.disabled"), new("enabled", "Emulation.Option.nestopia.nestopia_fds_auto_insert.Value.enabled")], Tab: EmulationMachineTab.Storage),
        new("nestopia_fds_savefile_format", "Emulation.Option.nestopia.nestopia_fds_savefile_format", "Emulation.Option.nestopia.nestopia_fds_savefile_format.Help", "system", "sav_ups", "sav_ups", [new("sav_ups", "Emulation.Option.nestopia.nestopia_fds_savefile_format.Value.sav_ups"), new("ups", "Emulation.Option.nestopia.nestopia_fds_savefile_format.Value.ups"), new("ips", "Emulation.Option.nestopia.nestopia_fds_savefile_format.Value.ips")], Tab: EmulationMachineTab.Storage),
        new("nestopia_blargg_ntsc_filter", "Emulation.Option.nestopia.nestopia_blargg_ntsc_filter", "Emulation.Option.nestopia.nestopia_blargg_ntsc_filter.Help", "video", "composite", "composite", [new("disabled", "Emulation.Option.nestopia.nestopia_blargg_ntsc_filter.Value.disabled"), new("composite", "Emulation.Option.nestopia.nestopia_blargg_ntsc_filter.Value.composite"), new("svideo", "Emulation.Option.nestopia.nestopia_blargg_ntsc_filter.Value.svideo"), new("rgb", "Emulation.Option.nestopia.nestopia_blargg_ntsc_filter.Value.rgb"), new("monochrome", "Emulation.Option.nestopia.nestopia_blargg_ntsc_filter.Value.monochrome")], Tab: EmulationMachineTab.Video),
        new("nestopia_palette", "Emulation.Option.nestopia.nestopia_palette", "Emulation.Option.nestopia.nestopia_palette.Help", "video", "royaltea", "royaltea", [new("royaltea", "Emulation.Option.nestopia.nestopia_palette.Value.royaltea"), new("cxa2025as", "Emulation.Option.nestopia.nestopia_palette.Value.cxa2025as"), new("cxa2025as_jp", "Emulation.Option.nestopia.nestopia_palette.Value.cxa2025as_jp"), new("consumer", "Emulation.Option.nestopia.nestopia_palette.Value.consumer"), new("canonical", "Emulation.Option.nestopia.nestopia_palette.Value.canonical"), new("alternative", "Emulation.Option.nestopia.nestopia_palette.Value.alternative"), new("rgb", "Emulation.Option.nestopia.nestopia_palette.Value.rgb"), new("pal", "Emulation.Option.nestopia.nestopia_palette.Value.pal"), new("digital-prime-fbx", "Emulation.Option.nestopia.nestopia_palette.Value.digital-prime-fbx"), new("magnum-fbx", "Emulation.Option.nestopia.nestopia_palette.Value.magnum-fbx"), new("smoothv2-fbx", "Emulation.Option.nestopia.nestopia_palette.Value.smoothv2-fbx"), new("composite-direct-fbx", "Emulation.Option.nestopia.nestopia_palette.Value.composite-direct-fbx"), new("pvm-style-d93-fbx", "Emulation.Option.nestopia.nestopia_palette.Value.pvm-style-d93-fbx"), new("ntsc-hardware-fbx", "Emulation.Option.nestopia.nestopia_palette.Value.ntsc-hardware-fbx"), new("nes-classic-fbx-fs", "Emulation.Option.nestopia.nestopia_palette.Value.nes-classic-fbx-fs"), new("restored-wii-vc", "Emulation.Option.nestopia.nestopia_palette.Value.restored-wii-vc"), new("wii-vc", "Emulation.Option.nestopia.nestopia_palette.Value.wii-vc"), new("raw", "Emulation.Option.nestopia.nestopia_palette.Value.raw"), new("custom", "Emulation.Option.nestopia.nestopia_palette.Value.custom")], Tab: EmulationMachineTab.Video),
        new("nestopia_overscan_v_top", "Emulation.Option.nestopia.nestopia_overscan_v_top", "Emulation.Option.nestopia.nestopia_overscan_v_top.Help", "video", "8", "8", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24")], Tab: EmulationMachineTab.Video),
        new("nestopia_overscan_v_bottom", "Emulation.Option.nestopia.nestopia_overscan_v_bottom", "Emulation.Option.nestopia.nestopia_overscan_v_bottom.Help", "video", "8", "8", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24")], Tab: EmulationMachineTab.Video),
        new("nestopia_overscan_h_left", "Emulation.Option.nestopia.nestopia_overscan_h_left", "Emulation.Option.nestopia.nestopia_overscan_h_left.Help", "video", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16")], Tab: EmulationMachineTab.Video),
        new("nestopia_overscan_h_right", "Emulation.Option.nestopia.nestopia_overscan_h_right", "Emulation.Option.nestopia.nestopia_overscan_h_right.Help", "video", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16")], Tab: EmulationMachineTab.Video),
        new("nestopia_aspect", "Emulation.Option.nestopia.nestopia_aspect", "Emulation.Option.nestopia.nestopia_aspect.Help", "video", "auto", "auto", [new("auto", "Emulation.Option.nestopia.nestopia_aspect.Value.auto"), new("ntsc", "Emulation.Option.nestopia.nestopia_aspect.Value.ntsc"), new("pal", "Emulation.Option.nestopia.nestopia_aspect.Value.pal"), new("4:3", "Emulation.Option.nestopia.nestopia_aspect.Value.4:3"), new("5:4", "Emulation.Option.nestopia.nestopia_aspect.Value.5:4"), new("uncorrected", "Emulation.Option.nestopia.nestopia_aspect.Value.uncorrected")], Tab: EmulationMachineTab.Video),
        new("nestopia_audio_filter", "Emulation.Option.nestopia.nestopia_audio_filter", "Emulation.Option.nestopia.nestopia_audio_filter.Help", "audio", "disabled", "disabled", [new("disabled", "Emulation.Option.nestopia.nestopia_audio_filter.Value.disabled"), new("enabled", "Emulation.Option.nestopia.nestopia_audio_filter.Value.enabled")], Tab: EmulationMachineTab.Audio),
        new("nestopia_show_advanced_av_settings", "Emulation.Option.nestopia.nestopia_show_advanced_av_settings", "Emulation.Option.nestopia.nestopia_show_advanced_av_settings.Help", "audio", "disabled", "disabled", [new("disabled", "Emulation.Option.nestopia.nestopia_show_advanced_av_settings.Value.disabled"), new("enabled", "Emulation.Option.nestopia.nestopia_show_advanced_av_settings.Value.enabled")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_sq1", "Emulation.Option.nestopia.nestopia_audio_vol_sq1", "Emulation.Option.nestopia.nestopia_audio_vol_sq1.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_sq2", "Emulation.Option.nestopia.nestopia_audio_vol_sq2", "Emulation.Option.nestopia.nestopia_audio_vol_sq2.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_tri", "Emulation.Option.nestopia.nestopia_audio_vol_tri", "Emulation.Option.nestopia.nestopia_audio_vol_tri.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_noise", "Emulation.Option.nestopia.nestopia_audio_vol_noise", "Emulation.Option.nestopia.nestopia_audio_vol_noise.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_dpcm", "Emulation.Option.nestopia.nestopia_audio_vol_dpcm", "Emulation.Option.nestopia.nestopia_audio_vol_dpcm.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_fds", "Emulation.Option.nestopia.nestopia_audio_vol_fds", "Emulation.Option.nestopia.nestopia_audio_vol_fds.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Storage),
        new("nestopia_audio_vol_mmc5", "Emulation.Option.nestopia.nestopia_audio_vol_mmc5", "Emulation.Option.nestopia.nestopia_audio_vol_mmc5.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_vrc6", "Emulation.Option.nestopia.nestopia_audio_vol_vrc6", "Emulation.Option.nestopia.nestopia_audio_vol_vrc6.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_vrc7", "Emulation.Option.nestopia.nestopia_audio_vol_vrc7", "Emulation.Option.nestopia.nestopia_audio_vol_vrc7.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_n163", "Emulation.Option.nestopia.nestopia_audio_vol_n163", "Emulation.Option.nestopia.nestopia_audio_vol_n163.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_audio_vol_s5b", "Emulation.Option.nestopia.nestopia_audio_vol_s5b", "Emulation.Option.nestopia.nestopia_audio_vol_s5b.Help", "audio", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95"), new("100", "100")], Tab: EmulationMachineTab.Audio),
        new("nestopia_select_adapter", "Emulation.Option.nestopia.nestopia_select_adapter", "Emulation.Option.nestopia.nestopia_select_adapter.Help", "input", "auto", "auto", [new("auto", "Emulation.Option.nestopia.nestopia_select_adapter.Value.auto"), new("ntsc", "Emulation.Option.nestopia.nestopia_select_adapter.Value.ntsc"), new("famicom", "Emulation.Option.nestopia.nestopia_select_adapter.Value.famicom")], Tab: EmulationMachineTab.Controllers),
        new("nestopia_button_shift", "Emulation.Option.nestopia.nestopia_button_shift", "Emulation.Option.nestopia.nestopia_button_shift.Help", "input", "disabled", "disabled", [new("disabled", "Emulation.Option.nestopia.nestopia_button_shift.Value.disabled"), new("enabled", "Emulation.Option.nestopia.nestopia_button_shift.Value.enabled")], Tab: EmulationMachineTab.Controllers),
        new("nestopia_arkanoid_device", "Emulation.Option.nestopia.nestopia_arkanoid_device", "Emulation.Option.nestopia.nestopia_arkanoid_device.Help", "input", "mouse", "mouse", [new("mouse", "Emulation.Option.nestopia.nestopia_arkanoid_device.Value.mouse"), new("pointer", "Emulation.Option.nestopia.nestopia_arkanoid_device.Value.pointer")], Tab: EmulationMachineTab.Controllers),
        new("nestopia_arkanoid_paddle_range", "Emulation.Option.nestopia.nestopia_arkanoid_paddle_range", "Emulation.Option.nestopia.nestopia_arkanoid_paddle_range.Help", "input", "combined", "combined", [new("combined", "Emulation.Option.nestopia.nestopia_arkanoid_paddle_range.Value.combined"), new("arkanoidI", "Emulation.Option.nestopia.nestopia_arkanoid_paddle_range.Value.arkanoidI"), new("arkanoidII", "Emulation.Option.nestopia.nestopia_arkanoid_paddle_range.Value.arkanoidII")], Tab: EmulationMachineTab.Controllers),
        new("nestopia_zapper_device", "Emulation.Option.nestopia.nestopia_zapper_device", "Emulation.Option.nestopia.nestopia_zapper_device.Help", "input", "lightgun", "lightgun", [new("lightgun", "Emulation.Option.nestopia.nestopia_zapper_device.Value.lightgun"), new("mouse", "Emulation.Option.nestopia.nestopia_zapper_device.Value.mouse"), new("pointer", "Emulation.Option.nestopia.nestopia_zapper_device.Value.pointer")], Tab: EmulationMachineTab.Controllers),
        new("nestopia_show_crosshair", "Emulation.Option.nestopia.nestopia_show_crosshair", "Emulation.Option.nestopia.nestopia_show_crosshair.Help", "input", "enabled", "enabled", [new("disabled", "Emulation.Option.nestopia.nestopia_show_crosshair.Value.disabled"), new("enabled", "Emulation.Option.nestopia.nestopia_show_crosshair.Value.enabled")], Tab: EmulationMachineTab.Controllers),
        new("nestopia_turbo_pulse", "Emulation.Option.nestopia.nestopia_turbo_pulse", "Emulation.Option.nestopia.nestopia_turbo_pulse.Help", "input", "2", "2", [new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9")], Tab: EmulationMachineTab.Controllers),
        new("nestopia_nospritelimit", "Emulation.Option.nestopia.nestopia_nospritelimit", "Emulation.Option.nestopia.nestopia_nospritelimit.Help", "hacks", "disabled", "disabled", [new("disabled", "Emulation.Option.nestopia.nestopia_nospritelimit.Value.disabled"), new("enabled", "Emulation.Option.nestopia.nestopia_nospritelimit.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("nestopia_dmc_pop_reducer", "Emulation.Option.nestopia.nestopia_dmc_pop_reducer", "Emulation.Option.nestopia.nestopia_dmc_pop_reducer.Help", "hacks", "disabled", "disabled", [new("disabled", "Emulation.Option.nestopia.nestopia_dmc_pop_reducer.Value.disabled"), new("enabled", "Emulation.Option.nestopia.nestopia_dmc_pop_reducer.Value.enabled")], Tab: EmulationMachineTab.Audio),
        new("nestopia_genie_distortion", "Emulation.Option.nestopia.nestopia_genie_distortion", "Emulation.Option.nestopia.nestopia_genie_distortion.Help", "hacks", "disabled", "disabled", [new("disabled", "Emulation.Option.nestopia.nestopia_genie_distortion.Value.disabled"), new("enabled", "Emulation.Option.nestopia.nestopia_genie_distortion.Value.enabled")], Tab: EmulationMachineTab.General),
        new("nestopia_ram_power_state", "Emulation.Option.nestopia.nestopia_ram_power_state", "Emulation.Option.nestopia.nestopia_ram_power_state.Help", "hacks", "0x00", "0x00", [new("0x00", "0x00"), new("0xFF", "Emulation.Option.nestopia.nestopia_ram_power_state.Value.0xFF"), new("random", "Emulation.Option.nestopia.nestopia_ram_power_state.Value.random")], Tab: EmulationMachineTab.Ram)
    ];
}
