namespace GWGUI.Emulation.Sega.Emulators.Ymir.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("ymir_region", "Emulation.Option.ymir.ymir_region", "Emulation.Option.ymir.ymir_region.Description", null, "auto", "auto", [new("auto", "Emulation.Option.ymir.ymir_region.Value.auto"), new("japan", "Emulation.Option.ymir.ymir_region.Value.japan"), new("north_america", "Emulation.Option.ymir.ymir_region.Value.north_america"), new("europe", "Emulation.Option.ymir.ymir_region.Value.europe")], Tab: EmulationMachineTab.General, RequiresRestart: false),
        new("ymir_sh2_cache", "Emulation.Option.ymir.ymir_sh2_cache", "Emulation.Option.ymir.ymir_sh2_cache.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.ymir.ymir_sh2_cache.Value.disabled"), new("enabled", "Emulation.Option.ymir.ymir_sh2_cache.Value.enabled")], Tab: EmulationMachineTab.Cpu, RequiresRestart: false),
        new("ymir_sh2_clock", "Emulation.Option.ymir.ymir_sh2_clock", "Emulation.Option.ymir.ymir_sh2_clock.Description", null, "100", "100", [new("25", "Emulation.Option.ymir.ymir_sh2_clock.Value.25"), new("50", "Emulation.Option.ymir.ymir_sh2_clock.Value.50"), new("75", "Emulation.Option.ymir.ymir_sh2_clock.Value.75"), new("100", "Emulation.Option.ymir.ymir_sh2_clock.Value.100"), new("125", "Emulation.Option.ymir.ymir_sh2_clock.Value.125"), new("150", "Emulation.Option.ymir.ymir_sh2_clock.Value.150"), new("200", "Emulation.Option.ymir.ymir_sh2_clock.Value.200"), new("300", "Emulation.Option.ymir.ymir_sh2_clock.Value.300"), new("400", "Emulation.Option.ymir.ymir_sh2_clock.Value.400"), new("500", "Emulation.Option.ymir.ymir_sh2_clock.Value.500")], Tab: EmulationMachineTab.Cpu, RequiresRestart: false),
        new("ymir_rtc_mode", "Emulation.Option.ymir.ymir_rtc_mode", "Emulation.Option.ymir.ymir_rtc_mode.Description", null, "virtual", "virtual", [new("virtual", "Emulation.Option.ymir.ymir_rtc_mode.Value.virtual"), new("host", "Emulation.Option.ymir.ymir_rtc_mode.Value.host")], Tab: EmulationMachineTab.General, RequiresRestart: false),
        new("ymir_cartridge", "Emulation.Option.ymir.ymir_cartridge", "Emulation.Option.ymir.ymir_cartridge.Description", null, "auto", "auto", [new("auto", "Emulation.Option.ymir.ymir_cartridge.Value.auto"), new("none", "Emulation.Option.ymir.ymir_cartridge.Value.none"), new("dram_8mbit", "Emulation.Option.ymir.ymir_cartridge.Value.dram_8mbit"), new("dram_32mbit", "Emulation.Option.ymir.ymir_cartridge.Value.dram_32mbit"), new("rom_kof95", "Emulation.Option.ymir.ymir_cartridge.Value.rom_kof95"), new("rom_ultraman", "Emulation.Option.ymir.ymir_cartridge.Value.rom_ultraman")], Tab: EmulationMachineTab.Ram, RequiresRestart: false),
        new("ymir_threaded_vdp1", "Emulation.Option.ymir.ymir_threaded_vdp1", "Emulation.Option.ymir.ymir_threaded_vdp1.Description", null, "enabled", "enabled", [new("enabled", "Emulation.Option.ymir.ymir_threaded_vdp1.Value.enabled"), new("disabled", "Emulation.Option.ymir.ymir_threaded_vdp1.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("ymir_threaded_vdp2", "Emulation.Option.ymir.ymir_threaded_vdp2", "Emulation.Option.ymir.ymir_threaded_vdp2.Description", null, "enabled", "enabled", [new("enabled", "Emulation.Option.ymir.ymir_threaded_vdp2.Value.enabled"), new("disabled", "Emulation.Option.ymir.ymir_threaded_vdp2.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("ymir_deinterlace", "Emulation.Option.ymir.ymir_deinterlace", "Emulation.Option.ymir.ymir_deinterlace.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.ymir.ymir_deinterlace.Value.disabled"), new("enabled", "Emulation.Option.ymir.ymir_deinterlace.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("ymir_threaded_deinterlacer", "Emulation.Option.ymir.ymir_threaded_deinterlacer", "Emulation.Option.ymir.ymir_threaded_deinterlacer.Description", null, "enabled", "enabled", [new("enabled", "Emulation.Option.ymir.ymir_threaded_deinterlacer.Value.enabled"), new("disabled", "Emulation.Option.ymir.ymir_threaded_deinterlacer.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("ymir_transparent_meshes", "Emulation.Option.ymir.ymir_transparent_meshes", "Emulation.Option.ymir.ymir_transparent_meshes.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.ymir.ymir_transparent_meshes.Value.disabled"), new("enabled", "Emulation.Option.ymir.ymir_transparent_meshes.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("ymir_audio_interpolation", "Emulation.Option.ymir.ymir_audio_interpolation", "Emulation.Option.ymir.ymir_audio_interpolation.Description", null, "linear", "linear", [new("linear", "Emulation.Option.ymir.ymir_audio_interpolation.Value.linear"), new("nearest_neighbor", "Emulation.Option.ymir.ymir_audio_interpolation.Value.nearest_neighbor")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("ymir_threaded_scsp", "Emulation.Option.ymir.ymir_threaded_scsp", "Emulation.Option.ymir.ymir_threaded_scsp.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.ymir.ymir_threaded_scsp.Value.disabled"), new("enabled", "Emulation.Option.ymir.ymir_threaded_scsp.Value.enabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("ymir_audio_step_granularity", "Emulation.Option.ymir.ymir_audio_step_granularity", "Emulation.Option.ymir.ymir_audio_step_granularity.Description", null, "0", "0", [new("0", "Emulation.Option.ymir.ymir_audio_step_granularity.Value.0"), new("1", "Emulation.Option.ymir.ymir_audio_step_granularity.Value.1"), new("2", "Emulation.Option.ymir.ymir_audio_step_granularity.Value.2"), new("3", "Emulation.Option.ymir.ymir_audio_step_granularity.Value.3"), new("4", "Emulation.Option.ymir.ymir_audio_step_granularity.Value.4"), new("5", "Emulation.Option.ymir.ymir_audio_step_granularity.Value.5")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("ymir_cd_speed", "Emulation.Option.ymir.ymir_cd_speed", "Emulation.Option.ymir.ymir_cd_speed.Description", null, "2", "2", [new("2", "Emulation.Option.ymir.ymir_cd_speed.Value.2"), new("4", "Emulation.Option.ymir.ymir_cd_speed.Value.4"), new("8", "Emulation.Option.ymir.ymir_cd_speed.Value.8")], Tab: EmulationMachineTab.Storage, RequiresRestart: false),
        new("ymir_cdblock_lle", "Emulation.Option.ymir.ymir_cdblock_lle", "Emulation.Option.ymir.ymir_cdblock_lle.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.ymir.ymir_cdblock_lle.Value.disabled"), new("enabled", "Emulation.Option.ymir.ymir_cdblock_lle.Value.enabled")], Tab: EmulationMachineTab.Storage, RequiresRestart: false),
    ];
}
