namespace GWGUI.Emulation.Sega.Emulators.BlueMSX.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("bluemsx_msxtype", "Emulation.Option.bluemsx.bluemsx_msxtype", "Emulation.Option.bluemsx.bluemsx_msxtype.Description", null, "SEGA - SG-1000", "SEGA - SG-1000", [new("SEGA - SG-1000", "Emulation.Option.bluemsx.bluemsx_msxtype.Value.SEGA - SG-1000"), new("SEGA - SC-3000", "Emulation.Option.bluemsx.bluemsx_msxtype.Value.SEGA - SC-3000"), new("SEGA - SF-7000", "Emulation.Option.bluemsx.bluemsx_msxtype.Value.SEGA - SF-7000")], Tab: EmulationMachineTab.General, RequiresRestart: true),
        new("bluemsx_auto_rewind_cas", "Emulation.Option.bluemsx.bluemsx_auto_rewind_cas", null, null, "ON", "ON", [new("ON", "Emulation.Option.bluemsx.bluemsx_auto_rewind_cas.Value.ON"), new("OFF", "Emulation.Option.bluemsx.bluemsx_auto_rewind_cas.Value.OFF")], Tab: EmulationMachineTab.Storage, RequiresRestart: false, MachineIds: OptionMachineConstants.Computers),
        new("bluemsx_overscan", "Emulation.Option.bluemsx.bluemsx_overscan", "Emulation.Option.bluemsx.bluemsx_overscan.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.bluemsx.bluemsx_overscan.Value.disabled"), new("enabled", "Emulation.Option.bluemsx.bluemsx_overscan.Value.enabled"), new("MSX2", "Emulation.Option.bluemsx.bluemsx_overscan.Value.MSX2")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("bluemsx_vdp_synctype", "Emulation.Option.bluemsx.bluemsx_vdp_synctype", "Emulation.Option.bluemsx.bluemsx_vdp_synctype.Description", null, "Auto", "Auto", [new("Auto", "Emulation.Option.bluemsx.bluemsx_vdp_synctype.Value.Auto"), new("50Hz", "Emulation.Option.bluemsx.bluemsx_vdp_synctype.Value.50Hz"), new("60Hz", "Emulation.Option.bluemsx.bluemsx_vdp_synctype.Value.60Hz")], Tab: EmulationMachineTab.Video, RequiresRestart: true),
        new("bluemsx_nospritelimits", "Emulation.Option.bluemsx.bluemsx_nospritelimits", "Emulation.Option.bluemsx.bluemsx_nospritelimits.Description", null, "OFF", "OFF", [new("OFF", "Emulation.Option.bluemsx.bluemsx_nospritelimits.Value.OFF"), new("ON", "Emulation.Option.bluemsx.bluemsx_nospritelimits.Value.ON")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("bluemsx_ym2413_enable", "Emulation.Option.bluemsx.bluemsx_ym2413_enable", "Emulation.Option.bluemsx.bluemsx_ym2413_enable.Description", null, "enabled", "enabled", [new("enabled", "Emulation.Option.bluemsx.bluemsx_ym2413_enable.Value.enabled"), new("disabled", "Emulation.Option.bluemsx.bluemsx_ym2413_enable.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: true, IsVisible: false),
        new("hard_reset_f12", "Emulation.Option.bluemsx.hard_reset_f12", "Emulation.Option.bluemsx.hard_reset_f12.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.bluemsx.hard_reset_f12.Value.enabled"), new("disabled", "Emulation.Option.bluemsx.hard_reset_f12.Value.disabled")], Tab: EmulationMachineTab.Keyboard, RequiresRestart: true),
        new("bluemsx_cartmapper", "Emulation.Option.bluemsx.bluemsx_cartmapper", "Emulation.Option.bluemsx.bluemsx_cartmapper.Description", null, "Auto", "Auto", [new("Auto", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.Auto"), new("SegaBasic", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.SegaBasic", MachineIds: OptionMachineConstants.Computers), new("SG1000", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.SG1000", MachineIds: OptionMachineConstants.CartridgeSystems), new("SG1000Castle", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.SG1000Castle", MachineIds: OptionMachineConstants.CartridgeSystems), new("SG1000RamA", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.SG1000RamA", MachineIds: OptionMachineConstants.CartridgeSystems), new("SG1000RamB", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.SG1000RamB", MachineIds: OptionMachineConstants.CartridgeSystems), new("SC3000", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.SC3000", MachineIds: OptionMachineConstants.Computers), new("SC3000MultiCart", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.SC3000MultiCart", MachineIds: OptionMachineConstants.Computers), new("SC3000MegaCart", "Emulation.Option.bluemsx.bluemsx_cartmapper.Value.SC3000MegaCart", MachineIds: OptionMachineConstants.Computers)], Tab: EmulationMachineTab.Rom, RequiresRestart: true),
    ];
}
