<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>gwgui.updater</AssemblyName>
    <RootNamespace>GWGUI.Updater</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GWGUI.Updates\GWGUI.Updates.csproj" />
  </ItemGroup>
</Project>
