namespace GWGUI.Emulation.Sega.Emulators.PicoDrive.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("picodrive_region", "Emulation.Option.picodrive.picodrive_region", "Emulation.Option.picodrive.picodrive_region.Description", null, "Auto", "Auto", [new("Auto", "Emulation.Option.picodrive.picodrive_region.Value.Auto"), new("Japan NTSC", "Emulation.Option.picodrive.picodrive_region.Value.Japan NTSC"), new("Japan PAL", "Emulation.Option.picodrive.picodrive_region.Value.Japan PAL"), new("US", "Emulation.Option.picodrive.picodrive_region.Value.US"), new("Europe", "Emulation.Option.picodrive.picodrive_region.Value.Europe")], Tab: EmulationMachineTab.General, RequiresRestart: false),
        new("picodrive_smstype", "Emulation.Option.picodrive.picodrive_smstype", "Emulation.Option.picodrive.picodrive_smstype.Description", null, "Auto", "Auto", [new("Auto", "Emulation.Option.picodrive.picodrive_smstype.Value.Auto"), new("Game Gear", "Emulation.Option.picodrive.picodrive_smstype.Value.Game Gear"), new("Master System", "Emulation.Option.picodrive.picodrive_smstype.Value.Master System"), new("SG-1000", "Emulation.Option.picodrive.picodrive_smstype.Value.SG-1000"), new("SC-3000", "Emulation.Option.picodrive.picodrive_smstype.Value.SC-3000")], Tab: EmulationMachineTab.General, RequiresRestart: false, MachineIds: OptionMachineConstants.MasterSystem),
        new("picodrive_smsmapper", "Emulation.Option.picodrive.picodrive_smsmapper", "Emulation.Option.picodrive.picodrive_smsmapper.Description", null, "Auto", "Auto", [new("Auto", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Auto"), new("Sega", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Sega"), new("Codemasters", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Codemasters"), new("Korea", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Korea"), new("Korea MSX", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Korea MSX"), new("Korea X-in-1", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Korea X-in-1"), new("Korea 4-Pak", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Korea 4-Pak"), new("Korea Janggun", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Korea Janggun"), new("Korea Nemesis", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Korea Nemesis"), new("Taiwan 8K RAM", "Emulation.Option.picodrive.picodrive_smsmapper.Value.Taiwan 8K RAM")], Tab: EmulationMachineTab.Rom, RequiresRestart: false, MachineIds: OptionMachineConstants.MasterSystem),
        new("picodrive_smstms", "Emulation.Option.picodrive.picodrive_smstms", "Emulation.Option.picodrive.picodrive_smstms.Description", null, "SMS", "SMS", [new("SMS", "Emulation.Option.picodrive.picodrive_smstms.Value.SMS"), new("SG-1000", "Emulation.Option.picodrive.picodrive_smstms.Value.SG-1000")], Tab: EmulationMachineTab.General, RequiresRestart: false, MachineIds: OptionMachineConstants.MasterSystem),
        new("picodrive_ramcart", "Emulation.Option.picodrive.picodrive_ramcart", "Emulation.Option.picodrive.picodrive_ramcart.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.picodrive.picodrive_ramcart.Value.disabled"), new("enabled", "Emulation.Option.picodrive.picodrive_ramcart.Value.enabled")], Tab: EmulationMachineTab.Ram, RequiresRestart: false, MachineIds: OptionMachineConstants.MegaCd),
        new("picodrive_aspect", "Emulation.Option.picodrive.picodrive_aspect", "Emulation.Option.picodrive.picodrive_aspect.Description", null, "PAR", "PAR", [new("PAR", "Emulation.Option.picodrive.picodrive_aspect.Value.PAR"), new("4/3", "Emulation.Option.picodrive.picodrive_aspect.Value.4/3"), new("CRT", "Emulation.Option.picodrive.picodrive_aspect.Value.CRT")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("picodrive_ggghost", "Emulation.Option.picodrive.picodrive_ggghost", "Emulation.Option.picodrive.picodrive_ggghost.Description", null, "off", "off", [new("off", "Emulation.Option.picodrive.picodrive_ggghost.Value.off"), new("weak", "Emulation.Option.picodrive.picodrive_ggghost.Value.weak"), new("normal", "Emulation.Option.picodrive.picodrive_ggghost.Value.normal")], Tab: EmulationMachineTab.Video, RequiresRestart: false, MachineIds: OptionMachineConstants.GameGear),
        new("picodrive_renderer", "Emulation.Option.picodrive.picodrive_renderer", "Emulation.Option.picodrive.picodrive_renderer.Description", null, "accurate", "accurate", [new("accurate", "Emulation.Option.picodrive.picodrive_renderer.Value.accurate"), new("good", "Emulation.Option.picodrive.picodrive_renderer.Value.good"), new("fast", "Emulation.Option.picodrive.picodrive_renderer.Value.fast")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("picodrive_sound_rate", "Emulation.Option.picodrive.picodrive_sound_rate", "Emulation.Option.picodrive.picodrive_sound_rate.Description", null, "44100", "44100", [new("16000", "Emulation.Option.picodrive.picodrive_sound_rate.Value.16000"), new("22050", "Emulation.Option.picodrive.picodrive_sound_rate.Value.22050"), new("32000", "Emulation.Option.picodrive.picodrive_sound_rate.Value.32000"), new("44100", "Emulation.Option.picodrive.picodrive_sound_rate.Value.44100"), new("native", "Emulation.Option.picodrive.picodrive_sound_rate.Value.native")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("picodrive_fm_filter", "Emulation.Option.picodrive.picodrive_fm_filter", "Emulation.Option.picodrive.picodrive_fm_filter.Description", null, "off", "off", [new("off", "Emulation.Option.picodrive.picodrive_fm_filter.Value.off"), new("on", "Emulation.Option.picodrive.picodrive_fm_filter.Value.on")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("picodrive_smsfm", "Emulation.Option.picodrive.picodrive_smsfm", "Emulation.Option.picodrive.picodrive_smsfm.Description", null, "off", "off", [new("off", "Emulation.Option.picodrive.picodrive_smsfm.Value.off"), new("on", "Emulation.Option.picodrive.picodrive_smsfm.Value.on")], Tab: EmulationMachineTab.Audio, RequiresRestart: false, MachineIds: OptionMachineConstants.MasterSystem),
        new("picodrive_fmchip", "Emulation.Option.picodrive.picodrive_fmchip", "Emulation.Option.picodrive.picodrive_fmchip.Description", null, "off", "off", [new("ym2612", "Emulation.Option.picodrive.picodrive_fmchip.Value.ym2612"), new("ym3438", "Emulation.Option.picodrive.picodrive_fmchip.Value.ym3438")], Tab: EmulationMachineTab.Audio, RequiresRestart: false, MachineIds: OptionMachineConstants.MegaDriveFamily),
        new("picodrive_audio_filter", "Emulation.Option.picodrive.picodrive_audio_filter", "Emulation.Option.picodrive.picodrive_audio_filter.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.picodrive.picodrive_audio_filter.Value.disabled"), new("low-pass", "Emulation.Option.picodrive.picodrive_audio_filter.Value.low-pass")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("picodrive_lowpass_range", "Emulation.Option.picodrive.picodrive_lowpass_range", "Emulation.Option.picodrive.picodrive_lowpass_range.Description", null, "60", "60", [new("5", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.5"), new("10", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.10"), new("15", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.15"), new("20", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.20"), new("25", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.25"), new("30", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.30"), new("35", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.35"), new("40", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.40"), new("45", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.45"), new("50", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.50"), new("55", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.55"), new("60", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.60"), new("65", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.65"), new("70", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.70"), new("75", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.75"), new("80", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.80"), new("85", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.85"), new("90", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.90"), new("95", "Emulation.Option.picodrive.picodrive_lowpass_range.Value.95")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("picodrive_input1", "Emulation.Option.picodrive.picodrive_input1", "Emulation.Option.picodrive.picodrive_input1.Description", null, "3 button pad", "3 button pad", [new("3 button pad", "Emulation.Option.picodrive.picodrive_input1.Value.3 button pad"), new("6 button pad", "Emulation.Option.picodrive.picodrive_input1.Value.6 button pad"), new("team player", "Emulation.Option.picodrive.picodrive_input1.Value.team player"), new("4way play", "Emulation.Option.picodrive.picodrive_input1.Value.4way play"), new("None", "Emulation.Option.picodrive.picodrive_input1.Value.None")], Tab: EmulationMachineTab.Controllers, RequiresRestart: false),
        new("picodrive_input2", "Emulation.Option.picodrive.picodrive_input2", "Emulation.Option.picodrive.picodrive_input2.Description", null, "3 button pad", "3 button pad", [new("3 button pad", "Emulation.Option.picodrive.picodrive_input2.Value.3 button pad"), new("6 button pad", "Emulation.Option.picodrive.picodrive_input2.Value.6 button pad"), new("None", "Emulation.Option.picodrive.picodrive_input2.Value.None")], Tab: EmulationMachineTab.Controllers, RequiresRestart: false),
        new("picodrive_drc", "Emulation.Option.picodrive.picodrive_drc", "Emulation.Option.picodrive.picodrive_drc.Description", null, "enabled", "enabled", [new("enabled", "Emulation.Option.picodrive.picodrive_drc.Value.enabled"), new("disabled", "Emulation.Option.picodrive.picodrive_drc.Value.disabled")], Tab: EmulationMachineTab.Cpu, RequiresRestart: false, MachineIds: OptionMachineConstants.MegaDriveFamily),
        new("picodrive_frameskip", "Emulation.Option.picodrive.picodrive_frameskip", "Emulation.Option.picodrive.picodrive_frameskip.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.picodrive.picodrive_frameskip.Value.disabled"), new("auto", "Emulation.Option.picodrive.picodrive_frameskip.Value.auto"), new("manual", "Emulation.Option.picodrive.picodrive_frameskip.Value.manual")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("picodrive_frameskip_threshold", "Emulation.Option.picodrive.picodrive_frameskip_threshold", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Description", null, "33", "33", [new("15", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.15"), new("18", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.18"), new("21", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.21"), new("24", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.24"), new("27", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.27"), new("30", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.30"), new("33", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.33"), new("36", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.36"), new("39", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.39"), new("42", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.42"), new("45", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.45"), new("48", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.48"), new("51", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.51"), new("54", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.54"), new("57", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.57"), new("60", "Emulation.Option.picodrive.picodrive_frameskip_threshold.Value.60")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("picodrive_sprlim", "Emulation.Option.picodrive.picodrive_sprlim", "Emulation.Option.picodrive.picodrive_sprlim.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.picodrive.picodrive_sprlim.Value.disabled"), new("enabled", "Emulation.Option.picodrive.picodrive_sprlim.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("picodrive_overclk68k", "Emulation.Option.picodrive.picodrive_overclk68k", "Emulation.Option.picodrive.picodrive_overclk68k.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.picodrive.picodrive_overclk68k.Value.disabled"), new("+25%", "Emulation.Option.picodrive.picodrive_overclk68k.Value.+25%"), new("+50%", "Emulation.Option.picodrive.picodrive_overclk68k.Value.+50%"), new("+75%", "Emulation.Option.picodrive.picodrive_overclk68k.Value.+75%"), new("+100%", "Emulation.Option.picodrive.picodrive_overclk68k.Value.+100%"), new("+200%", "Emulation.Option.picodrive.picodrive_overclk68k.Value.+200%"), new("+400%", "Emulation.Option.picodrive.picodrive_overclk68k.Value.+400%")], Tab: EmulationMachineTab.Cpu, RequiresRestart: false, MachineIds: OptionMachineConstants.MegaDriveFamily),
    ];
}
