using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Quicknes.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("quicknes_aspect_ratio_par", "Emulation.Option.quicknes.quicknes_aspect_ratio_par", "Emulation.Option.quicknes.quicknes_aspect_ratio_par.Help", "", "PAR", "PAR", [new("PAR", "Emulation.Option.quicknes.quicknes_aspect_ratio_par.Value.PAR"), new("4:3", "4:3")]),
        new("quicknes_use_overscan_h", "Emulation.Option.quicknes.quicknes_use_overscan_h", "Emulation.Option.quicknes.quicknes_use_overscan_h.Help", "", "enabled", "enabled", [new("enabled", "Emulation.Option.quicknes.quicknes_use_overscan_h.Value.enabled"), new("disabled", "Emulation.Option.quicknes.quicknes_use_overscan_h.Value.disabled")]),
        new("quicknes_use_overscan_v", "Emulation.Option.quicknes.quicknes_use_overscan_v", "Emulation.Option.quicknes.quicknes_use_overscan_v.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.quicknes.quicknes_use_overscan_v.Value.disabled"), new("enabled", "Emulation.Option.quicknes.quicknes_use_overscan_v.Value.enabled")]),
        new("quicknes_palette", "Emulation.Option.quicknes.quicknes_palette", "Emulation.Option.quicknes.quicknes_palette.Help", "", "default", "default", [new("default", "Emulation.Option.quicknes.quicknes_palette.Value.default"), new("asqrealc", "Emulation.Option.quicknes.quicknes_palette.Value.asqrealc"), new("nintendo-vc", "Emulation.Option.quicknes.quicknes_palette.Value.nintendo-vc"), new("rgb", "Emulation.Option.quicknes.quicknes_palette.Value.rgb"), new("yuv-v3", "Emulation.Option.quicknes.quicknes_palette.Value.yuv-v3"), new("unsaturated-final", "Emulation.Option.quicknes.quicknes_palette.Value.unsaturated-final"), new("sony-cxa2025as-us", "Emulation.Option.quicknes.quicknes_palette.Value.sony-cxa2025as-us"), new("pal", "Emulation.Option.quicknes.quicknes_palette.Value.pal"), new("bmf-final2", "Emulation.Option.quicknes.quicknes_palette.Value.bmf-final2"), new("bmf-final3", "Emulation.Option.quicknes.quicknes_palette.Value.bmf-final3"), new("smooth-fbx", "Emulation.Option.quicknes.quicknes_palette.Value.smooth-fbx"), new("composite-direct-fbx", "Emulation.Option.quicknes.quicknes_palette.Value.composite-direct-fbx"), new("pvm-style-d93-fbx", "Emulation.Option.quicknes.quicknes_palette.Value.pvm-style-d93-fbx"), new("ntsc-hardware-fbx", "Emulation.Option.quicknes.quicknes_palette.Value.ntsc-hardware-fbx"), new("nes-classic-fbx-fs", "Emulation.Option.quicknes.quicknes_palette.Value.nes-classic-fbx-fs"), new("nescap", "Emulation.Option.quicknes.quicknes_palette.Value.nescap"), new("wavebeam", "Emulation.Option.quicknes.quicknes_palette.Value.wavebeam")]),
        new("quicknes_no_sprite_limit", "Emulation.Option.quicknes.quicknes_no_sprite_limit", "Emulation.Option.quicknes.quicknes_no_sprite_limit.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.quicknes.quicknes_no_sprite_limit.Value.disabled"), new("enabled", "Emulation.Option.quicknes.quicknes_no_sprite_limit.Value.enabled")]),
        new("quicknes_audio_samplerate", "Emulation.Option.quicknes.quicknes_audio_samplerate", "Emulation.Option.quicknes.quicknes_audio_samplerate.Help", "", "auto", "auto", [new("auto", "Emulation.Option.quicknes.quicknes_audio_samplerate.Value.auto"), new("32000", "Emulation.Option.quicknes.quicknes_audio_samplerate.Value.32000"), new("44100", "Emulation.Option.quicknes.quicknes_audio_samplerate.Value.44100"), new("48000", "Emulation.Option.quicknes.quicknes_audio_samplerate.Value.48000"), new("96000", "Emulation.Option.quicknes.quicknes_audio_samplerate.Value.96000")]),
        new("quicknes_audio_nonlinear", "Emulation.Option.quicknes.quicknes_audio_nonlinear", "Emulation.Option.quicknes.quicknes_audio_nonlinear.Help", "", "nonlinear", "nonlinear", [new("nonlinear", "Emulation.Option.quicknes.quicknes_audio_nonlinear.Value.nonlinear"), new("linear", "Emulation.Option.quicknes.quicknes_audio_nonlinear.Value.linear"), new("stereo panning", "Emulation.Option.quicknes.quicknes_audio_nonlinear.Value.stereo panning")]),
        new("quicknes_audio_eq", "Emulation.Option.quicknes.quicknes_audio_eq", "Emulation.Option.quicknes.quicknes_audio_eq.Help", "", "default", "default", [new("default", "Emulation.Option.quicknes.quicknes_audio_eq.Value.default"), new("famicom", "Emulation.Option.quicknes.quicknes_audio_eq.Value.famicom"), new("tv", "TV"), new("flat", "Emulation.Option.quicknes.quicknes_audio_eq.Value.flat"), new("crisp", "Emulation.Option.quicknes.quicknes_audio_eq.Value.crisp"), new("tinny", "Emulation.Option.quicknes.quicknes_audio_eq.Value.tinny")]),
        new("quicknes_turbo_enable", "Emulation.Option.quicknes.quicknes_turbo_enable", "Emulation.Option.quicknes.quicknes_turbo_enable.Help", "", "none", "none", [new("none", "Emulation.Option.quicknes.quicknes_turbo_enable.Value.none"), new("player 1", "Emulation.Option.quicknes.quicknes_turbo_enable.Value.player 1"), new("player 2", "Emulation.Option.quicknes.quicknes_turbo_enable.Value.player 2"), new("both", "Emulation.Option.quicknes.quicknes_turbo_enable.Value.both")]),
        new("quicknes_turbo_pulse_width", "Emulation.Option.quicknes.quicknes_turbo_pulse_width", "Emulation.Option.quicknes.quicknes_turbo_pulse_width.Help", "", "3", "3", [new("1", "1"), new("2", "2"), new("3", "3"), new("5", "5"), new("10", "10"), new("15", "15"), new("30", "30"), new("60", "60")]),
        new("quicknes_up_down_allowed", "Emulation.Option.quicknes.quicknes_up_down_allowed", "Emulation.Option.quicknes.quicknes_up_down_allowed.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.quicknes.quicknes_up_down_allowed.Value.disabled"), new("enabled", "Emulation.Option.quicknes.quicknes_up_down_allowed.Value.enabled")])
    ];
}
