using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.PokeMini.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("pokemini_video_scale", "Emulation.Option.pokemini.pokemini_video_scale", "Emulation.Option.pokemini.pokemini_video_scale.Help", "", "4x", "4x", [new("1x", "1x"), new("2x", "2x"), new("3x", "3x"), new("4x", "4x"), new("5x", "5x"), new("6x", "6x"), new("7x", "7x")], Tab: EmulationMachineTab.Video, RequiresRestart: true),
        new("pokemini_60hz_mode", "Emulation.Option.pokemini.pokemini_60hz_mode", "Emulation.Option.pokemini.pokemini_60hz_mode.Help", "", "enabled", "enabled", [new("disabled", "Emulation.Option.pokemini.pokemini_60hz_mode.Value.disabled"), new("enabled", "Emulation.Option.pokemini.pokemini_60hz_mode.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("pokemini_lcdfilter", "Emulation.Option.pokemini.pokemini_lcdfilter", "Emulation.Option.pokemini.pokemini_lcdfilter.Help", "", "dotmatrix", "dotmatrix", [new("dotmatrix", "Emulation.Option.pokemini.pokemini_lcdfilter.Value.dotmatrix"), new("scanline", "Emulation.Option.pokemini.pokemini_lcdfilter.Value.scanline"), new("none", "Emulation.Option.pokemini.pokemini_lcdfilter.Value.none")], Tab: EmulationMachineTab.Video),
        new("pokemini_lcdmode", "Emulation.Option.pokemini.pokemini_lcdmode", "Emulation.Option.pokemini.pokemini_lcdmode.Help", "", "analog", "analog", [new("analog", "Emulation.Option.pokemini.pokemini_lcdmode.Value.analog"), new("3shades", "Emulation.Option.pokemini.pokemini_lcdmode.Value.3shades"), new("2shades", "Emulation.Option.pokemini.pokemini_lcdmode.Value.2shades")], Tab: EmulationMachineTab.Video),
        new("pokemini_lcdcontrast", "Emulation.Option.pokemini.pokemini_lcdcontrast", "Emulation.Option.pokemini.pokemini_lcdcontrast.Help", "", "64", "64", [new("0", "0"), new("16", "16"), new("32", "32"), new("48", "48"), new("64", "64"), new("80", "80"), new("96", "96")], Tab: EmulationMachineTab.Video),
        new("pokemini_lcdbright", "Emulation.Option.pokemini.pokemini_lcdbright", "Emulation.Option.pokemini.pokemini_lcdbright.Help", "", "0", "0", [new("-80", "-80"), new("-60", "-60"), new("-40", "-40"), new("-20", "-20"), new("0", "0"), new("20", "20"), new("40", "40"), new("60", "60"), new("80", "80")], Tab: EmulationMachineTab.Video),
        new("pokemini_palette", "Emulation.Option.pokemini.pokemini_palette", "Emulation.Option.pokemini.pokemini_palette.Help", "", "Default", "Default", [new("Default", "Emulation.Option.pokemini.pokemini_palette.Value.Default"), new("Old", "Emulation.Option.pokemini.pokemini_palette.Value.Old"), new("Monochrome", "Emulation.Option.pokemini.pokemini_palette.Value.Monochrome"), new("Green", "Emulation.Option.pokemini.pokemini_palette.Value.Green"), new("Green Vector", "Emulation.Option.pokemini.pokemini_palette.Value.Green Vector"), new("Red", "Emulation.Option.pokemini.pokemini_palette.Value.Red"), new("Red Vector", "Emulation.Option.pokemini.pokemini_palette.Value.Red Vector"), new("Blue LCD", "Emulation.Option.pokemini.pokemini_palette.Value.Blue LCD"), new("LEDBacklight", "Emulation.Option.pokemini.pokemini_palette.Value.LEDBacklight"), new("Girl Power", "Emulation.Option.pokemini.pokemini_palette.Value.Girl Power"), new("Blue", "Emulation.Option.pokemini.pokemini_palette.Value.Blue"), new("Blue Vector", "Emulation.Option.pokemini.pokemini_palette.Value.Blue Vector"), new("Sepia", "Emulation.Option.pokemini.pokemini_palette.Value.Sepia"), new("Monochrome Vector", "Emulation.Option.pokemini.pokemini_palette.Value.Monochrome Vector")], Tab: EmulationMachineTab.Video),
        new("pokemini_piezofilter", "Emulation.Option.pokemini.pokemini_piezofilter", "Emulation.Option.pokemini.pokemini_piezofilter.Help", "", "enabled", "enabled", [new("enabled", "Emulation.Option.pokemini.pokemini_piezofilter.Value.enabled"), new("disabled", "Emulation.Option.pokemini.pokemini_piezofilter.Value.disabled")], Tab: EmulationMachineTab.Audio),
        new("pokemini_lowpass_filter", "Emulation.Option.pokemini.pokemini_lowpass_filter", "Emulation.Option.pokemini.pokemini_lowpass_filter.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.pokemini.pokemini_lowpass_filter.Value.disabled"), new("enabled", "Emulation.Option.pokemini.pokemini_lowpass_filter.Value.enabled")], Tab: EmulationMachineTab.Audio),
        new("pokemini_lowpass_range", "Emulation.Option.pokemini.pokemini_lowpass_range", "Emulation.Option.pokemini.pokemini_lowpass_range.Help", "", "60", "60", [new("5", "5"), new("10", "10"), new("15", "15"), new("20", "20"), new("25", "25"), new("30", "30"), new("35", "35"), new("40", "40"), new("45", "45"), new("50", "50"), new("55", "55"), new("60", "60"), new("65", "65"), new("70", "70"), new("75", "75"), new("80", "80"), new("85", "85"), new("90", "90"), new("95", "95")], Tab: EmulationMachineTab.Audio),
        new("pokemini_screen_shake_lv", "Emulation.Option.pokemini.pokemini_screen_shake_lv", "Emulation.Option.pokemini.pokemini_screen_shake_lv.Help", "", "3", "3", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3")], Tab: EmulationMachineTab.Video),
        new("pokemini_rumble_lv", "Emulation.Option.pokemini.pokemini_rumble_lv", "Emulation.Option.pokemini.pokemini_rumble_lv.Help", "", "10", "10", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10")], Tab: EmulationMachineTab.Controllers),
        new("pokemini_turbo_period", "Emulation.Option.pokemini.pokemini_turbo_period", "Emulation.Option.pokemini.pokemini_turbo_period.Help", "", "18", "18", [new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24"), new("25", "25"), new("26", "26"), new("27", "27"), new("28", "28"), new("29", "29"), new("30", "30"), new("31", "31"), new("32", "32"), new("33", "33"), new("34", "34"), new("35", "35"), new("36", "36"), new("37", "37"), new("38", "38"), new("39", "39"), new("40", "40"), new("41", "41"), new("42", "42"), new("43", "43"), new("44", "44"), new("45", "45"), new("46", "46"), new("47", "47"), new("48", "48"), new("49", "49"), new("50", "50"), new("51", "51"), new("52", "52"), new("53", "53"), new("54", "54"), new("55", "55"), new("56", "56"), new("57", "57"), new("58", "58"), new("59", "59"), new("60", "60"), new("61", "61"), new("62", "62"), new("63", "63"), new("64", "64"), new("65", "65"), new("66", "66"), new("67", "67"), new("68", "68"), new("69", "69"), new("70", "70"), new("71", "71"), new("72", "72"), new("73", "73"), new("74", "74"), new("75", "75"), new("76", "76"), new("77", "77"), new("78", "78"), new("79", "79"), new("80", "80"), new("81", "81"), new("82", "82"), new("83", "83"), new("84", "84"), new("85", "85"), new("86", "86"), new("87", "87"), new("88", "88"), new("89", "89"), new("90", "90"), new("91", "91"), new("92", "92"), new("93", "93"), new("94", "94"), new("95", "95"), new("96", "96"), new("97", "97"), new("98", "98"), new("99", "99"), new("100", "100"), new("101", "101"), new("102", "102"), new("103", "103"), new("104", "104"), new("105", "105"), new("106", "106"), new("107", "107"), new("108", "108"), new("109", "109"), new("110", "110"), new("111", "111"), new("112", "112"), new("113", "113"), new("114", "114"), new("115", "115"), new("116", "116"), new("117", "117"), new("118", "118"), new("119", "119"), new("120", "120")], Tab: EmulationMachineTab.Controllers)
    ];
}
