using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Cemu.Constants;

internal static class OptionConstants
{
    internal const string GraphicsApiOption = "cemu_gpu_api";
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("cemu_cpu_mode", "Emulation.Option.cemu.cemu_cpu_mode", "Emulation.Option.cemu.cemu_cpu_mode.Help", "system", "auto", "auto", [new("auto", "Emulation.Option.cemu.cemu_cpu_mode.Value.auto"), new("singlecore_interpreter", "Emulation.Option.cemu.cemu_cpu_mode.Value.singlecore_interpreter"), new("singlecore_recompiler", "Emulation.Option.cemu.cemu_cpu_mode.Value.singlecore_recompiler"), new("multicore_recompiler", "Emulation.Option.cemu.cemu_cpu_mode.Value.multicore_recompiler"), new("multicore_interpreter", "Emulation.Option.cemu.cemu_cpu_mode.Value.multicore_interpreter")]),
        new("cemu_console_language", "Emulation.Option.cemu.cemu_console_language", null, "system", "English", "English", [new("English", "Emulation.Option.cemu.cemu_console_language.Value.English"), new("Japanese", "Emulation.Option.cemu.cemu_console_language.Value.Japanese"), new("French", "Emulation.Option.cemu.cemu_console_language.Value.French"), new("German", "Emulation.Option.cemu.cemu_console_language.Value.German"), new("Italian", "Emulation.Option.cemu.cemu_console_language.Value.Italian"), new("Spanish", "Emulation.Option.cemu.cemu_console_language.Value.Spanish"), new("Chinese", "Emulation.Option.cemu.cemu_console_language.Value.Chinese"), new("Korean", "Emulation.Option.cemu.cemu_console_language.Value.Korean"), new("Dutch", "Emulation.Option.cemu.cemu_console_language.Value.Dutch"), new("Portuguese", "Emulation.Option.cemu.cemu_console_language.Value.Portuguese"), new("Russian", "Emulation.Option.cemu.cemu_console_language.Value.Russian"), new("Taiwanese", "Emulation.Option.cemu.cemu_console_language.Value.Taiwanese")]),
        new("cemu_async_shader_compile", "Emulation.Option.cemu.cemu_async_shader_compile", null, "shaders", "enabled", "enabled", [new("enabled", "Emulation.Option.cemu.cemu_async_shader_compile.Value.enabled"), new("disabled", "Emulation.Option.cemu.cemu_async_shader_compile.Value.disabled")]),
        new("cemu_gx2drawdone_sync", "Emulation.Option.cemu.cemu_gx2drawdone_sync", null, "shaders", "enabled", "enabled", [new("enabled", "Emulation.Option.cemu.cemu_gx2drawdone_sync.Value.enabled"), new("disabled", "Emulation.Option.cemu.cemu_gx2drawdone_sync.Value.disabled")]),
        new("cemu_precompiled_shaders", "Emulation.Option.cemu.cemu_precompiled_shaders", null, "shaders", "auto", "auto", [new("auto", "Emulation.Option.cemu.cemu_precompiled_shaders.Value.auto"), new("enabled", "Emulation.Option.cemu.cemu_precompiled_shaders.Value.enabled"), new("disabled", "Emulation.Option.cemu.cemu_precompiled_shaders.Value.disabled")]),
        new("cemu_accurate_shader_mul", "Emulation.Option.cemu.cemu_accurate_shader_mul", null, "shaders", "enabled", "enabled", [new("enabled", "Emulation.Option.cemu.cemu_accurate_shader_mul.Value.enabled"), new("disabled", "Emulation.Option.cemu.cemu_accurate_shader_mul.Value.disabled")]),
        new("cemu_upscale_filter", "Emulation.Option.cemu.cemu_upscale_filter", null, "video", "linear", "linear", [new("linear", "Emulation.Option.cemu.cemu_upscale_filter.Value.linear"), new("bicubic", "Emulation.Option.cemu.cemu_upscale_filter.Value.bicubic"), new("bicubic_hermite", "Emulation.Option.cemu.cemu_upscale_filter.Value.bicubic_hermite"), new("nearest", "Emulation.Option.cemu.cemu_upscale_filter.Value.nearest")]),
        new("cemu_show_game_fps", "Emulation.Option.cemu.cemu_show_game_fps", "Emulation.Option.cemu.cemu_show_game_fps.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_show_game_fps.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_show_game_fps.Value.enabled")]),
        new("cemu_downscale_filter", "Emulation.Option.cemu.cemu_downscale_filter", null, "video", "linear", "linear", [new("linear", "Emulation.Option.cemu.cemu_downscale_filter.Value.linear"), new("bicubic", "Emulation.Option.cemu.cemu_downscale_filter.Value.bicubic"), new("bicubic_hermite", "Emulation.Option.cemu.cemu_downscale_filter.Value.bicubic_hermite"), new("nearest", "Emulation.Option.cemu.cemu_downscale_filter.Value.nearest")]),
        new("cemu_internal_resolution", "Emulation.Option.cemu.cemu_internal_resolution", "Emulation.Option.cemu.cemu_internal_resolution.Help", "video", "1280x720", "1280x720", [new("640x360", "640x360"), new("960x540", "960x540"), new("1280x720", "1280x720"), new("1920x1080", "1920x1080"), new("2560x1440", "2560x1440"), new("3840x2160", "3840x2160")]),
        new("cemu_fullscreen_scaling", "Emulation.Option.cemu.cemu_fullscreen_scaling", null, "video", "keep_aspect", "keep_aspect", [new("keep_aspect", "Emulation.Option.cemu.cemu_fullscreen_scaling.Value.keep_aspect"), new("stretch", "Emulation.Option.cemu.cemu_fullscreen_scaling.Value.stretch")]),
        new("cemu_thread_quantum", "Emulation.Option.cemu.cemu_thread_quantum", null, "system", "45000", "45000", [new("20000", "20000"), new("45000", "45000"), new("60000", "60000"), new("80000", "80000"), new("100000", "100000")]),
        new("cemu_rumble_strength", "Emulation.Option.cemu.cemu_rumble_strength", "Emulation.Option.cemu.cemu_rumble_strength.Help", "system", "100", "100", [new("0", "Emulation.Option.cemu.cemu_rumble_strength.Value.0"), new("25", "25%"), new("50", "50%"), new("75", "75%"), new("100", "100%")]),
        new("cemu_emulate_skylander_portal", "Emulation.Option.cemu.cemu_emulate_skylander_portal", null, "addons", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_emulate_skylander_portal.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_emulate_skylander_portal.Value.enabled")]),
        new("cemu_emulate_infinity_base", "Emulation.Option.cemu.cemu_emulate_infinity_base", null, "addons", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_emulate_infinity_base.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_emulate_infinity_base.Value.enabled")]),
        new("cemu_emulate_dimensions_toypad", "Emulation.Option.cemu.cemu_emulate_dimensions_toypad", null, "addons", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_emulate_dimensions_toypad.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_emulate_dimensions_toypad.Value.enabled")]),
        new("cemu_number_of_screen_layouts", "Emulation.Option.cemu.cemu_number_of_screen_layouts", null, "screen", "2", "2", [new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5")]),
        new("cemu_screen_layout1", "Emulation.Option.cemu.cemu_screen_layout1", null, "screen", "Default Screen", "Default Screen", [new("Default Screen", "Emulation.Option.cemu.cemu_screen_layout1.Value.Default Screen"), new("GamePad Screen", "Emulation.Option.cemu.cemu_screen_layout1.Value.GamePad Screen"), new("Side by Side", "Emulation.Option.cemu.cemu_screen_layout1.Value.Side by Side"), new("Top Bottom", "Emulation.Option.cemu.cemu_screen_layout1.Value.Top Bottom"), new("Picture in Picture", "Emulation.Option.cemu.cemu_screen_layout1.Value.Picture in Picture")]),
        new("cemu_screen_layout2", "Emulation.Option.cemu.cemu_screen_layout2", null, "screen", "GamePad Screen", "GamePad Screen", [new("Default Screen", "Emulation.Option.cemu.cemu_screen_layout2.Value.Default Screen"), new("GamePad Screen", "Emulation.Option.cemu.cemu_screen_layout2.Value.GamePad Screen"), new("Side by Side", "Emulation.Option.cemu.cemu_screen_layout2.Value.Side by Side"), new("Top Bottom", "Emulation.Option.cemu.cemu_screen_layout2.Value.Top Bottom"), new("Picture in Picture", "Emulation.Option.cemu.cemu_screen_layout2.Value.Picture in Picture")]),
        new("cemu_screen_layout3", "Emulation.Option.cemu.cemu_screen_layout3", null, "screen", "Side by Side", "Side by Side", [new("Default Screen", "Emulation.Option.cemu.cemu_screen_layout3.Value.Default Screen"), new("GamePad Screen", "Emulation.Option.cemu.cemu_screen_layout3.Value.GamePad Screen"), new("Side by Side", "Emulation.Option.cemu.cemu_screen_layout3.Value.Side by Side"), new("Top Bottom", "Emulation.Option.cemu.cemu_screen_layout3.Value.Top Bottom"), new("Picture in Picture", "Emulation.Option.cemu.cemu_screen_layout3.Value.Picture in Picture")]),
        new("cemu_screen_layout4", "Emulation.Option.cemu.cemu_screen_layout4", null, "screen", "Top Bottom", "Top Bottom", [new("Default Screen", "Emulation.Option.cemu.cemu_screen_layout4.Value.Default Screen"), new("GamePad Screen", "Emulation.Option.cemu.cemu_screen_layout4.Value.GamePad Screen"), new("Side by Side", "Emulation.Option.cemu.cemu_screen_layout4.Value.Side by Side"), new("Top Bottom", "Emulation.Option.cemu.cemu_screen_layout4.Value.Top Bottom"), new("Picture in Picture", "Emulation.Option.cemu.cemu_screen_layout4.Value.Picture in Picture")]),
        new("cemu_screen_layout5", "Emulation.Option.cemu.cemu_screen_layout5", null, "screen", "Picture in Picture", "Picture in Picture", [new("Default Screen", "Emulation.Option.cemu.cemu_screen_layout5.Value.Default Screen"), new("GamePad Screen", "Emulation.Option.cemu.cemu_screen_layout5.Value.GamePad Screen"), new("Side by Side", "Emulation.Option.cemu.cemu_screen_layout5.Value.Side by Side"), new("Top Bottom", "Emulation.Option.cemu.cemu_screen_layout5.Value.Top Bottom"), new("Picture in Picture", "Emulation.Option.cemu.cemu_screen_layout5.Value.Picture in Picture")]),
        new("cemu_next_screen_layout_button", "Emulation.Option.cemu.cemu_next_screen_layout_button", null, "screen", "L + R + L2 + R2 + L3 + R3", "L + R + L2 + R2 + L3 + R3", [new("Disabled", "Emulation.Option.cemu.cemu_next_screen_layout_button.Value.Disabled"), new("L + R + L2 + R2 + L3 + R3", "L + R + L2 + R2 + L3 + R3"), new("Select + L3", "Emulation.Option.cemu.cemu_next_screen_layout_button.Value.Select + L3"), new("Select + R3", "Emulation.Option.cemu.cemu_next_screen_layout_button.Value.Select + R3"), new("Tab", "Emulation.Option.cemu.cemu_next_screen_layout_button.Value.Tab")]),
        new("cemu_drc_position", "Emulation.Option.cemu.cemu_drc_position", null, "screen", "normal", "normal", [new("normal", "Emulation.Option.cemu.cemu_drc_position.Value.normal"), new("swapped", "Emulation.Option.cemu.cemu_drc_position.Value.swapped")]),
        new("cemu_dump_shaders", "Emulation.Option.cemu.cemu_dump_shaders", "Emulation.Option.cemu.cemu_dump_shaders.Help", "logging", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_dump_shaders.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_dump_shaders.Value.enabled")]),
        new("cemu_log_to_file", "Emulation.Option.cemu.cemu_log_to_file", null, "logging", "enabled", "enabled", [new("enabled", "Emulation.Option.cemu.cemu_log_to_file.Value.enabled"), new("disabled", "Emulation.Option.cemu.cemu_log_to_file.Value.disabled")]),
        new("cemu_log_filesystem", "Emulation.Option.cemu.cemu_log_filesystem", null, "logging", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_log_filesystem.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_log_filesystem.Value.enabled")]),
        new("cemu_log_thread_sync", "Emulation.Option.cemu.cemu_log_thread_sync", null, "logging", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_log_thread_sync.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_log_thread_sync.Value.enabled")]),
        new("cemu_log_system_api", "Emulation.Option.cemu.cemu_log_system_api", null, "logging", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_log_system_api.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_log_system_api.Value.enabled")]),
        new("cemu_log_texture_memory", "Emulation.Option.cemu.cemu_log_texture_memory", "Emulation.Option.cemu.cemu_log_texture_memory.Help", "logging", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_log_texture_memory.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_log_texture_memory.Value.enabled")]),
        new("cemu_log_input_api", "Emulation.Option.cemu.cemu_log_input_api", "Emulation.Option.cemu.cemu_log_input_api.Help", "logging", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_log_input_api.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_log_input_api.Value.enabled")]),
        new("cemu_log_audio", "Emulation.Option.cemu.cemu_log_audio", "Emulation.Option.cemu.cemu_log_audio.Help", "logging", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_log_audio.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_log_audio.Value.enabled")]),
        new("cemu_bc1_16bit", "Emulation.Option.cemu.cemu_bc1_16bit", "Emulation.Option.cemu.cemu_bc1_16bit.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_bc1_16bit.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_bc1_16bit.Value.enabled")]),
        new(GraphicsApiOption, "Emulation.Option.cemu.cemu_gpu_api", "Emulation.Option.cemu.cemu_gpu_api.Help", "video", "OpenGL", "OpenGL", [new("OpenGL", "Emulation.Option.cemu.cemu_gpu_api.Value.OpenGL"), new("Vulkan", "Emulation.Option.cemu.cemu_gpu_api.Value.Vulkan")]),
        new("cemu_install_game", "Emulation.Option.cemu.cemu_install_game", "Emulation.Option.cemu.cemu_install_game.Help", "install", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_install_game.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_install_game.Value.enabled")]),
        new("cemu_uninstall_game", "Emulation.Option.cemu.cemu_uninstall_game", "Emulation.Option.cemu.cemu_uninstall_game.Help", "install", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_uninstall_game.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_uninstall_game.Value.enabled")]),
        new("cemu_install_titles", "Emulation.Option.cemu.cemu_install_titles", "Emulation.Option.cemu.cemu_install_titles.Help", "install", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_install_titles.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_install_titles.Value.enabled")]),
        new("cemu_uninstall_titles", "Emulation.Option.cemu.cemu_uninstall_titles", "Emulation.Option.cemu.cemu_uninstall_titles.Help", "install", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_uninstall_titles.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_uninstall_titles.Value.enabled")]),
        new("cemu_install_remove_source", "Emulation.Option.cemu.cemu_install_remove_source", "Emulation.Option.cemu.cemu_install_remove_source.Help", "install", "disabled", "disabled", [new("disabled", "Emulation.Option.cemu.cemu_install_remove_source.Value.disabled"), new("enabled", "Emulation.Option.cemu.cemu_install_remove_source.Value.enabled")])
    ];
}
