namespace GWGUI.Emulation.Sega.Emulators.SmsPlusGX.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("smsplus_sms_bios", "Emulation.Option.smsplus.smsplus_sms_bios", "Emulation.Option.smsplus.smsplus_sms_bios.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.smsplus.smsplus_sms_bios.Value.disabled"), new("auto", "Emulation.Option.smsplus.smsplus_sms_bios.Value.auto")], Tab: EmulationMachineTab.Rom, RequiresRestart: true),
        new("smsplus_hardware", "Emulation.Option.smsplus.smsplus_hardware", "Emulation.Option.smsplus.smsplus_hardware.Description", null, "auto", "auto", [new("auto", "Emulation.Option.smsplus.smsplus_hardware.Value.auto"), new("master system", "Emulation.Option.smsplus.smsplus_hardware.Value.master system"), new("master system II", "Emulation.Option.smsplus.smsplus_hardware.Value.master system II"), new("game gear", "Emulation.Option.smsplus.smsplus_hardware.Value.game gear"), new("game gear (sms compatibility)", "Emulation.Option.smsplus.smsplus_hardware.Value.game gear (sms compatibility)"), new("coleco", "Emulation.Option.smsplus.smsplus_hardware.Value.coleco")], Tab: EmulationMachineTab.General, RequiresRestart: true),
        new("smsplus_region", "Emulation.Option.smsplus.smsplus_region", "Emulation.Option.smsplus.smsplus_region.Description", null, "auto", "auto", [new("auto", "Emulation.Option.smsplus.smsplus_region.Value.auto"), new("ntsc-u", "Emulation.Option.smsplus.smsplus_region.Value.ntsc-u"), new("pal", "Emulation.Option.smsplus.smsplus_region.Value.pal"), new("ntsc-j", "Emulation.Option.smsplus.smsplus_region.Value.ntsc-j")], Tab: EmulationMachineTab.General, RequiresRestart: true),
        new("smsplus_fm_sound", "Emulation.Option.smsplus.smsplus_fm_sound", "Emulation.Option.smsplus.smsplus_fm_sound.Description", null, "auto", "auto", [new("auto", "Emulation.Option.smsplus.smsplus_fm_sound.Value.auto"), new("disabled", "Emulation.Option.smsplus.smsplus_fm_sound.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: true),
        new("smsplus_hide_left_border", "Emulation.Option.smsplus.smsplus_hide_left_border", "Emulation.Option.smsplus.smsplus_hide_left_border.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.smsplus.smsplus_hide_left_border.Value.disabled"), new("enabled", "Emulation.Option.smsplus.smsplus_hide_left_border.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("smsplus_ntsc_filter", "Emulation.Option.smsplus.smsplus_ntsc_filter", "Emulation.Option.smsplus.smsplus_ntsc_filter.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.smsplus.smsplus_ntsc_filter.Value.disabled"), new("composite", "Emulation.Option.smsplus.smsplus_ntsc_filter.Value.composite"), new("svideo", "Emulation.Option.smsplus.smsplus_ntsc_filter.Value.svideo"), new("rgb", "Emulation.Option.smsplus.smsplus_ntsc_filter.Value.rgb"), new("monochrome", "Emulation.Option.smsplus.smsplus_ntsc_filter.Value.monochrome")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
    ];
}
