namespace GWGUI.Emulation.Sega.Emulators.Kronos.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("kronos_force_hle_bios", "Emulation.Option.kronos.kronos_force_hle_bios", "Emulation.Option.kronos.kronos_force_hle_bios.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_force_hle_bios.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_force_hle_bios.Value.enabled")], Tab: EmulationMachineTab.Rom, RequiresRestart: false, MachineIds: OptionMachineConstants.Saturn),
        new("kronos_videoformattype", "Emulation.Option.kronos.kronos_videoformattype", "Emulation.Option.kronos.kronos_videoformattype.Description", null, "auto", "auto", [new("auto", "Emulation.Option.kronos.kronos_videoformattype.Value.auto"), new("NTSC", "Emulation.Option.kronos.kronos_videoformattype.Value.NTSC"), new("PAL", "Emulation.Option.kronos.kronos_videoformattype.Value.PAL")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("kronos_skipframe", "Emulation.Option.kronos.kronos_skipframe", "Emulation.Option.kronos.kronos_skipframe.Description", null, "0", "0", [new("0", "Emulation.Option.kronos.kronos_skipframe.Value.0"), new("1", "Emulation.Option.kronos.kronos_skipframe.Value.1"), new("2", "Emulation.Option.kronos.kronos_skipframe.Value.2"), new("3", "Emulation.Option.kronos.kronos_skipframe.Value.3"), new("4", "Emulation.Option.kronos.kronos_skipframe.Value.4"), new("5", "Emulation.Option.kronos.kronos_skipframe.Value.5")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("kronos_usecache", "Emulation.Option.kronos.kronos_usecache", "Emulation.Option.kronos.kronos_usecache.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_usecache.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_usecache.Value.enabled")], Tab: EmulationMachineTab.Cpu, RequiresRestart: false),
        new("kronos_use_beetle_saves", "Emulation.Option.kronos.kronos_use_beetle_saves", "Emulation.Option.kronos.kronos_use_beetle_saves.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_use_beetle_saves.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_use_beetle_saves.Value.enabled")], Tab: EmulationMachineTab.Storage, RequiresRestart: false, MachineIds: OptionMachineConstants.Saturn),
        new("kronos_addon_cartridge", "Emulation.Option.kronos.kronos_addon_cartridge", "Emulation.Option.kronos.kronos_addon_cartridge.Description", null, "512K_backup_ram", "512K_backup_ram", [new("none", "Emulation.Option.kronos.kronos_addon_cartridge.Value.none"), new("1M_extended_ram", "Emulation.Option.kronos.kronos_addon_cartridge.Value.1M_extended_ram"), new("4M_extended_ram", "Emulation.Option.kronos.kronos_addon_cartridge.Value.4M_extended_ram"), new("16M_extended_ram", "Emulation.Option.kronos.kronos_addon_cartridge.Value.16M_extended_ram"), new("512K_backup_ram", "Emulation.Option.kronos.kronos_addon_cartridge.Value.512K_backup_ram"), new("1M_backup_ram", "Emulation.Option.kronos.kronos_addon_cartridge.Value.1M_backup_ram"), new("2M_backup_ram", "Emulation.Option.kronos.kronos_addon_cartridge.Value.2M_backup_ram"), new("4M_backup_ram", "Emulation.Option.kronos.kronos_addon_cartridge.Value.4M_backup_ram")], Tab: EmulationMachineTab.Ram, RequiresRestart: false, MachineIds: OptionMachineConstants.Saturn),
        new("kronos_multitap_port1", "Emulation.Option.kronos.kronos_multitap_port1", "Emulation.Option.kronos.kronos_multitap_port1.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_multitap_port1.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_multitap_port1.Value.enabled")], Tab: EmulationMachineTab.Controllers, RequiresRestart: false, MachineIds: OptionMachineConstants.Saturn),
        new("kronos_multitap_port2", "Emulation.Option.kronos.kronos_multitap_port2", "Emulation.Option.kronos.kronos_multitap_port2.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_multitap_port2.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_multitap_port2.Value.enabled")], Tab: EmulationMachineTab.Controllers, RequiresRestart: false, MachineIds: OptionMachineConstants.Saturn),
        new("kronos_resolution_mode", "Emulation.Option.kronos.kronos_resolution_mode", "Emulation.Option.kronos.kronos_resolution_mode.Description", null, "original", "original", [new("original", "Emulation.Option.kronos.kronos_resolution_mode.Value.original"), new("2X", "Emulation.Option.kronos.kronos_resolution_mode.Value.2X"), new("4X", "Emulation.Option.kronos.kronos_resolution_mode.Value.4X"), new("8X", "Emulation.Option.kronos.kronos_resolution_mode.Value.8X")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("kronos_force_downsampling", "Emulation.Option.kronos.kronos_force_downsampling", "Emulation.Option.kronos.kronos_force_downsampling.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_force_downsampling.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_force_downsampling.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("kronos_meshmode", "Emulation.Option.kronos.kronos_meshmode", "Emulation.Option.kronos.kronos_meshmode.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_meshmode.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_meshmode.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("kronos_bandingmode", "Emulation.Option.kronos.kronos_bandingmode", "Emulation.Option.kronos.kronos_bandingmode.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_bandingmode.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_bandingmode.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("kronos_video_filter_type", "Emulation.Option.kronos.kronos_video_filter_type", "Emulation.Option.kronos.kronos_video_filter_type.Description", null, "0", "0", [new("0", "Emulation.Option.kronos.kronos_video_filter_type.Value.0"), new("3", "Emulation.Option.kronos.kronos_video_filter_type.Value.3"), new("5", "Emulation.Option.kronos.kronos_video_filter_type.Value.5")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("kronos_wireframe_mode", "Emulation.Option.kronos.kronos_wireframe_mode", "Emulation.Option.kronos.kronos_wireframe_mode.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_wireframe_mode.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_wireframe_mode.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("kronos_service_enabled", "Emulation.Option.kronos.kronos_service_enabled", "Emulation.Option.kronos.kronos_service_enabled.Description", null, "disabled", "disabled", [new("disabled", "Emulation.Option.kronos.kronos_service_enabled.Value.disabled"), new("enabled", "Emulation.Option.kronos.kronos_service_enabled.Value.enabled")], Tab: EmulationMachineTab.General, RequiresRestart: false, MachineIds: OptionMachineConstants.StV),
        new("kronos_stv_favorite_region", "Emulation.Option.kronos.kronos_stv_favorite_region", "Emulation.Option.kronos.kronos_stv_favorite_region.Description", null, "EU", "EU", [new("EU", "Emulation.Option.kronos.kronos_stv_favorite_region.Value.EU"), new("US", "Emulation.Option.kronos.kronos_stv_favorite_region.Value.US"), new("JP", "Emulation.Option.kronos.kronos_stv_favorite_region.Value.JP"), new("TW", "Emulation.Option.kronos.kronos_stv_favorite_region.Value.TW")], Tab: EmulationMachineTab.General, RequiresRestart: false, MachineIds: OptionMachineConstants.StV),
        new("kronos_language_id", "Emulation.Option.kronos.kronos_language_id", "Emulation.Option.kronos.kronos_language_id.Description", null, "EU", "EU", [new("English", "Emulation.Option.kronos.kronos_language_id.Value.English"), new("German", "Emulation.Option.kronos.kronos_language_id.Value.German"), new("French", "Emulation.Option.kronos.kronos_language_id.Value.French"), new("Spanish", "Emulation.Option.kronos.kronos_language_id.Value.Spanish"), new("Italian", "Emulation.Option.kronos.kronos_language_id.Value.Italian"), new("Japanese", "Emulation.Option.kronos.kronos_language_id.Value.Japanese")], Tab: EmulationMachineTab.General, RequiresRestart: false, MachineIds: OptionMachineConstants.Saturn),
    ];
}
