using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Noods.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("noods_directBoot", "Emulation.Option.noods.noods_directBoot", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.noods.noods_directBoot.Value.enabled"), new("disabled", "Emulation.Option.noods.noods_directBoot.Value.disabled")], Tab: EmulationMachineTab.Rom),
        new("noods_fpsLimiter", "Emulation.Option.noods.noods_fpsLimiter", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.noods.noods_fpsLimiter.Value.disabled"), new("enabled", "Emulation.Option.noods.noods_fpsLimiter.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("noods_frameskip", "Emulation.Option.noods.noods_frameskip", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.noods.noods_frameskip.Value.disabled"), new("enabled", "Emulation.Option.noods.noods_frameskip.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("noods_romInRam", "Emulation.Option.noods.noods_romInRam", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.noods.noods_romInRam.Value.disabled"), new("enabled", "Emulation.Option.noods.noods_romInRam.Value.enabled")], Tab: EmulationMachineTab.Ram),
        new("noods_dsiMode", "Emulation.Option.noods.noods_dsiMode", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.noods.noods_dsiMode.Value.disabled"), new("enabled", "Emulation.Option.noods.noods_dsiMode.Value.enabled")], Tab: EmulationMachineTab.General, IsVisible: false),
        new("noods_arm7Hle", "Emulation.Option.noods.noods_arm7Hle", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.noods.noods_arm7Hle.Value.disabled"), new("enabled", "Emulation.Option.noods.noods_arm7Hle.Value.enabled")], Tab: EmulationMachineTab.Rom),
        new("noods_threaded2D", "Emulation.Option.noods.noods_threaded2D", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.noods.noods_threaded2D.Value.enabled"), new("disabled", "Emulation.Option.noods.noods_threaded2D.Value.disabled")], Tab: EmulationMachineTab.Video),
        new("noods_threaded3D", "Emulation.Option.noods.noods_threaded3D", null, "", "1 Thread", "1 Thread", [new("1 Thread", "Emulation.Option.noods.noods_threaded3D.Value.1 Thread"), new("2 Threads", "Emulation.Option.noods.noods_threaded3D.Value.2 Threads"), new("3 Threads", "Emulation.Option.noods.noods_threaded3D.Value.3 Threads"), new("4 Threads", "Emulation.Option.noods.noods_threaded3D.Value.4 Threads"), new("Disabled", "Emulation.Option.noods.noods_threaded3D.Value.Disabled")], Tab: EmulationMachineTab.Video),
        new("noods_highRes3D", "Emulation.Option.noods.noods_highRes3D", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.noods.noods_highRes3D.Value.disabled"), new("enabled", "Emulation.Option.noods.noods_highRes3D.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("noods_screenArrangement", "Emulation.Option.noods.noods_screenArrangement", null, "", "Automatic", "Automatic", [new("Automatic", "Emulation.Option.noods.noods_screenArrangement.Value.Automatic"), new("Vertical", "Emulation.Option.noods.noods_screenArrangement.Value.Vertical"), new("Horizontal", "Emulation.Option.noods.noods_screenArrangement.Value.Horizontal"), new("Single Screen", "Emulation.Option.noods.noods_screenArrangement.Value.Single Screen")], Tab: EmulationMachineTab.Video),
        new("noods_screenRotation", "Emulation.Option.noods.noods_screenRotation", null, "", "Normal", "Normal", [new("Normal", "Emulation.Option.noods.noods_screenRotation.Value.Normal"), new("Rotated Left", "Emulation.Option.noods.noods_screenRotation.Value.Rotated Left"), new("Rotated Right", "Emulation.Option.noods.noods_screenRotation.Value.Rotated Right")], Tab: EmulationMachineTab.Video),
        new("noods_screenSizing", "Emulation.Option.noods.noods_screenSizing", null, "", "Even", "Even", [new("Even", "Emulation.Option.noods.noods_screenSizing.Value.Even"), new("Enlarge Top", "Emulation.Option.noods.noods_screenSizing.Value.Enlarge Top"), new("Enlarge Bottom", "Emulation.Option.noods.noods_screenSizing.Value.Enlarge Bottom")], Tab: EmulationMachineTab.Video),
        new("noods_screenPosition", "Emulation.Option.noods.noods_screenPosition", null, "", "Center", "Center", [new("Center", "Emulation.Option.noods.noods_screenPosition.Value.Center"), new("Start", "Emulation.Option.noods.noods_screenPosition.Value.Start"), new("End", "Emulation.Option.noods.noods_screenPosition.Value.End")], Tab: EmulationMachineTab.Video),
        new("noods_screenGap", "Emulation.Option.noods.noods_screenGap", null, "", "None", "None", [new("None", "Emulation.Option.noods.noods_screenGap.Value.None"), new("Quarter", "Emulation.Option.noods.noods_screenGap.Value.Quarter"), new("Half", "Emulation.Option.noods.noods_screenGap.Value.Half"), new("Full", "Emulation.Option.noods.noods_screenGap.Value.Full")], Tab: EmulationMachineTab.Video),
        new("noods_gbaCrop", "Emulation.Option.noods.noods_gbaCrop", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.noods.noods_gbaCrop.Value.enabled"), new("disabled", "Emulation.Option.noods.noods_gbaCrop.Value.disabled")], Tab: EmulationMachineTab.General, IsVisible: false),
        new("noods_screenFilter", "Emulation.Option.noods.noods_screenFilter", null, "", "Nearest", "Nearest", [new("Nearest", "Emulation.Option.noods.noods_screenFilter.Value.Nearest"), new("Upscaled", "Emulation.Option.noods.noods_screenFilter.Value.Upscaled"), new("Linear", "Emulation.Option.noods.noods_screenFilter.Value.Linear")], Tab: EmulationMachineTab.Video),
        new("noods_screenGhost", "Emulation.Option.noods.noods_screenGhost", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.noods.noods_screenGhost.Value.disabled"), new("enabled", "Emulation.Option.noods.noods_screenGhost.Value.enabled")], Tab: EmulationMachineTab.Video),
        new("noods_emulateAudio", "Emulation.Option.noods.noods_emulateAudio", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.noods.noods_emulateAudio.Value.enabled"), new("disabled", "Emulation.Option.noods.noods_emulateAudio.Value.disabled")], Tab: EmulationMachineTab.Audio),
        new("noods_audio16Bit", "Emulation.Option.noods.noods_audio16Bit", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.noods.noods_audio16Bit.Value.enabled"), new("disabled", "Emulation.Option.noods.noods_audio16Bit.Value.disabled")], Tab: EmulationMachineTab.Audio),
        new("noods_swapScreenMode", "Emulation.Option.noods.noods_swapScreenMode", null, "", "Toggle", "Toggle", [new("Toggle", "Emulation.Option.noods.noods_swapScreenMode.Value.Toggle"), new("Hold", "Emulation.Option.noods.noods_swapScreenMode.Value.Hold")], Tab: EmulationMachineTab.Video),
        new("noods_touchMode", "Emulation.Option.noods.noods_touchMode", null, "", "Auto", "Auto", [new("Auto", "Emulation.Option.noods.noods_touchMode.Value.Auto"), new("Pointer", "Emulation.Option.noods.noods_touchMode.Value.Pointer"), new("Joystick", "Emulation.Option.noods.noods_touchMode.Value.Joystick"), new("None", "Emulation.Option.noods.noods_touchMode.Value.None")], Tab: EmulationMachineTab.Mouse),
        new("noods_touchCursor", "Emulation.Option.noods.noods_touchCursor", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.noods.noods_touchCursor.Value.enabled"), new("disabled", "Emulation.Option.noods.noods_touchCursor.Value.disabled")], Tab: EmulationMachineTab.Mouse),
        new("noods_cursorTimeout", "Emulation.Option.noods.noods_cursorTimeout", null, "", "3 Seconds", "3 Seconds", [new("3 Seconds", "Emulation.Option.noods.noods_cursorTimeout.Value.3 Seconds"), new("5 Seconds", "Emulation.Option.noods.noods_cursorTimeout.Value.5 Seconds"), new("10 Seconds", "Emulation.Option.noods.noods_cursorTimeout.Value.10 Seconds"), new("15 Seconds", "Emulation.Option.noods.noods_cursorTimeout.Value.15 Seconds"), new("20 Seconds", "Emulation.Option.noods.noods_cursorTimeout.Value.20 Seconds"), new("Never Hide", "Emulation.Option.noods.noods_cursorTimeout.Value.Never Hide")], Tab: EmulationMachineTab.General),
        new("noods_micInputMode", "Emulation.Option.noods.noods_micInputMode", null, "", "Silence", "Silence", [new("Silence", "Emulation.Option.noods.noods_micInputMode.Value.Silence"), new("Noise", "Emulation.Option.noods.noods_micInputMode.Value.Noise"), new("Microphone", "Emulation.Option.noods.noods_micInputMode.Value.Microphone")], Tab: EmulationMachineTab.Audio),
        new("noods_micButtonMode", "Emulation.Option.noods.noods_micButtonMode", null, "", "Toggle", "Toggle", [new("Toggle", "Emulation.Option.noods.noods_micButtonMode.Value.Toggle"), new("Hold", "Emulation.Option.noods.noods_micButtonMode.Value.Hold"), new("Always", "Emulation.Option.noods.noods_micButtonMode.Value.Always")], Tab: EmulationMachineTab.Audio)
    ];
}
