using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Supafaust.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("supafaust_pixel_format", "Emulation.Option.mednafen_supafaust.supafaust_pixel_format", null, "", "rgb565", "rgb565", [new("rgb565", "Emulation.Option.mednafen_supafaust.supafaust_pixel_format.Value.rgb565"), new("xrgb8888", "Emulation.Option.mednafen_supafaust.supafaust_pixel_format.Value.xrgb8888"), new("0rgb1555", "Emulation.Option.mednafen_supafaust.supafaust_pixel_format.Value.0rgb1555")]),
        new("supafaust_correct_aspect", "Emulation.Option.mednafen_supafaust.supafaust_correct_aspect", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.mednafen_supafaust.supafaust_correct_aspect.Value.enabled"), new("disabled", "Emulation.Option.mednafen_supafaust.supafaust_correct_aspect.Value.disabled"), new("force_ntsc", "Emulation.Option.mednafen_supafaust.supafaust_correct_aspect.Value.force_ntsc"), new("force_pal", "Emulation.Option.mednafen_supafaust.supafaust_correct_aspect.Value.force_pal")]),
        new("supafaust_h_filter", "Emulation.Option.mednafen_supafaust.supafaust_h_filter", null, "", "phr256blend_auto512", "phr256blend_auto512", [new("phr256blend_auto512", "Emulation.Option.mednafen_supafaust.supafaust_h_filter.Value.phr256blend_auto512"), new("phr256blend_512", "Emulation.Option.mednafen_supafaust.supafaust_h_filter.Value.phr256blend_512"), new("512_blend", "Emulation.Option.mednafen_supafaust.supafaust_h_filter.Value.512_blend"), new("512", "512"), new("phr256blend", "Emulation.Option.mednafen_supafaust.supafaust_h_filter.Value.phr256blend")]),
        new("supafaust_deinterlacer", "Emulation.Option.mednafen_supafaust.supafaust_deinterlacer", null, "", "bob_offset", "bob_offset", [new("bob_offset", "Emulation.Option.mednafen_supafaust.supafaust_deinterlacer.Value.bob_offset"), new("weave", "Emulation.Option.mednafen_supafaust.supafaust_deinterlacer.Value.weave"), new("blend", "Emulation.Option.mednafen_supafaust.supafaust_deinterlacer.Value.blend")]),
        new("supafaust_slstart", "Emulation.Option.mednafen_supafaust.supafaust_slstart", null, "", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16")]),
        new("supafaust_slend", "Emulation.Option.mednafen_supafaust.supafaust_slend", null, "", "223", "223", [new("223", "223"), new("222", "222"), new("221", "221"), new("220", "220"), new("219", "219"), new("218", "218"), new("217", "217"), new("216", "216"), new("215", "215"), new("214", "214"), new("213", "213"), new("212", "212"), new("211", "211"), new("210", "210"), new("209", "209"), new("208", "208"), new("207", "207")]),
        new("supafaust_slstartp", "Emulation.Option.mednafen_supafaust.supafaust_slstartp", null, "", "0", "0", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24")]),
        new("supafaust_slendp", "Emulation.Option.mednafen_supafaust.supafaust_slendp", null, "", "238", "238", [new("238", "238"), new("237", "237"), new("236", "236"), new("235", "235"), new("234", "234"), new("233", "233"), new("232", "232"), new("231", "231"), new("230", "230"), new("229", "229"), new("228", "228"), new("227", "227"), new("226", "226"), new("225", "225"), new("224", "224"), new("223", "223"), new("222", "222"), new("221", "221"), new("220", "220"), new("219", "219"), new("218", "218"), new("217", "217"), new("216", "216"), new("215", "215"), new("214", "214")]),
        new("supafaust_region", "Emulation.Option.mednafen_supafaust.supafaust_region", null, "", "auto", "auto", [new("auto", "Emulation.Option.mednafen_supafaust.supafaust_region.Value.auto"), new("ntsc", "Emulation.Option.mednafen_supafaust.supafaust_region.Value.ntsc"), new("pal", "Emulation.Option.mednafen_supafaust.supafaust_region.Value.pal"), new("ntsc_lie_auto", "Emulation.Option.mednafen_supafaust.supafaust_region.Value.ntsc_lie_auto"), new("pal_lie_auto", "Emulation.Option.mednafen_supafaust.supafaust_region.Value.pal_lie_auto"), new("ntsc_lie_pal", "Emulation.Option.mednafen_supafaust.supafaust_region.Value.ntsc_lie_pal"), new("pal_lie_ntsc", "Emulation.Option.mednafen_supafaust.supafaust_region.Value.pal_lie_ntsc")]),
        new("supafaust_frame_begin_vblank", "Emulation.Option.mednafen_supafaust.supafaust_frame_begin_vblank", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.mednafen_supafaust.supafaust_frame_begin_vblank.Value.enabled"), new("disabled", "Emulation.Option.mednafen_supafaust.supafaust_frame_begin_vblank.Value.disabled")]),
        new("supafaust_run_ahead", "Emulation.Option.mednafen_supafaust.supafaust_run_ahead", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.mednafen_supafaust.supafaust_run_ahead.Value.disabled"), new("video", "Emulation.Option.mednafen_supafaust.supafaust_run_ahead.Value.video"), new("video+audio", "Emulation.Option.mednafen_supafaust.supafaust_run_ahead.Value.video+audio")]),
        new("supafaust_multitap", "Emulation.Option.mednafen_supafaust.supafaust_multitap", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.mednafen_supafaust.supafaust_multitap.Value.disabled"), new("port1", "Emulation.Option.mednafen_supafaust.supafaust_multitap.Value.port1"), new("port2", "Emulation.Option.mednafen_supafaust.supafaust_multitap.Value.port2"), new("port1+port2", "Emulation.Option.mednafen_supafaust.supafaust_multitap.Value.port1+port2")]),
        new("supafaust_cx4_clock_rate", "Emulation.Option.mednafen_supafaust.supafaust_cx4_clock_rate", null, "", "100", "100", [new("100", "100"), new("125", "125"), new("150", "150"), new("175", "175"), new("200", "200"), new("250", "250"), new("300", "300"), new("400", "400"), new("500", "500")]),
        new("supafaust_superfx_clock_rate", "Emulation.Option.mednafen_supafaust.supafaust_superfx_clock_rate", null, "", "100", "100", [new("100", "100"), new("125", "125"), new("150", "150"), new("175", "175"), new("200", "200"), new("250", "250"), new("300", "300"), new("400", "400"), new("500", "500"), new("95", "95")]),
        new("supafaust_superfx_icache", "Emulation.Option.mednafen_supafaust.supafaust_superfx_icache", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.mednafen_supafaust.supafaust_superfx_icache.Value.disabled"), new("enabled", "Emulation.Option.mednafen_supafaust.supafaust_superfx_icache.Value.enabled")]),
        new("supafaust_audio_rate", "Emulation.Option.mednafen_supafaust.supafaust_audio_rate", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.mednafen_supafaust.supafaust_audio_rate.Value.disabled"), new("44100", "44100"), new("48000", "48000"), new("96000", "96000")]),
        new("supafaust_thread_affinity_emu", "Emulation.Option.mednafen_supafaust.supafaust_thread_affinity_emu", null, "", "0x2", "0x2", [new("0x2", "0x2"), new("0x0", "0x0"), new("0x1", "0x1"), new("0x3", "0x3"), new("0x4", "0x4"), new("0x5", "0x5"), new("0x6", "0x6"), new("0x7", "0x7"), new("0x8", "0x8"), new("0x9", "0x9"), new("0xa", "0xa"), new("0xb", "0xb"), new("0xc", "0xc"), new("0xd", "0xd"), new("0xe", "0xe"), new("0xf", "0xf")]),
        new("supafaust_thread_affinity_ppu", "Emulation.Option.mednafen_supafaust.supafaust_thread_affinity_ppu", null, "", "0x1", "0x1", [new("0x1", "0x1"), new("0x0", "0x0"), new("0x2", "0x2"), new("0x3", "0x3"), new("0x4", "0x4"), new("0x5", "0x5"), new("0x6", "0x6"), new("0x7", "0x7"), new("0x8", "0x8"), new("0x9", "0x9"), new("0xa", "0xa"), new("0xb", "0xb"), new("0xc", "0xc"), new("0xd", "0xd"), new("0xe", "0xe"), new("0xf", "0xf")]),
        new("supafaust_renderer", "Emulation.Option.mednafen_supafaust.supafaust_renderer", null, "", "mt", "mt", [new("mt", "mt"), new("st", "st")])
    ];
}
