using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Sameboy.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("sameboy_model", "Emulation.Option.sameboy.sameboy_model", "Emulation.Option.sameboy.sameboy_model.Help", "system", "Auto", "Auto", [new("Auto", "Emulation.Option.sameboy.sameboy_model.Value.Auto"), new("Auto (SGB)", "Emulation.Option.sameboy.sameboy_model.Value.Auto (SGB)"), new("Game Boy", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy"), new("Game Boy Pocket", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Pocket"), new("Game Boy Color 0", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Color 0"), new("Game Boy Color A", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Color A"), new("Game Boy Color B", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Color B"), new("Game Boy Color C", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Color C"), new("Game Boy Color D", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Color D"), new("Game Boy Color", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Color"), new("Game Boy Advance", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Advance"), new("Game Boy Player", "Emulation.Option.sameboy.sameboy_model.Value.Game Boy Player"), new("Super Game Boy", "Emulation.Option.sameboy.sameboy_model.Value.Super Game Boy"), new("Super Game Boy PAL", "Emulation.Option.sameboy.sameboy_model.Value.Super Game Boy PAL"), new("Super Game Boy 2", "Emulation.Option.sameboy.sameboy_model.Value.Super Game Boy 2")]),
        new("sameboy_auto_sgb_model", "Emulation.Option.sameboy.sameboy_auto_sgb_model", "Emulation.Option.sameboy.sameboy_auto_sgb_model.Help", "system", "Super Game Boy", "Super Game Boy", [new("Super Game Boy", "Emulation.Option.sameboy.sameboy_auto_sgb_model.Value.Super Game Boy"), new("Super Game Boy PAL", "Emulation.Option.sameboy.sameboy_auto_sgb_model.Value.Super Game Boy PAL"), new("Super Game Boy 2", "Emulation.Option.sameboy.sameboy_auto_sgb_model.Value.Super Game Boy 2")]),
        new("sameboy_mono_palette", "Emulation.Option.sameboy.sameboy_mono_palette", "Emulation.Option.sameboy.sameboy_mono_palette.Help", "video", "greyscale", "greyscale", [new("greyscale", "Emulation.Option.sameboy.sameboy_mono_palette.Value.greyscale"), new("lime", "Emulation.Option.sameboy.sameboy_mono_palette.Value.lime"), new("olive", "Emulation.Option.sameboy.sameboy_mono_palette.Value.olive"), new("teal", "Emulation.Option.sameboy.sameboy_mono_palette.Value.teal")]),
        new("sameboy_color_correction_mode", "Emulation.Option.sameboy.sameboy_color_correction_mode", "Emulation.Option.sameboy.sameboy_color_correction_mode.Help", "video", "emulate hardware", "emulate hardware", [new("emulate hardware", "Emulation.Option.sameboy.sameboy_color_correction_mode.Value.emulate hardware"), new("accurate", "Emulation.Option.sameboy.sameboy_color_correction_mode.Value.accurate"), new("preserve brightness", "Emulation.Option.sameboy.sameboy_color_correction_mode.Value.preserve brightness"), new("reduce contrast", "Emulation.Option.sameboy.sameboy_color_correction_mode.Value.reduce contrast"), new("correct curves", "Emulation.Option.sameboy.sameboy_color_correction_mode.Value.correct curves"), new("harsh reality", "Emulation.Option.sameboy.sameboy_color_correction_mode.Value.harsh reality"), new("off", "Emulation.Option.sameboy.sameboy_color_correction_mode.Value.off")]),
        new("sameboy_light_temperature", "Emulation.Option.sameboy.sameboy_light_temperature", "Emulation.Option.sameboy.sameboy_light_temperature.Help", "video", "0", "0", [new("1.0", "Emulation.Option.sameboy.sameboy_light_temperature.Value.1.0"), new("0.9", "1550K"), new("0.8", "2100K"), new("0.7", "2650K"), new("0.6", "3200K"), new("0.5", "3750K"), new("0.4", "4300K"), new("0.3", "4850K"), new("0.2", "5400K"), new("0.1", "5950K"), new("0", "Emulation.Option.sameboy.sameboy_light_temperature.Value.0"), new("-0.1", "7050K"), new("-0.2", "7600K"), new("-0.3", "8150K"), new("-0.4", "8700K"), new("-0.5", "9250K"), new("-0.6", "9800K"), new("-0.7", "10350K"), new("-0.8", "10900K"), new("-0.9", "11450K"), new("-1.0", "Emulation.Option.sameboy.sameboy_light_temperature.Value.-1.0")]),
        new("sameboy_border", "Emulation.Option.sameboy.sameboy_border", "Emulation.Option.sameboy.sameboy_border.Help", "video", "Super Game Boy only", "Super Game Boy only", [new("always", "Emulation.Option.sameboy.sameboy_border.Value.always"), new("Super Game Boy only", "Emulation.Option.sameboy.sameboy_border.Value.Super Game Boy only"), new("never", "Emulation.Option.sameboy.sameboy_border.Value.never")]),
        new("sameboy_high_pass_filter_mode", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode.Help", "audio", "accurate", "accurate", [new("accurate", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode.Value.accurate"), new("remove dc offset", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode.Value.remove dc offset"), new("off", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode.Value.off")]),
        new("sameboy_audio_interference", "Emulation.Option.sameboy.sameboy_audio_interference", "Emulation.Option.sameboy.sameboy_audio_interference.Help", "audio", "0", "0", [new("0", "0%"), new("5", "5%"), new("10", "10%"), new("15", "15%"), new("20", "20%"), new("25", "25%"), new("30", "30%"), new("35", "35%"), new("40", "40%"), new("45", "45%"), new("50", "50%"), new("55", "55%"), new("60", "60%"), new("65", "65%"), new("70", "70%"), new("75", "75%"), new("80", "80%"), new("85", "85%"), new("90", "90%"), new("95", "95%"), new("100", "100%")]),
        new("sameboy_rumble", "Emulation.Option.sameboy.sameboy_rumble", "Emulation.Option.sameboy.sameboy_rumble.Help", "input", "rumble-enabled games", "rumble-enabled games", [new("all games", "Emulation.Option.sameboy.sameboy_rumble.Value.all games"), new("rumble-enabled games", "Emulation.Option.sameboy.sameboy_rumble.Value.rumble-enabled games"), new("never", "Emulation.Option.sameboy.sameboy_rumble.Value.never")]),
        new("sameboy_link", "Emulation.Option.sameboy.sameboy_link", "Emulation.Option.sameboy.sameboy_link.Help", "system", "enabled", "enabled", [new("enabled", "Emulation.Option.sameboy.sameboy_link.Value.enabled"), new("disabled", "Emulation.Option.sameboy.sameboy_link.Value.disabled")]),
        new("sameboy_model_1", "Emulation.Option.sameboy.sameboy_model_1", "Emulation.Option.sameboy.sameboy_model_1.Help", "system", "Auto", "Auto", [new("Auto", "Emulation.Option.sameboy.sameboy_model_1.Value.Auto"), new("Auto (SGB)", "Emulation.Option.sameboy.sameboy_model_1.Value.Auto (SGB)"), new("Game Boy", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy"), new("Game Boy Pocket", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Pocket"), new("Game Boy Color 0", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Color 0"), new("Game Boy Color A", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Color A"), new("Game Boy Color B", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Color B"), new("Game Boy Color C", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Color C"), new("Game Boy Color D", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Color D"), new("Game Boy Color", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Color"), new("Game Boy Advance", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Advance"), new("Game Boy Player", "Emulation.Option.sameboy.sameboy_model_1.Value.Game Boy Player"), new("Super Game Boy", "Emulation.Option.sameboy.sameboy_model_1.Value.Super Game Boy"), new("Super Game Boy PAL", "Emulation.Option.sameboy.sameboy_model_1.Value.Super Game Boy PAL"), new("Super Game Boy 2", "Emulation.Option.sameboy.sameboy_model_1.Value.Super Game Boy 2")]),
        new("sameboy_auto_sgb_model_1", "Emulation.Option.sameboy.sameboy_auto_sgb_model_1", "Emulation.Option.sameboy.sameboy_auto_sgb_model_1.Help", "system", "Super Game Boy", "Super Game Boy", [new("Super Game Boy", "Emulation.Option.sameboy.sameboy_auto_sgb_model_1.Value.Super Game Boy"), new("Super Game Boy PAL", "Emulation.Option.sameboy.sameboy_auto_sgb_model_1.Value.Super Game Boy PAL"), new("Super Game Boy 2", "Emulation.Option.sameboy.sameboy_auto_sgb_model_1.Value.Super Game Boy 2")]),
        new("sameboy_model_2", "Emulation.Option.sameboy.sameboy_model_2", "Emulation.Option.sameboy.sameboy_model_2.Help", "system", "Auto", "Auto", [new("Auto", "Emulation.Option.sameboy.sameboy_model_2.Value.Auto"), new("Auto (SGB)", "Emulation.Option.sameboy.sameboy_model_2.Value.Auto (SGB)"), new("Game Boy", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy"), new("Game Boy Pocket", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Pocket"), new("Game Boy Color 0", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Color 0"), new("Game Boy Color A", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Color A"), new("Game Boy Color B", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Color B"), new("Game Boy Color C", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Color C"), new("Game Boy Color D", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Color D"), new("Game Boy Color", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Color"), new("Game Boy Advance", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Advance"), new("Game Boy Player", "Emulation.Option.sameboy.sameboy_model_2.Value.Game Boy Player"), new("Super Game Boy", "Emulation.Option.sameboy.sameboy_model_2.Value.Super Game Boy"), new("Super Game Boy PAL", "Emulation.Option.sameboy.sameboy_model_2.Value.Super Game Boy PAL"), new("Super Game Boy 2", "Emulation.Option.sameboy.sameboy_model_2.Value.Super Game Boy 2")]),
        new("sameboy_auto_sgb_model_2", "Emulation.Option.sameboy.sameboy_auto_sgb_model_2", "Emulation.Option.sameboy.sameboy_auto_sgb_model_2.Help", "system", "Super Game Boy", "Super Game Boy", [new("Super Game Boy", "Emulation.Option.sameboy.sameboy_auto_sgb_model_2.Value.Super Game Boy"), new("Super Game Boy PAL", "Emulation.Option.sameboy.sameboy_auto_sgb_model_2.Value.Super Game Boy PAL"), new("Super Game Boy 2", "Emulation.Option.sameboy.sameboy_auto_sgb_model_2.Value.Super Game Boy 2")]),
        new("sameboy_screen_layout", "Emulation.Option.sameboy.sameboy_screen_layout", "Emulation.Option.sameboy.sameboy_screen_layout.Help", "video", "top-down", "top-down", [new("top-down", "Emulation.Option.sameboy.sameboy_screen_layout.Value.top-down"), new("left-right", "Emulation.Option.sameboy.sameboy_screen_layout.Value.left-right")]),
        new("sameboy_mono_palette_1", "Emulation.Option.sameboy.sameboy_mono_palette_1", "Emulation.Option.sameboy.sameboy_mono_palette_1.Help", "video", "greyscale", "greyscale", [new("greyscale", "Emulation.Option.sameboy.sameboy_mono_palette_1.Value.greyscale"), new("lime", "Emulation.Option.sameboy.sameboy_mono_palette_1.Value.lime"), new("olive", "Emulation.Option.sameboy.sameboy_mono_palette_1.Value.olive"), new("teal", "Emulation.Option.sameboy.sameboy_mono_palette_1.Value.teal")]),
        new("sameboy_mono_palette_2", "Emulation.Option.sameboy.sameboy_mono_palette_2", "Emulation.Option.sameboy.sameboy_mono_palette_2.Help", "video", "greyscale", "greyscale", [new("greyscale", "Emulation.Option.sameboy.sameboy_mono_palette_2.Value.greyscale"), new("lime", "Emulation.Option.sameboy.sameboy_mono_palette_2.Value.lime"), new("olive", "Emulation.Option.sameboy.sameboy_mono_palette_2.Value.olive"), new("teal", "Emulation.Option.sameboy.sameboy_mono_palette_2.Value.teal")]),
        new("sameboy_color_correction_mode_1", "Emulation.Option.sameboy.sameboy_color_correction_mode_1", "Emulation.Option.sameboy.sameboy_color_correction_mode_1.Help", "video", "emulate hardware", "emulate hardware", [new("emulate hardware", "Emulation.Option.sameboy.sameboy_color_correction_mode_1.Value.emulate hardware"), new("accurate", "Emulation.Option.sameboy.sameboy_color_correction_mode_1.Value.accurate"), new("preserve brightness", "Emulation.Option.sameboy.sameboy_color_correction_mode_1.Value.preserve brightness"), new("reduce contrast", "Emulation.Option.sameboy.sameboy_color_correction_mode_1.Value.reduce contrast"), new("correct curves", "Emulation.Option.sameboy.sameboy_color_correction_mode_1.Value.correct curves"), new("harsh reality", "Emulation.Option.sameboy.sameboy_color_correction_mode_1.Value.harsh reality"), new("off", "Emulation.Option.sameboy.sameboy_color_correction_mode_1.Value.off")]),
        new("sameboy_color_correction_mode_2", "Emulation.Option.sameboy.sameboy_color_correction_mode_2", "Emulation.Option.sameboy.sameboy_color_correction_mode_2.Help", "video", "emulate hardware", "emulate hardware", [new("emulate hardware", "Emulation.Option.sameboy.sameboy_color_correction_mode_2.Value.emulate hardware"), new("accurate", "Emulation.Option.sameboy.sameboy_color_correction_mode_2.Value.accurate"), new("preserve brightness", "Emulation.Option.sameboy.sameboy_color_correction_mode_2.Value.preserve brightness"), new("reduce contrast", "Emulation.Option.sameboy.sameboy_color_correction_mode_2.Value.reduce contrast"), new("correct curves", "Emulation.Option.sameboy.sameboy_color_correction_mode_2.Value.correct curves"), new("harsh reality", "Emulation.Option.sameboy.sameboy_color_correction_mode_2.Value.harsh reality"), new("off", "Emulation.Option.sameboy.sameboy_color_correction_mode_2.Value.off")]),
        new("sameboy_light_temperature_1", "Emulation.Option.sameboy.sameboy_light_temperature_1", "Emulation.Option.sameboy.sameboy_light_temperature_1.Help", "video", "0", "0", [new("1.0", "Emulation.Option.sameboy.sameboy_light_temperature_1.Value.1.0"), new("0.9", "1550K"), new("0.8", "2100K"), new("0.7", "2650K"), new("0.6", "3200K"), new("0.5", "3750K"), new("0.4", "4300K"), new("0.3", "4850K"), new("0.2", "5400K"), new("0.1", "5950K"), new("0", "Emulation.Option.sameboy.sameboy_light_temperature_1.Value.0"), new("-0.1", "7050K"), new("-0.2", "7600K"), new("-0.3", "8150K"), new("-0.4", "8700K"), new("-0.5", "9250K"), new("-0.6", "9800K"), new("-0.7", "10350K"), new("-0.8", "10900K"), new("-0.9", "11450K"), new("-1.0", "Emulation.Option.sameboy.sameboy_light_temperature_1.Value.-1.0")]),
        new("sameboy_light_temperature_2", "Emulation.Option.sameboy.sameboy_light_temperature_2", "Emulation.Option.sameboy.sameboy_light_temperature_2.Help", "video", "0", "0", [new("1.0", "Emulation.Option.sameboy.sameboy_light_temperature_2.Value.1.0"), new("0.9", "1550K"), new("0.8", "2100K"), new("0.7", "2650K"), new("0.6", "3200K"), new("0.5", "3750K"), new("0.4", "4300K"), new("0.3", "4850K"), new("0.2", "5400K"), new("0.1", "5950K"), new("0", "Emulation.Option.sameboy.sameboy_light_temperature_2.Value.0"), new("-0.1", "7050K"), new("-0.2", "7600K"), new("-0.3", "8150K"), new("-0.4", "8700K"), new("-0.5", "9250K"), new("-0.6", "9800K"), new("-0.7", "10350K"), new("-0.8", "10900K"), new("-0.9", "11450K"), new("-1.0", "Emulation.Option.sameboy.sameboy_light_temperature_2.Value.-1.0")]),
        new("sameboy_audio_output", "Emulation.Option.sameboy.sameboy_audio_output", "Emulation.Option.sameboy.sameboy_audio_output.Help", "audio", "Game Boy #1", "Game Boy #1", [new("Game Boy #1", "Emulation.Option.sameboy.sameboy_audio_output.Value.Game Boy #1"), new("Game Boy #2", "Emulation.Option.sameboy.sameboy_audio_output.Value.Game Boy #2"), new("Mix Both", "Emulation.Option.sameboy.sameboy_audio_output.Value.Mix Both")]),
        new("sameboy_high_pass_filter_mode_1", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_1", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_1.Help", "audio", "accurate", "accurate", [new("accurate", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_1.Value.accurate"), new("remove dc offset", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_1.Value.remove dc offset"), new("off", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_1.Value.off")]),
        new("sameboy_high_pass_filter_mode_2", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_2", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_2.Help", "audio", "accurate", "accurate", [new("accurate", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_2.Value.accurate"), new("remove dc offset", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_2.Value.remove dc offset"), new("off", "Emulation.Option.sameboy.sameboy_high_pass_filter_mode_2.Value.off")]),
        new("sameboy_audio_interference_1", "Emulation.Option.sameboy.sameboy_audio_interference_1", "Emulation.Option.sameboy.sameboy_audio_interference_1.Help", "audio", "0", "0", [new("0", "0%"), new("5", "5%"), new("10", "10%"), new("15", "15%"), new("20", "20%"), new("25", "25%"), new("30", "30%"), new("35", "35%"), new("40", "40%"), new("45", "45%"), new("50", "50%"), new("55", "55%"), new("60", "60%"), new("65", "65%"), new("70", "70%"), new("75", "75%"), new("80", "80%"), new("85", "85%"), new("90", "90%"), new("95", "95%"), new("100", "100%")]),
        new("sameboy_audio_interference_2", "Emulation.Option.sameboy.sameboy_audio_interference_2", "Emulation.Option.sameboy.sameboy_audio_interference_2.Help", "audio", "0", "0", [new("0", "0%"), new("5", "5%"), new("10", "10%"), new("15", "15%"), new("20", "20%"), new("25", "25%"), new("30", "30%"), new("35", "35%"), new("40", "40%"), new("45", "45%"), new("50", "50%"), new("55", "55%"), new("60", "60%"), new("65", "65%"), new("70", "70%"), new("75", "75%"), new("80", "80%"), new("85", "85%"), new("90", "90%"), new("95", "95%"), new("100", "100%")]),
        new("sameboy_rumble_1", "Emulation.Option.sameboy.sameboy_rumble_1", "Emulation.Option.sameboy.sameboy_rumble_1.Help", "input", "rumble-enabled games", "rumble-enabled games", [new("all games", "Emulation.Option.sameboy.sameboy_rumble_1.Value.all games"), new("rumble-enabled games", "Emulation.Option.sameboy.sameboy_rumble_1.Value.rumble-enabled games"), new("never", "Emulation.Option.sameboy.sameboy_rumble_1.Value.never")]),
        new("sameboy_rumble_2", "Emulation.Option.sameboy.sameboy_rumble_2", "Emulation.Option.sameboy.sameboy_rumble_2.Help", "input", "rumble-enabled games", "rumble-enabled games", [new("all games", "Emulation.Option.sameboy.sameboy_rumble_2.Value.all games"), new("rumble-enabled games", "Emulation.Option.sameboy.sameboy_rumble_2.Value.rumble-enabled games"), new("never", "Emulation.Option.sameboy.sameboy_rumble_2.Value.never")]),
        new("sameboy_rtc", "Emulation.Option.sameboy.sameboy_rtc", "Emulation.Option.sameboy.sameboy_rtc.Help", "system", "sync to system clock", "sync to system clock", [new("sync to system clock", "Emulation.Option.sameboy.sameboy_rtc.Value.sync to system clock"), new("accurate", "Emulation.Option.sameboy.sameboy_rtc.Value.accurate")])
    ];
}
