using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Mesen2.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<string> UnconfiguredSystemOptionPrefixes { get; } =
        ["mesen_pce_", "mesen_sms_", "mesen_ws_", "mesen_gba_"];
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("mesen_region", "Emulation.Option.mesen2.mesen_region", "Emulation.Option.mesen2.mesen_region.Help", "system", "Auto", "Auto", [new("Auto", "Emulation.Option.mesen2.mesen_region.Value.Auto"), new("NTSC", "Emulation.Option.mesen2.mesen_region.Value.NTSC"), new("PAL", "Emulation.Option.mesen2.mesen_region.Value.PAL"), new("Dendy", "Emulation.Option.mesen2.mesen_region.Value.Dendy")], Tab: EmulationMachineTab.General, MachineIds: OptionMachineConstants.Nes),
        new("mesen_ramstate", "Emulation.Option.mesen2.mesen_ramstate", "Emulation.Option.mesen2.mesen_ramstate.Help", "system", "All 0s (Default)", "All 0s (Default)", [new("All 0s (Default)", "Emulation.Option.mesen2.mesen_ramstate.Value.All 0s (Default)"), new("All 1s", "Emulation.Option.mesen2.mesen_ramstate.Value.All 1s"), new("Random Values", "Emulation.Option.mesen2.mesen_ramstate.Value.Random Values")], Tab: EmulationMachineTab.Ram, MachineIds: OptionMachineConstants.Nes),
        new("mesen_overclock", "Emulation.Option.mesen2.mesen_overclock", "Emulation.Option.mesen2.mesen_overclock.Help", "system", "None", "None", [new("None", "Emulation.Option.mesen2.mesen_overclock.Value.None"), new("Low", "Emulation.Option.mesen2.mesen_overclock.Value.Low"), new("Medium", "Emulation.Option.mesen2.mesen_overclock.Value.Medium"), new("High", "Emulation.Option.mesen2.mesen_overclock.Value.High"), new("Very High", "Emulation.Option.mesen2.mesen_overclock.Value.Very High")], Tab: EmulationMachineTab.Cpu, MachineIds: OptionMachineConstants.Nes),
        new("mesen_overclock_type", "Emulation.Option.mesen2.mesen_overclock_type", "Emulation.Option.mesen2.mesen_overclock_type.Help", "system", "Before NMI (Recommended)", "Before NMI (Recommended)", [new("Before NMI (Recommended)", "Emulation.Option.mesen2.mesen_overclock_type.Value.Before NMI (Recommended)"), new("After NMI", "Emulation.Option.mesen2.mesen_overclock_type.Value.After NMI")], Tab: EmulationMachineTab.Cpu, MachineIds: OptionMachineConstants.Nes),
        new("mesen_fdsautoinsertdisk", "Emulation.Option.mesen2.mesen_fdsautoinsertdisk", "Emulation.Option.mesen2.mesen_fdsautoinsertdisk.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_fdsautoinsertdisk.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Storage, MachineIds: OptionMachineConstants.FamicomDisk),
        new("mesen_fdsfastforwardload", "Emulation.Option.mesen2.mesen_fdsfastforwardload", "Emulation.Option.mesen2.mesen_fdsfastforwardload.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_fdsfastforwardload.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Storage, MachineIds: OptionMachineConstants.FamicomDisk),
        new("mesen_allow_invalid_input", "Emulation.Option.mesen2.mesen_allow_invalid_input", "Emulation.Option.mesen2.mesen_allow_invalid_input.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_allow_invalid_input.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Controllers, MachineIds: OptionMachineConstants.Nes),
        new("mesen_randomize_mapper_power_on_state", "Emulation.Option.mesen2.mesen_randomize_mapper_power_on_state", "Emulation.Option.mesen2.mesen_randomize_mapper_power_on_state.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_randomize_mapper_power_on_state.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Ram, MachineIds: OptionMachineConstants.Nes),
        new("mesen_randomize_cpu_ppu_alignment", "Emulation.Option.mesen2.mesen_randomize_cpu_ppu_alignment", "Emulation.Option.mesen2.mesen_randomize_cpu_ppu_alignment.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_randomize_cpu_ppu_alignment.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Cpu, MachineIds: OptionMachineConstants.Nes),
        new("mesen_palette", "Emulation.Option.mesen2.mesen_palette", "Emulation.Option.mesen2.mesen_palette.Help", "video", "Default", "Default", [new("Default", "Emulation.Option.mesen2.mesen_palette.Value.Default"), new("Composite Direct (by FirebrandX)", "Emulation.Option.mesen2.mesen_palette.Value.Composite Direct (by FirebrandX)"), new("Nes Classic", "Emulation.Option.mesen2.mesen_palette.Value.Nes Classic"), new("Nestopia (RGB)", "Emulation.Option.mesen2.mesen_palette.Value.Nestopia (RGB)"), new("Original Hardware (by FirebrandX)", "Emulation.Option.mesen2.mesen_palette.Value.Original Hardware (by FirebrandX)"), new("PVM Style (by FirebrandX)", "Emulation.Option.mesen2.mesen_palette.Value.PVM Style (by FirebrandX)"), new("Sony CXA2025AS", "Emulation.Option.mesen2.mesen_palette.Value.Sony CXA2025AS"), new("Unsaturated v6 (by FirebrandX)", "Emulation.Option.mesen2.mesen_palette.Value.Unsaturated v6 (by FirebrandX)"), new("YUV v3 (by FirebrandX)", "Emulation.Option.mesen2.mesen_palette.Value.YUV v3 (by FirebrandX)"), new("Wavebeam (by nakedarthur)", "Emulation.Option.mesen2.mesen_palette.Value.Wavebeam (by nakedarthur)"), new("Custom", "Emulation.Option.mesen2.mesen_palette.Value.Custom")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Nes),
        new("mesen_ntsc_filter", "Emulation.Option.mesen2.mesen_ntsc_filter", "Emulation.Option.mesen2.mesen_ntsc_filter.Help", "video", "Disabled", "Disabled", [new("Disabled", "Emulation.Option.mesen2.mesen_ntsc_filter.Value.Disabled"), new("Composite (Blargg)", "Emulation.Option.mesen2.mesen_ntsc_filter.Value.Composite (Blargg)")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Nes),
        new("mesen_enable_pal_borders", "Emulation.Option.mesen2.mesen_enable_pal_borders", "Emulation.Option.mesen2.mesen_enable_pal_borders.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_enable_pal_borders.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Nes),
        new("mesen_fake_stereo", "Emulation.Option.mesen2.mesen_fake_stereo", "Emulation.Option.mesen2.mesen_fake_stereo.Help", "audio", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_fake_stereo.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Audio, MachineIds: OptionMachineConstants.Nes),
        new("mesen_mute_triangle_ultrasonic", "Emulation.Option.mesen2.mesen_mute_triangle_ultrasonic", "Emulation.Option.mesen2.mesen_mute_triangle_ultrasonic.Help", "audio", "enabled", "enabled", [new("enabled", "Emulation.Option.Common.Value.Enabled"), new("disabled", "Emulation.Option.mesen2.mesen_mute_triangle_ultrasonic.Value.disabled")], Tab: EmulationMachineTab.Audio, MachineIds: OptionMachineConstants.Nes),
        new("mesen_reduce_dmc_popping", "Emulation.Option.mesen2.mesen_reduce_dmc_popping", "Emulation.Option.mesen2.mesen_reduce_dmc_popping.Help", "audio", "enabled", "enabled", [new("enabled", "Emulation.Option.Common.Value.Enabled"), new("disabled", "Emulation.Option.mesen2.mesen_reduce_dmc_popping.Value.disabled")], Tab: EmulationMachineTab.Audio, MachineIds: OptionMachineConstants.Nes),
        new("mesen_swap_duty_cycle", "Emulation.Option.mesen2.mesen_swap_duty_cycle", "Emulation.Option.mesen2.mesen_swap_duty_cycle.Help", "audio", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_swap_duty_cycle.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Audio, MachineIds: OptionMachineConstants.Nes),
        new("mesen_disable_noise_mode_flag", "Emulation.Option.mesen2.mesen_disable_noise_mode_flag", "Emulation.Option.mesen2.mesen_disable_noise_mode_flag.Help", "audio", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_disable_noise_mode_flag.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Audio, MachineIds: OptionMachineConstants.Nes),
        new("mesen_audio_sample_rate", "Emulation.Option.mesen2.mesen_audio_sample_rate", "Emulation.Option.mesen2.mesen_audio_sample_rate.Help", "audio", "44100", "44100", [new("48000", "48000 Hz"), new("96000", "96000 Hz"), new("11025", "11025 Hz"), new("22050", "22050 Hz"), new("44100", "44100 Hz")], Tab: EmulationMachineTab.Audio, MachineIds: OptionMachineConstants.Nes),
        new("mesen_snes_color_correction", "Emulation.Option.mesen2.mesen_snes_color_correction", "Emulation.Option.mesen2.mesen_snes_color_correction.Help", "video", "None", "None", [new("None", "Emulation.Option.mesen2.mesen_snes_color_correction.Value.None"), new("NTSC Black Level", "Emulation.Option.mesen2.mesen_snes_color_correction.Value.NTSC Black Level"), new("Deep Black Boost", "Emulation.Option.mesen2.mesen_snes_color_correction.Value.Deep Black Boost")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_high_res_blend_mode", "Emulation.Option.mesen2.mesen_snes_high_res_blend_mode", "Emulation.Option.mesen2.mesen_snes_high_res_blend_mode.Help", "video", "None", "None", [new("None", "Emulation.Option.mesen2.mesen_snes_high_res_blend_mode.Value.None"), new("Blend All", "Emulation.Option.mesen2.mesen_snes_high_res_blend_mode.Value.Blend All"), new("Blend Even/Odd", "Emulation.Option.mesen2.mesen_snes_high_res_blend_mode.Value.Blend Even/Odd")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_deinterlace_mode", "Emulation.Option.mesen2.mesen_snes_deinterlace_mode", "Emulation.Option.mesen2.mesen_snes_deinterlace_mode.Help", "video", "Weave", "Weave", [new("Weave", "Emulation.Option.mesen2.mesen_snes_deinterlace_mode.Value.Weave"), new("Bob Blend", "Emulation.Option.mesen2.mesen_snes_deinterlace_mode.Value.Bob Blend"), new("Bob", "Emulation.Option.mesen2.mesen_snes_deinterlace_mode.Value.Bob"), new("Current Field", "Emulation.Option.mesen2.mesen_snes_deinterlace_mode.Value.Current Field")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_hide_bg_layer_1", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_1", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_1.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_1.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_hide_bg_layer_2", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_2", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_2.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_2.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_hide_bg_layer_3", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_3", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_3.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_3.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_hide_bg_layer_4", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_4", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_4.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_hide_bg_layer_4.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_hide_sprites", "Emulation.Option.mesen2.mesen_snes_hide_sprites", "Emulation.Option.mesen2.mesen_snes_hide_sprites.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_hide_sprites.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_remove_sprite_limit", "Emulation.Option.mesen2.mesen_snes_remove_sprite_limit", "Emulation.Option.mesen2.mesen_snes_remove_sprite_limit.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_remove_sprite_limit.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_force_fixed_resolution", "Emulation.Option.mesen2.mesen_snes_force_fixed_resolution", "Emulation.Option.mesen2.mesen_snes_force_fixed_resolution.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_force_fixed_resolution.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_disable_frame_skipping", "Emulation.Option.mesen2.mesen_snes_disable_frame_skipping", "Emulation.Option.mesen2.mesen_snes_disable_frame_skipping.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_disable_frame_skipping.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_enable_strict_board_mappings", "Emulation.Option.mesen2.mesen_snes_enable_strict_board_mappings", "Emulation.Option.mesen2.mesen_snes_enable_strict_board_mappings.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_enable_strict_board_mappings.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.General, MachineIds: OptionMachineConstants.Snes),
        new("mesen_snes_randomize_power_on_state", "Emulation.Option.mesen2.mesen_snes_randomize_power_on_state", "Emulation.Option.mesen2.mesen_snes_randomize_power_on_state.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_snes_randomize_power_on_state.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Ram, MachineIds: OptionMachineConstants.Snes),
        new("mesen_gameboy_model", "Emulation.Option.mesen2.mesen_gameboy_model", "Emulation.Option.mesen2.mesen_gameboy_model.Help", "system", "Auto (GBC)", "Auto (GBC)", [new("Auto (Best)", "Emulation.Option.mesen2.mesen_gameboy_model.Value.Auto (Best)"), new("Auto (GBC)", "Emulation.Option.mesen2.mesen_gameboy_model.Value.Auto (GBC)"), new("Auto (SGB)", "Emulation.Option.mesen2.mesen_gameboy_model.Value.Auto (SGB)"), new("Auto (GB)", "Emulation.Option.mesen2.mesen_gameboy_model.Value.Auto (GB)"), new("Game Boy", "Emulation.Option.mesen2.mesen_gameboy_model.Value.Game Boy"), new("Game Boy Color", "Emulation.Option.mesen2.mesen_gameboy_model.Value.Game Boy Color"), new("Super Game Boy", "Emulation.Option.mesen2.mesen_gameboy_model.Value.Super Game Boy")], Tab: EmulationMachineTab.General, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen_gameboy_blend_frames", "Emulation.Option.mesen2.mesen_gameboy_blend_frames", "Emulation.Option.mesen2.mesen_gameboy_blend_frames.Help", "video", "enabled", "enabled", [new("enabled", "Emulation.Option.Common.Value.Enabled"), new("disabled", "Emulation.Option.mesen2.mesen_gameboy_blend_frames.Value.disabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen_gameboy_adjust_colors", "Emulation.Option.mesen2.mesen_gameboy_adjust_colors", "Emulation.Option.mesen2.mesen_gameboy_adjust_colors.Help", "video", "enabled", "enabled", [new("enabled", "Emulation.Option.Common.Value.Enabled"), new("disabled", "Emulation.Option.mesen2.mesen_gameboy_adjust_colors.Value.disabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen_gameboy_disable_background", "Emulation.Option.mesen2.mesen_gameboy_disable_background", "Emulation.Option.mesen2.mesen_gameboy_disable_background.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_gameboy_disable_background.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen_gameboy_disable_sprites", "Emulation.Option.mesen2.mesen_gameboy_disable_sprites", "Emulation.Option.mesen2.mesen_gameboy_disable_sprites.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_gameboy_disable_sprites.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen_gameboy_remove_sprite_limit", "Emulation.Option.mesen2.mesen_gameboy_remove_sprite_limit", "Emulation.Option.mesen2.mesen_gameboy_remove_sprite_limit.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_gameboy_remove_sprite_limit.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen_gameboy_hide_sgb_borders", "Emulation.Option.mesen2.mesen_gameboy_hide_sgb_borders", "Emulation.Option.mesen2.mesen_gameboy_hide_sgb_borders.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_gameboy_hide_sgb_borders.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen_controllerturbospeed", "Emulation.Option.mesen2.mesen_controllerturbospeed", "Emulation.Option.mesen2.mesen_controllerturbospeed.Help", "input", "Normal", "Normal", [new("Fast", "Emulation.Option.mesen2.mesen_controllerturbospeed.Value.Fast"), new("Very Fast", "Emulation.Option.mesen2.mesen_controllerturbospeed.Value.Very Fast"), new("Disabled", "Emulation.Option.mesen2.mesen_controllerturbospeed.Value.Disabled"), new("Slow", "Emulation.Option.mesen2.mesen_controllerturbospeed.Value.Slow"), new("Normal", "Emulation.Option.mesen2.mesen_controllerturbospeed.Value.Normal")], Tab: EmulationMachineTab.Controllers),
        new("mesen_sprites_enabled", "Emulation.Option.mesen2.mesen_sprites_enabled", "Emulation.Option.mesen2.mesen_sprites_enabled.Help", "enhancements", "enabled", "enabled", [new("enabled", "Emulation.Option.Common.Value.Enabled"), new("disabled", "Emulation.Option.mesen2.mesen_sprites_enabled.Value.disabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Nes),
        new("mesen_background_enabled", "Emulation.Option.mesen2.mesen_background_enabled", "Emulation.Option.mesen2.mesen_background_enabled.Help", "enhancements", "enabled", "enabled", [new("enabled", "Emulation.Option.Common.Value.Enabled"), new("disabled", "Emulation.Option.mesen2.mesen_background_enabled.Value.disabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Nes),
        new("mesen_disable_game_genie_bus_conflicts", "Emulation.Option.mesen2.mesen_disable_game_genie_bus_conflicts", "Emulation.Option.mesen2.mesen_disable_game_genie_bus_conflicts.Help", "enhancements", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen2.mesen_disable_game_genie_bus_conflicts.Value.disabled"), new("enabled", "Emulation.Option.Common.Value.Enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Nes),
        new("mesen_sprite_limit", "Emulation.Option.mesen2.mesen_sprite_limit", "Emulation.Option.mesen2.mesen_sprite_limit.Help", "enhancements", "normal", "normal", [new("normal", "Emulation.Option.mesen2.mesen_sprite_limit.Value.normal"), new("adaptive", "Emulation.Option.mesen2.mesen_sprite_limit.Value.adaptive"), new("off", "Emulation.Option.mesen2.mesen_sprite_limit.Value.off")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Nes)
    ];
}
