using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Snes9x.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("snes9x_region", "Emulation.Option.snes9x.snes9x_region", "Emulation.Option.snes9x.snes9x_region.Help", "", "auto", "auto", [new("auto", "Emulation.Option.snes9x.snes9x_region.Value.auto"), new("ntsc", "Emulation.Option.snes9x.snes9x_region.Value.ntsc"), new("pal", "Emulation.Option.snes9x.snes9x_region.Value.pal")]),
        new("snes9x_aspect", "Emulation.Option.snes9x.snes9x_aspect", "Emulation.Option.snes9x.snes9x_aspect.Help", "", "4:3", "4:3", [new("4:3", "4:3"), new("4:3 scaled", "Emulation.Option.snes9x.snes9x_aspect.Value.4:3 scaled"), new("uncorrected", "Emulation.Option.snes9x.snes9x_aspect.Value.uncorrected"), new("auto", "Emulation.Option.snes9x.snes9x_aspect.Value.auto"), new("ntsc", "Emulation.Option.snes9x.snes9x_aspect.Value.ntsc"), new("pal", "Emulation.Option.snes9x.snes9x_aspect.Value.pal")]),
        new("snes9x_overscan", "Emulation.Option.snes9x.snes9x_overscan", "Emulation.Option.snes9x.snes9x_overscan.Help", "", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_overscan.Value.enabled"), new("12_pixels", "Emulation.Option.snes9x.snes9x_overscan.Value.12_pixels"), new("16_pixels", "Emulation.Option.snes9x.snes9x_overscan.Value.16_pixels"), new("auto", "Emulation.Option.snes9x.snes9x_overscan.Value.auto"), new("disabled", "Emulation.Option.snes9x.snes9x_overscan.Value.disabled")]),
        new("snes9x_mode7_hires", "Emulation.Option.snes9x.snes9x_mode7_hires", "Emulation.Option.snes9x.snes9x_mode7_hires.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_mode7_hires.Value.disabled"), new("2x", "2x"), new("4x", "4x"), new("2x_hv", "2x (H+V)"), new("4x_hv", "4x (H+V)")]),
        new("snes9x_mode7_hires_bilinear", "Emulation.Option.snes9x.snes9x_mode7_hires_bilinear", "Emulation.Option.snes9x.snes9x_mode7_hires_bilinear.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_mode7_hires_bilinear.Value.disabled"), new("stable", "Emulation.Option.snes9x.snes9x_mode7_hires_bilinear.Value.stable"), new("smooth", "Emulation.Option.snes9x.snes9x_mode7_hires_bilinear.Value.smooth")]),
        new("snes9x_hires_blend", "Emulation.Option.snes9x.snes9x_hires_blend", "Emulation.Option.snes9x.snes9x_hires_blend.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_hires_blend.Value.disabled"), new("merge", "Emulation.Option.snes9x.snes9x_hires_blend.Value.merge"), new("blur", "Emulation.Option.snes9x.snes9x_hires_blend.Value.blur")]),
        new("snes9x_blargg", "Emulation.Option.snes9x.snes9x_blargg", "Emulation.Option.snes9x.snes9x_blargg.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_blargg.Value.disabled"), new("monochrome", "Emulation.Option.snes9x.snes9x_blargg.Value.monochrome"), new("rf", "RF"), new("composite", "Emulation.Option.snes9x.snes9x_blargg.Value.composite"), new("s-video", "Emulation.Option.snes9x.snes9x_blargg.Value.s-video"), new("rgb", "Emulation.Option.snes9x.snes9x_blargg.Value.rgb")]),
        new("snes9x_audio_interpolation", "Emulation.Option.snes9x.snes9x_audio_interpolation", "Emulation.Option.snes9x.snes9x_audio_interpolation.Help", "", "gaussian", "gaussian", [new("gaussian", "Emulation.Option.snes9x.snes9x_audio_interpolation.Value.gaussian"), new("cubic", "Emulation.Option.snes9x.snes9x_audio_interpolation.Value.cubic"), new("sinc", "Emulation.Option.snes9x.snes9x_audio_interpolation.Value.sinc"), new("none", "Emulation.Option.snes9x.snes9x_audio_interpolation.Value.none"), new("linear", "Emulation.Option.snes9x.snes9x_audio_interpolation.Value.linear")]),
        new("snes9x_up_down_allowed", "Emulation.Option.snes9x.snes9x_up_down_allowed", "Emulation.Option.snes9x.snes9x_up_down_allowed.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_up_down_allowed.Value.disabled"), new("enabled", "Emulation.Option.snes9x.snes9x_up_down_allowed.Value.enabled")]),
        new("snes9x_overclock_superfx", "Emulation.Option.snes9x.snes9x_overclock_superfx", "Emulation.Option.snes9x.snes9x_overclock_superfx.Help", "hacks", "100%", "100%", [new("50%", "50%"), new("60%", "60%"), new("70%", "70%"), new("80%", "80%"), new("90%", "90%"), new("100%", "100%"), new("150%", "150%"), new("200%", "200%"), new("250%", "250%"), new("300%", "300%"), new("350%", "350%"), new("400%", "400%"), new("450%", "450%"), new("500%", "500%")]),
        new("snes9x_superfx_timing", "Emulation.Option.snes9x.snes9x_superfx_timing", "Emulation.Option.snes9x.snes9x_superfx_timing.Help", "hacks", "compat", "compat", [new("compat", "Emulation.Option.snes9x.snes9x_superfx_timing.Value.compat"), new("hardware", "Emulation.Option.snes9x.snes9x_superfx_timing.Value.hardware")]),
        new("snes9x_overclock_cycles", "Emulation.Option.snes9x.snes9x_overclock_cycles", "Emulation.Option.snes9x.snes9x_overclock_cycles.Help", "hacks", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_overclock_cycles.Value.disabled"), new("light", "Emulation.Option.snes9x.snes9x_overclock_cycles.Value.light"), new("compatible", "Emulation.Option.snes9x.snes9x_overclock_cycles.Value.compatible"), new("max", "Emulation.Option.snes9x.snes9x_overclock_cycles.Value.max")]),
        new("snes9x_reduce_sprite_flicker", "Emulation.Option.snes9x.snes9x_reduce_sprite_flicker", "Emulation.Option.snes9x.snes9x_reduce_sprite_flicker.Help", "hacks", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_reduce_sprite_flicker.Value.disabled"), new("enabled", "Emulation.Option.snes9x.snes9x_reduce_sprite_flicker.Value.enabled")]),
        new("snes9x_randomize_memory", "Emulation.Option.snes9x.snes9x_randomize_memory", "Emulation.Option.snes9x.snes9x_randomize_memory.Help", "hacks", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_randomize_memory.Value.disabled"), new("enabled", "Emulation.Option.snes9x.snes9x_randomize_memory.Value.enabled")]),
        new("snes9x_block_invalid_vram_access", "Emulation.Option.snes9x.snes9x_block_invalid_vram_access", "Emulation.Option.snes9x.snes9x_block_invalid_vram_access.Help", "hacks", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_block_invalid_vram_access.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_block_invalid_vram_access.Value.disabled")]),
        new("snes9x_echo_buffer_hack", "Emulation.Option.snes9x.snes9x_echo_buffer_hack", "Emulation.Option.snes9x.snes9x_echo_buffer_hack.Help", "hacks", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_echo_buffer_hack.Value.disabled"), new("enabled", "Emulation.Option.snes9x.snes9x_echo_buffer_hack.Value.enabled")]),
        new("snes9x_show_lightgun_settings", "Emulation.Option.snes9x.snes9x_show_lightgun_settings", "Emulation.Option.snes9x.snes9x_show_lightgun_settings.Help", "", "disabled", "disabled", [new("enabled", "Emulation.Option.snes9x.snes9x_show_lightgun_settings.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_show_lightgun_settings.Value.disabled")]),
        new("snes9x_lightgun_mode", "Emulation.Option.snes9x.snes9x_lightgun_mode", "Emulation.Option.snes9x.snes9x_lightgun_mode.Help", "lightgun", "Lightgun", "Lightgun", [new("Lightgun", "Emulation.Option.snes9x.snes9x_lightgun_mode.Value.Lightgun"), new("Touchscreen", "Emulation.Option.snes9x.snes9x_lightgun_mode.Value.Touchscreen")]),
        new("snes9x_superscope_reverse_buttons", "Emulation.Option.snes9x.snes9x_superscope_reverse_buttons", "Emulation.Option.snes9x.snes9x_superscope_reverse_buttons.Help", "lightgun", "disabled", "disabled", [new("disabled", "Emulation.Option.snes9x.snes9x_superscope_reverse_buttons.Value.disabled"), new("enabled", "Emulation.Option.snes9x.snes9x_superscope_reverse_buttons.Value.enabled")]),
        new("snes9x_superscope_crosshair", "Emulation.Option.snes9x.snes9x_superscope_crosshair", "Emulation.Option.snes9x.snes9x_superscope_crosshair.Help", "lightgun", "2", "2", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16")]),
        new("snes9x_superscope_color", "Emulation.Option.snes9x.snes9x_superscope_color", "Emulation.Option.snes9x.snes9x_superscope_color.Help", "lightgun", "White", "White", [new("White", "Emulation.Option.snes9x.snes9x_superscope_color.Value.White"), new("White (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.White (blend)"), new("Red", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Red"), new("Red (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Red (blend)"), new("Orange", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Orange"), new("Orange (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Orange (blend)"), new("Yellow", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Yellow"), new("Yellow (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Yellow (blend)"), new("Green", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Green"), new("Green (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Green (blend)"), new("Cyan", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Cyan"), new("Cyan (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Cyan (blend)"), new("Sky", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Sky"), new("Sky (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Sky (blend)"), new("Blue", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Blue"), new("Blue (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Blue (blend)"), new("Violet", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Violet"), new("Violet (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Violet (blend)"), new("Pink", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Pink"), new("Pink (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Pink (blend)"), new("Purple", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Purple"), new("Purple (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Purple (blend)"), new("Black", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Black"), new("Black (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.Black (blend)"), new("25% Grey", "Emulation.Option.snes9x.snes9x_superscope_color.Value.25% Grey"), new("25% Grey (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.25% Grey (blend)"), new("50% Grey", "Emulation.Option.snes9x.snes9x_superscope_color.Value.50% Grey"), new("50% Grey (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.50% Grey (blend)"), new("75% Grey", "Emulation.Option.snes9x.snes9x_superscope_color.Value.75% Grey"), new("75% Grey (blend)", "Emulation.Option.snes9x.snes9x_superscope_color.Value.75% Grey (blend)")]),
        new("snes9x_justifier1_crosshair", "Emulation.Option.snes9x.snes9x_justifier1_crosshair", "Emulation.Option.snes9x.snes9x_justifier1_crosshair.Help", "lightgun", "4", "4", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16")]),
        new("snes9x_justifier1_color", "Emulation.Option.snes9x.snes9x_justifier1_color", "Emulation.Option.snes9x.snes9x_justifier1_color.Help", "lightgun", "Blue", "Blue", [new("Blue", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Blue"), new("Blue (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Blue (blend)"), new("Violet", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Violet"), new("Violet (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Violet (blend)"), new("Pink", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Pink"), new("Pink (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Pink (blend)"), new("Purple", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Purple"), new("Purple (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Purple (blend)"), new("Black", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Black"), new("Black (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Black (blend)"), new("25% Grey", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.25% Grey"), new("25% Grey (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.25% Grey (blend)"), new("50% Grey", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.50% Grey"), new("50% Grey (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.50% Grey (blend)"), new("75% Grey", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.75% Grey"), new("75% Grey (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.75% Grey (blend)"), new("White", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.White"), new("White (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.White (blend)"), new("Red", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Red"), new("Red (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Red (blend)"), new("Orange", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Orange"), new("Orange (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Orange (blend)"), new("Yellow", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Yellow"), new("Yellow (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Yellow (blend)"), new("Green", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Green"), new("Green (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Green (blend)"), new("Cyan", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Cyan"), new("Cyan (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Cyan (blend)"), new("Sky", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Sky"), new("Sky (blend)", "Emulation.Option.snes9x.snes9x_justifier1_color.Value.Sky (blend)")]),
        new("snes9x_justifier2_crosshair", "Emulation.Option.snes9x.snes9x_justifier2_crosshair", "Emulation.Option.snes9x.snes9x_justifier2_crosshair.Help", "lightgun", "4", "4", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16")]),
        new("snes9x_justifier2_color", "Emulation.Option.snes9x.snes9x_justifier2_color", "Emulation.Option.snes9x.snes9x_justifier2_color.Help", "lightgun", "Pink", "Pink", [new("Pink", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Pink"), new("Pink (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Pink (blend)"), new("Purple", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Purple"), new("Purple (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Purple (blend)"), new("Black", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Black"), new("Black (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Black (blend)"), new("25% Grey", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.25% Grey"), new("25% Grey (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.25% Grey (blend)"), new("50% Grey", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.50% Grey"), new("50% Grey (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.50% Grey (blend)"), new("75% Grey", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.75% Grey"), new("75% Grey (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.75% Grey (blend)"), new("White", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.White"), new("White (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.White (blend)"), new("Red", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Red"), new("Red (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Red (blend)"), new("Orange", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Orange"), new("Orange (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Orange (blend)"), new("Yellow", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Yellow"), new("Yellow (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Yellow (blend)"), new("Green", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Green"), new("Green (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Green (blend)"), new("Cyan", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Cyan"), new("Cyan (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Cyan (blend)"), new("Sky", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Sky"), new("Sky (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Sky (blend)"), new("Blue", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Blue"), new("Blue (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Blue (blend)"), new("Violet", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Violet"), new("Violet (blend)", "Emulation.Option.snes9x.snes9x_justifier2_color.Value.Violet (blend)")]),
        new("snes9x_rifle_crosshair", "Emulation.Option.snes9x.snes9x_rifle_crosshair", "Emulation.Option.snes9x.snes9x_rifle_crosshair.Help", "lightgun", "2", "2", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16")]),
        new("snes9x_rifle_color", "Emulation.Option.snes9x.snes9x_rifle_color", "Emulation.Option.snes9x.snes9x_rifle_color.Help", "lightgun", "White", "White", [new("White", "Emulation.Option.snes9x.snes9x_rifle_color.Value.White"), new("White (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.White (blend)"), new("Red", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Red"), new("Red (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Red (blend)"), new("Orange", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Orange"), new("Orange (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Orange (blend)"), new("Yellow", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Yellow"), new("Yellow (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Yellow (blend)"), new("Green", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Green"), new("Green (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Green (blend)"), new("Cyan", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Cyan"), new("Cyan (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Cyan (blend)"), new("Sky", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Sky"), new("Sky (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Sky (blend)"), new("Blue", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Blue"), new("Blue (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Blue (blend)"), new("Violet", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Violet"), new("Violet (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Violet (blend)"), new("Pink", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Pink"), new("Pink (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Pink (blend)"), new("Purple", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Purple"), new("Purple (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Purple (blend)"), new("Black", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Black"), new("Black (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.Black (blend)"), new("25% Grey", "Emulation.Option.snes9x.snes9x_rifle_color.Value.25% Grey"), new("25% Grey (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.25% Grey (blend)"), new("50% Grey", "Emulation.Option.snes9x.snes9x_rifle_color.Value.50% Grey"), new("50% Grey (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.50% Grey (blend)"), new("75% Grey", "Emulation.Option.snes9x.snes9x_rifle_color.Value.75% Grey"), new("75% Grey (blend)", "Emulation.Option.snes9x.snes9x_rifle_color.Value.75% Grey (blend)")]),
        new("snes9x_msu1_enhanced_audio", "Emulation.Option.snes9x.snes9x_msu1_enhanced_audio", "Emulation.Option.snes9x.snes9x_msu1_enhanced_audio.Help", "", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_msu1_enhanced_audio.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_msu1_enhanced_audio.Value.disabled")]),
        new("snes9x_show_advanced_av_settings", "Emulation.Option.snes9x.snes9x_show_advanced_av_settings", "Emulation.Option.snes9x.snes9x_show_advanced_av_settings.Help", "", "disabled", "disabled", [new("enabled", "Emulation.Option.snes9x.snes9x_show_advanced_av_settings.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_show_advanced_av_settings.Value.disabled")]),
        new("snes9x_layer_1", "Emulation.Option.snes9x.snes9x_layer_1", null, "advanced_av", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_layer_1.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_layer_1.Value.disabled")]),
        new("snes9x_layer_2", "Emulation.Option.snes9x.snes9x_layer_2", null, "advanced_av", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_layer_2.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_layer_2.Value.disabled")]),
        new("snes9x_layer_3", "Emulation.Option.snes9x.snes9x_layer_3", null, "advanced_av", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_layer_3.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_layer_3.Value.disabled")]),
        new("snes9x_layer_4", "Emulation.Option.snes9x.snes9x_layer_4", null, "advanced_av", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_layer_4.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_layer_4.Value.disabled")]),
        new("snes9x_layer_5", "Emulation.Option.snes9x.snes9x_layer_5", null, "advanced_av", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_layer_5.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_layer_5.Value.disabled")]),
        new("snes9x_gfx_transp", "Emulation.Option.snes9x.snes9x_gfx_transp", null, "advanced_av", "enabled", "enabled", [new("enabled", "Emulation.Option.snes9x.snes9x_gfx_transp.Value.enabled"), new("disabled", "Emulation.Option.snes9x.snes9x_gfx_transp.Value.disabled")]),
        new("snes9x_sndchan_volume_1", "Emulation.Option.snes9x.snes9x_sndchan_volume_1", null, "advanced_av", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")]),
        new("snes9x_sndchan_volume_2", "Emulation.Option.snes9x.snes9x_sndchan_volume_2", null, "advanced_av", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")]),
        new("snes9x_sndchan_volume_3", "Emulation.Option.snes9x.snes9x_sndchan_volume_3", null, "advanced_av", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")]),
        new("snes9x_sndchan_volume_4", "Emulation.Option.snes9x.snes9x_sndchan_volume_4", null, "advanced_av", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")]),
        new("snes9x_sndchan_volume_5", "Emulation.Option.snes9x.snes9x_sndchan_volume_5", null, "advanced_av", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")]),
        new("snes9x_sndchan_volume_6", "Emulation.Option.snes9x.snes9x_sndchan_volume_6", null, "advanced_av", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")]),
        new("snes9x_sndchan_volume_7", "Emulation.Option.snes9x.snes9x_sndchan_volume_7", null, "advanced_av", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")]),
        new("snes9x_sndchan_volume_8", "Emulation.Option.snes9x.snes9x_sndchan_volume_8", null, "advanced_av", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")])
    ];
}
