<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>gwgui.emulation.atari</AssemblyName>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GWGUI.Tests" />
    <ProjectReference Include="..\GWGUI.Emulation\GWGUI.Emulation.csproj" />
    <ProjectReference Include="..\GWGUI.MediaEngine\GWGUI.MediaEngine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\*\*.resx">
      <WithCulture>false</WithCulture>
      <LogicalName>GWGUI.Emulation.Atari.Resources.%(Filename).$([System.IO.Path]::GetFileName($([System.IO.Path]::GetDirectoryName('%(Identity)')))).resources</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
