<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>gwgui.emulation.atari</AssemblyName>
    <RootNamespace>GWGUI.Emulation.Atari</RootNamespace>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GWGUI.Tests" />
    <ProjectReference Include="..\GWGUI.Emulation\GWGUI.Emulation.csproj" />
  </ItemGroup>
</Project>
