using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.BsnesHd.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("bsnes_video_luminance", "Emulation.Option.bsnes_hd_beta.bsnes_video_luminance", "Emulation.Option.bsnes_hd_beta.bsnes_video_luminance.Help", "", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100")]),
        new("bsnes_video_saturation", "Emulation.Option.bsnes_hd_beta.bsnes_video_saturation", "Emulation.Option.bsnes_hd_beta.bsnes_video_saturation.Help", "", "100", "100", [new("0", "0"), new("10", "10"), new("20", "20"), new("30", "30"), new("40", "40"), new("50", "50"), new("60", "60"), new("70", "70"), new("80", "80"), new("90", "90"), new("100", "100"), new("110", "110"), new("120", "120"), new("130", "130"), new("140", "140"), new("150", "150"), new("160", "160"), new("170", "170"), new("180", "180"), new("190", "190"), new("200", "200")]),
        new("bsnes_video_gamma", "Emulation.Option.bsnes_hd_beta.bsnes_video_gamma", "Emulation.Option.bsnes_hd_beta.bsnes_video_gamma.Help", "", "100", "100", [new("100", "100"), new("110", "110"), new("120", "120"), new("130", "130"), new("140", "140"), new("150", "150"), new("160", "160"), new("170", "170"), new("180", "180"), new("190", "190"), new("200", "200")]),
        new("bsnes_video_aspectcorrection", "Emulation.Option.bsnes_hd_beta.bsnes_video_aspectcorrection", "Emulation.Option.bsnes_hd_beta.bsnes_video_aspectcorrection.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_video_aspectcorrection.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_video_aspectcorrection.Value.OFF")]),
        new("bsnes_ppu_show_overscan", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_show_overscan", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_show_overscan.Help", "", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_show_overscan.Value.OFF"), new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_show_overscan.Value.ON")]),
        new("bsnes_blur_emulation", "Emulation.Option.bsnes_hd_beta.bsnes_blur_emulation", "Emulation.Option.bsnes_hd_beta.bsnes_blur_emulation.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_blur_emulation.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_blur_emulation.Value.OFF")]),
        new("bsnes_hotfixes", "Emulation.Option.bsnes_hd_beta.bsnes_hotfixes", "Emulation.Option.bsnes_hd_beta.bsnes_hotfixes.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_hotfixes.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_hotfixes.Value.OFF")]),
        new("bsnes_entropy", "Emulation.Option.bsnes_hd_beta.bsnes_entropy", "Emulation.Option.bsnes_hd_beta.bsnes_entropy.Help", "", "Low", "Low", [new("Low", "Emulation.Option.bsnes_hd_beta.bsnes_entropy.Value.Low"), new("High", "Emulation.Option.bsnes_hd_beta.bsnes_entropy.Value.High"), new("None", "Emulation.Option.bsnes_hd_beta.bsnes_entropy.Value.None")]),
        new("bsnes_cpu_overclock", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_overclock", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_overclock.Help", "", "100", "100", [new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "100%"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%"), new("210", "210%"), new("220", "220%"), new("230", "230%"), new("240", "240%"), new("250", "250%"), new("260", "260%"), new("270", "270%"), new("280", "280%"), new("290", "290%"), new("300", "300%"), new("310", "310%"), new("320", "320%"), new("330", "330%"), new("340", "340%"), new("350", "350%"), new("360", "360%"), new("370", "370%"), new("380", "380%"), new("390", "390%"), new("400", "400%")]),
        new("bsnes_cpu_fastmath", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_fastmath", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_fastmath.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_fastmath.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_fastmath.Value.OFF")]),
        new("bsnes_cpu_sa1_overclock", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_sa1_overclock", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_sa1_overclock.Help", "", "100", "100", [new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "100%"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%"), new("210", "210%"), new("220", "220%"), new("230", "230%"), new("240", "240%"), new("250", "250%"), new("260", "260%"), new("270", "270%"), new("280", "280%"), new("290", "290%"), new("300", "300%"), new("310", "310%"), new("320", "320%"), new("330", "330%"), new("340", "340%"), new("350", "350%"), new("360", "360%"), new("370", "370%"), new("380", "380%"), new("390", "390%"), new("400", "400%")]),
        new("bsnes_cpu_sfx_overclock", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_sfx_overclock", "Emulation.Option.bsnes_hd_beta.bsnes_cpu_sfx_overclock.Help", "", "100", "100", [new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "100%"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%"), new("210", "210%"), new("220", "220%"), new("230", "230%"), new("240", "240%"), new("250", "250%"), new("260", "260%"), new("270", "270%"), new("280", "280%"), new("290", "290%"), new("300", "300%"), new("310", "310%"), new("320", "320%"), new("330", "330%"), new("340", "340%"), new("350", "350%"), new("360", "360%"), new("370", "370%"), new("380", "380%"), new("390", "390%"), new("400", "400%"), new("410", "410%"), new("420", "420%"), new("430", "430%"), new("440", "440%"), new("450", "450%"), new("460", "460%"), new("470", "470%"), new("480", "480%"), new("490", "490%"), new("500", "500%"), new("510", "510%"), new("520", "520%"), new("530", "530%"), new("540", "540%"), new("550", "550%"), new("560", "560%"), new("570", "570%"), new("580", "580%"), new("590", "590%"), new("600", "600%"), new("610", "610%"), new("620", "620%"), new("630", "630%"), new("640", "640%"), new("650", "650%"), new("660", "660%"), new("670", "670%"), new("680", "680%"), new("690", "690%"), new("700", "700%"), new("710", "710%"), new("720", "720%"), new("730", "730%"), new("740", "740%"), new("750", "750%"), new("760", "760%"), new("770", "770%"), new("780", "780%"), new("790", "790%"), new("800", "800%")]),
        new("bsnes_ppu_fast", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_fast", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_fast.Help", "", "ON", "ON", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_fast.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_fast.Value.OFF")]),
        new("bsnes_ppu_deinterlace", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_deinterlace", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_deinterlace.Help", "", "ON", "ON", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_deinterlace.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_deinterlace.Value.OFF")]),
        new("bsnes_ppu_no_sprite_limit", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_no_sprite_limit", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_no_sprite_limit.Help", "", "ON", "ON", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_no_sprite_limit.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_no_sprite_limit.Value.OFF")]),
        new("bsnes_ppu_no_vram_blocking", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_no_vram_blocking", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_no_vram_blocking.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_no_vram_blocking.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_ppu_no_vram_blocking.Value.OFF")]),
        new("bsnes_dsp_fast", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_fast", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_fast.Help", "", "ON", "ON", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_fast.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_fast.Value.OFF")]),
        new("bsnes_dsp_cubic", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_cubic", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_cubic.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_cubic.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_cubic.Value.OFF")]),
        new("bsnes_dsp_echo_shadow", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_echo_shadow", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_echo_shadow.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_echo_shadow.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_dsp_echo_shadow.Value.OFF")]),
        new("bsnes_coprocessor_delayed_sync", "Emulation.Option.bsnes_hd_beta.bsnes_coprocessor_delayed_sync", "Emulation.Option.bsnes_hd_beta.bsnes_coprocessor_delayed_sync.Help", "", "ON", "ON", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_coprocessor_delayed_sync.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_coprocessor_delayed_sync.Value.OFF")]),
        new("bsnes_coprocessor_prefer_hle", "Emulation.Option.bsnes_hd_beta.bsnes_coprocessor_prefer_hle", "Emulation.Option.bsnes_hd_beta.bsnes_coprocessor_prefer_hle.Help", "", "ON", "ON", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_coprocessor_prefer_hle.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_coprocessor_prefer_hle.Value.OFF")]),
        new("bsnes_sgb_bios", "Emulation.Option.bsnes_hd_beta.bsnes_sgb_bios", "Emulation.Option.bsnes_hd_beta.bsnes_sgb_bios.Help", "", "SGB1.sfc", "SGB1.sfc", [new("SGB1.sfc", "Emulation.Option.bsnes_hd_beta.bsnes_sgb_bios.Value.SGB1.sfc"), new("SGB2.sfc", "Emulation.Option.bsnes_hd_beta.bsnes_sgb_bios.Value.SGB2.sfc")]),
        new("bsnes_run_ahead_frames", "Emulation.Option.bsnes_hd_beta.bsnes_run_ahead_frames", "Emulation.Option.bsnes_hd_beta.bsnes_run_ahead_frames.Help", "", "OFF", "OFF", [new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_run_ahead_frames.Value.OFF"), new("1", "Emulation.Option.bsnes_hd_beta.bsnes_run_ahead_frames.Value.1"), new("2", "Emulation.Option.bsnes_hd_beta.bsnes_run_ahead_frames.Value.2"), new("3", "Emulation.Option.bsnes_hd_beta.bsnes_run_ahead_frames.Value.3"), new("4", "Emulation.Option.bsnes_hd_beta.bsnes_run_ahead_frames.Value.4")]),
        new("bsnes_ips_headered", "Emulation.Option.bsnes_hd_beta.bsnes_ips_headered", "Emulation.Option.bsnes_hd_beta.bsnes_ips_headered.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_ips_headered.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_ips_headered.Value.OFF")]),
        new("bsnes_mode7_scale", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_scale", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_scale.Help", "", "2x", "2x", [new("disable", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_scale.Value.disable"), new("1x", "240p (1x)"), new("2x", "480p (2x)"), new("3x", "720p (3x)"), new("4x", "960p (4x)"), new("5x", "1200p (5x)"), new("6x", "1440p (6x)"), new("7x", "1680p (7x)"), new("8x", "1920p (8x)"), new("9x", "2160p (9x)"), new("10x", "2400p (10x)")]),
        new("bsnes_mode7_perspective", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective.Help", "", "auto (wide)", "auto (wide)", [new("auto (wide)", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective.Value.auto (wide)"), new("auto (medium)", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective.Value.auto (medium)"), new("auto (narrow)", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective.Value.auto (narrow)"), new("on (wide)", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective.Value.on (wide)"), new("on (medium)", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective.Value.on (medium)"), new("on (narrow)", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective.Value.on (narrow)"), new("off", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_perspective.Value.off")]),
        new("bsnes_mode7_supersample", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_supersample", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_supersample.Help", "", "none", "none", [new("none", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_supersample.Value.none"), new("2x", "2x"), new("3x", "3x"), new("4x", "4x"), new("5x", "5x"), new("6x", "6x"), new("7x", "7x"), new("8x", "8x"), new("9x", "9x"), new("10x", "10x")]),
        new("bsnes_mode7_mosaic", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_mosaic", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_mosaic.Help", "", "1x scale", "1x scale", [new("non-HD", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_mosaic.Value.non-HD"), new("ignore", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_mosaic.Value.ignore"), new("1x scale", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_mosaic.Value.1x scale")]),
        new("bsnes_mode7_bgGrad", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_bgGrad", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_bgGrad.Help", "", "4", "4", [new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("0", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_bgGrad.Value.0")]),
        new("bsnes_mode7_windRad", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_windRad", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_windRad.Help", "", "0", "0", [new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("0", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_windRad.Value.0")]),
        new("bsnes_mode7_wsMode", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMode", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMode.Help", "", "Mode 7", "Mode 7", [new("Mode 7", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMode.Value.Mode 7"), new("all", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMode.Value.all"), new("none", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMode.Value.none")]),
        new("bsnes_mode7_widescreen", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_widescreen", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_widescreen.Help", "", "16:9", "16:9", [new("16:9", "16:9"), new("16:10", "16:10"), new("21:9", "21:9"), new("2:1", "2:1"), new("4:3", "4:3"), new("none", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_widescreen.Value.none")]),
        new("bsnes_mode7_wsbg1", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Help", "", "auto horz and vert", "auto horz and vert", [new("on", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.on"), new("auto horizontal", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.auto horizontal"), new("auto horz and vert", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.auto horz and vert"), new("above line 40", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.above line 40"), new("below line 40", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.below line 40"), new("above line 80", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.above line 80"), new("below line 80", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.below line 80"), new("above line 120", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.above line 120"), new("below line 120", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.below line 120"), new("above line 160", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.above line 160"), new("below line 160", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.below line 160"), new("above line 200", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.above line 200"), new("below line 200", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.below line 200"), new("crop edges", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.crop edges"), new("auto crop edges", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.auto crop edges"), new("off", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.off"), new("disable entirely", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg1.Value.disable entirely")]),
        new("bsnes_mode7_wsbg2", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Help", "", "auto horz and vert", "auto horz and vert", [new("on", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.on"), new("auto horizontal", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.auto horizontal"), new("auto horz and vert", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.auto horz and vert"), new("above line 40", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.above line 40"), new("below line 40", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.below line 40"), new("above line 80", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.above line 80"), new("below line 80", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.below line 80"), new("above line 120", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.above line 120"), new("below line 120", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.below line 120"), new("above line 160", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.above line 160"), new("below line 160", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.below line 160"), new("above line 200", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.above line 200"), new("below line 200", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.below line 200"), new("crop edges", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.crop edges"), new("auto crop edges", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.auto crop edges"), new("off", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.off"), new("disable entirely", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg2.Value.disable entirely")]),
        new("bsnes_mode7_wsbg3", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Help", "", "auto horz and vert", "auto horz and vert", [new("on", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.on"), new("auto horizontal", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.auto horizontal"), new("auto horz and vert", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.auto horz and vert"), new("above line 40", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.above line 40"), new("below line 40", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.below line 40"), new("above line 80", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.above line 80"), new("below line 80", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.below line 80"), new("above line 120", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.above line 120"), new("below line 120", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.below line 120"), new("above line 160", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.above line 160"), new("below line 160", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.below line 160"), new("above line 200", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.above line 200"), new("below line 200", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.below line 200"), new("crop edges", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.crop edges"), new("auto crop edges", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.auto crop edges"), new("off", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.off"), new("disable entirely", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg3.Value.disable entirely")]),
        new("bsnes_mode7_wsbg4", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Help", "", "auto horz and vert", "auto horz and vert", [new("on", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.on"), new("auto horizontal", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.auto horizontal"), new("auto horz and vert", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.auto horz and vert"), new("above line 40", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.above line 40"), new("below line 40", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.below line 40"), new("above line 80", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.above line 80"), new("below line 80", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.below line 80"), new("above line 120", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.above line 120"), new("below line 120", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.below line 120"), new("above line 160", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.above line 160"), new("below line 160", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.below line 160"), new("above line 200", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.above line 200"), new("below line 200", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.below line 200"), new("crop edges", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.crop edges"), new("auto crop edges", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.auto crop edges"), new("off", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.off"), new("disable entirely", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsbg4.Value.disable entirely")]),
        new("bsnes_mode7_wsobj", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsobj", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsobj.Help", "", "safe", "safe", [new("safe", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsobj.Value.safe"), new("unsafe", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsobj.Value.unsafe"), new("clip", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsobj.Value.clip"), new("disable entirely", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsobj.Value.disable entirely")]),
        new("bsnes_mode7_wsBgCol", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsBgCol", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsBgCol.Help", "", "auto", "auto", [new("auto", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsBgCol.Value.auto"), new("color", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsBgCol.Value.color"), new("black", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsBgCol.Value.black")]),
        new("bsnes_mode7_igwin", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwin", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwin.Help", "", "outside", "outside", [new("outside", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwin.Value.outside"), new("outside and always", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwin.Value.outside and always"), new("all", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwin.Value.all"), new("none", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwin.Value.none")]),
        new("bsnes_mode7_igwinx", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwinx", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwinx.Help", "", "128", "128", [new("40", "40"), new("88", "88"), new("128", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_igwinx.Value.128"), new("168", "168"), new("216", "216")]),
        new("bsnes_mode7_wsMarker", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMarker", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMarker.Help", "", "none", "none", [new("lines", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMarker.Value.lines"), new("darken", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMarker.Value.darken"), new("none", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMarker.Value.none")]),
        new("bsnes_mode7_wsMarkerAlpha", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMarkerAlpha", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_wsMarkerAlpha.Help", "", "1/1", "1/1", [new("1/1", "1/1"), new("1/2", "1/2"), new("1/3", "1/3"), new("1/4", "1/4"), new("1/5", "1/5"), new("1/6", "1/6"), new("1/7", "1/7"), new("1/8", "1/8"), new("1/9", "1/9"), new("1/10", "1/10")]),
        new("bsnes_mode7_strWin", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_strWin", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_strWin.Help", "", "OFF", "OFF", [new("ON", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_strWin.Value.ON"), new("OFF", "Emulation.Option.bsnes_hd_beta.bsnes_mode7_strWin.Value.OFF")])
    ];
}
