using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Citra.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("citra_use_cpu_jit", "Emulation.Option.citra.citra_use_cpu_jit", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra.citra_use_cpu_jit.Value.enabled"), new("disabled", "Emulation.Option.citra.citra_use_cpu_jit.Value.disabled")]),
        new("citra_cpu_scale", "Emulation.Option.citra.citra_cpu_scale", null, "", "100% (Default)", "100% (Default)", [new("100% (Default)", "Emulation.Option.citra.citra_cpu_scale.Value.100% (Default)"), new("5%", "5%"), new("10%", "10%"), new("15%", "15%"), new("20%", "20%"), new("25%", "25%"), new("30%", "30%"), new("35%", "35%"), new("40%", "40%"), new("45%", "45%"), new("50%", "50%"), new("55%", "55%"), new("60%", "60%"), new("65%", "65%"), new("70%", "70%"), new("75%", "75%"), new("80%", "80%"), new("85%", "85%"), new("90%", "90%"), new("95%", "95%"), new("105%", "105%"), new("110%", "110%"), new("115%", "115%"), new("120%", "120%"), new("125%", "125%"), new("130%", "130%"), new("135%", "135%"), new("140%", "140%"), new("145%", "145%"), new("150%", "150%"), new("155%", "155%"), new("160%", "160%"), new("165%", "165%"), new("170%", "170%"), new("175%", "175%"), new("180%", "180%"), new("185%", "185%"), new("190%", "190%"), new("195%", "195%"), new("200%", "200%"), new("205%", "205%"), new("210%", "210%"), new("215%", "215%"), new("220%", "220%"), new("225%", "225%"), new("230%", "230%"), new("235%", "235%"), new("240%", "240%"), new("245%", "245%"), new("250%", "250%"), new("255%", "255%"), new("260%", "260%"), new("265%", "265%"), new("270%", "270%"), new("275%", "275%"), new("280%", "280%"), new("285%", "285%"), new("290%", "290%"), new("295%", "295%"), new("300%", "300%"), new("305%", "305%"), new("310%", "310%"), new("315%", "315%"), new("320%", "320%"), new("325%", "325%"), new("330%", "330%"), new("335%", "335%"), new("340%", "340%"), new("345%", "345%"), new("350%", "350%"), new("355%", "355%"), new("360%", "360%"), new("365%", "365%"), new("370%", "370%"), new("375%", "375%"), new("380%", "380%"), new("385%", "385%"), new("390%", "390%"), new("395%", "395%"), new("400%", "400%")]),
        new("citra_use_shader_jit", "Emulation.Option.citra.citra_use_shader_jit", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra.citra_use_shader_jit.Value.enabled"), new("disabled", "Emulation.Option.citra.citra_use_shader_jit.Value.disabled")]),
        new("citra_use_hw_shaders", "Emulation.Option.citra.citra_use_hw_shaders", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra.citra_use_hw_shaders.Value.enabled"), new("disabled", "Emulation.Option.citra.citra_use_hw_shaders.Value.disabled")]),
        new("citra_use_hw_shader_cache", "Emulation.Option.citra.citra_use_hw_shader_cache", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra.citra_use_hw_shader_cache.Value.enabled"), new("disabled", "Emulation.Option.citra.citra_use_hw_shader_cache.Value.disabled")]),
        new("citra_use_acc_geo_shaders", "Emulation.Option.citra.citra_use_acc_geo_shaders", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra.citra_use_acc_geo_shaders.Value.enabled"), new("disabled", "Emulation.Option.citra.citra_use_acc_geo_shaders.Value.disabled")]),
        new("citra_use_acc_mul", "Emulation.Option.citra.citra_use_acc_mul", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra.citra_use_acc_mul.Value.enabled"), new("disabled", "Emulation.Option.citra.citra_use_acc_mul.Value.disabled")]),
        new("citra_texture_filter", "Emulation.Option.citra.citra_texture_filter", null, "", "none", "none", [new("none", "Emulation.Option.citra.citra_texture_filter.Value.none"), new("Anime4K Ultrafast", "Emulation.Option.citra.citra_texture_filter.Value.Anime4K Ultrafast"), new("Bicubic", "Emulation.Option.citra.citra_texture_filter.Value.Bicubic"), new("NearestNeighbor", "Emulation.Option.citra.citra_texture_filter.Value.NearestNeighbor"), new("ScaleForce", "Emulation.Option.citra.citra_texture_filter.Value.ScaleForce"), new("xBRZ freescale", "Emulation.Option.citra.citra_texture_filter.Value.xBRZ freescale"), new("MMPX", "Emulation.Option.citra.citra_texture_filter.Value.MMPX")]),
        new("citra_texture_sampling", "Emulation.Option.citra.citra_texture_sampling", null, "", "GameControlled", "GameControlled", [new("GameControlled", "Emulation.Option.citra.citra_texture_sampling.Value.GameControlled"), new("NearestNeighbor", "Emulation.Option.citra.citra_texture_sampling.Value.NearestNeighbor"), new("Linear", "Emulation.Option.citra.citra_texture_sampling.Value.Linear")]),
        new("citra_custom_textures", "Emulation.Option.citra.citra_custom_textures", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.citra.citra_custom_textures.Value.disabled"), new("enabled", "Emulation.Option.citra.citra_custom_textures.Value.enabled")]),
        new("citra_dump_textures", "Emulation.Option.citra.citra_dump_textures", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.citra.citra_dump_textures.Value.disabled"), new("enabled", "Emulation.Option.citra.citra_dump_textures.Value.enabled")]),
        new("citra_resolution_factor", "Emulation.Option.citra.citra_resolution_factor", null, "", "1x (Native)", "1x (Native)", [new("1x (Native)", "Emulation.Option.citra.citra_resolution_factor.Value.1x (Native)"), new("2x", "2x"), new("3x", "3x"), new("4x", "4x"), new("5x", "5x"), new("6x", "6x"), new("7x", "7x"), new("8x", "8x"), new("9x", "9x"), new("10x", "10x")]),
        new("citra_layout_option", "Emulation.Option.citra.citra_layout_option", null, "", "Default Top-Bottom Screen", "Default Top-Bottom Screen", [new("Default Top-Bottom Screen", "Emulation.Option.citra.citra_layout_option.Value.Default Top-Bottom Screen"), new("Single Screen Only", "Emulation.Option.citra.citra_layout_option.Value.Single Screen Only"), new("Large Screen, Small Screen", "Emulation.Option.citra.citra_layout_option.Value.Large Screen, Small Screen"), new("Side by Side", "Emulation.Option.citra.citra_layout_option.Value.Side by Side")]),
        new("citra_swap_screen", "Emulation.Option.citra.citra_swap_screen", null, "", "Top", "Top", [new("Top", "Emulation.Option.citra.citra_swap_screen.Value.Top"), new("Bottom", "Emulation.Option.citra.citra_swap_screen.Value.Bottom")]),
        new("citra_swap_screen_mode", "Emulation.Option.citra.citra_swap_screen_mode", null, "", "Toggle", "Toggle", [new("Toggle", "Emulation.Option.citra.citra_swap_screen_mode.Value.Toggle"), new("Hold", "Emulation.Option.citra.citra_swap_screen_mode.Value.Hold")]),
        new("citra_analog_function", "Emulation.Option.citra.citra_analog_function", null, "", "C-Stick and Touchscreen Pointer", "C-Stick and Touchscreen Pointer", [new("C-Stick and Touchscreen Pointer", "Emulation.Option.citra.citra_analog_function.Value.C-Stick and Touchscreen Pointer"), new("Touchscreen Pointer", "Emulation.Option.citra.citra_analog_function.Value.Touchscreen Pointer"), new("C-Stick", "Emulation.Option.citra.citra_analog_function.Value.C-Stick")]),
        new("citra_deadzone", "Emulation.Option.citra.citra_deadzone", null, "", "15", "15", [new("15", "15"), new("20", "20"), new("25", "25"), new("30", "30"), new("35", "35"), new("0", "0"), new("5", "5"), new("10", "10")]),
        new("citra_mouse_touchscreen", "Emulation.Option.citra.citra_mouse_touchscreen", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra.citra_mouse_touchscreen.Value.enabled"), new("disabled", "Emulation.Option.citra.citra_mouse_touchscreen.Value.disabled")]),
        new("citra_touch_touchscreen", "Emulation.Option.citra.citra_touch_touchscreen", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.citra.citra_touch_touchscreen.Value.disabled"), new("enabled", "Emulation.Option.citra.citra_touch_touchscreen.Value.enabled")]),
        new("citra_render_touchscreen", "Emulation.Option.citra.citra_render_touchscreen", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.citra.citra_render_touchscreen.Value.disabled"), new("enabled", "Emulation.Option.citra.citra_render_touchscreen.Value.enabled")]),
        new("citra_use_virtual_sd", "Emulation.Option.citra.citra_use_virtual_sd", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra.citra_use_virtual_sd.Value.enabled"), new("disabled", "Emulation.Option.citra.citra_use_virtual_sd.Value.disabled")]),
        new("citra_use_libretro_save_path", "Emulation.Option.citra.citra_use_libretro_save_path", null, "", "LibRetro Default", "LibRetro Default", [new("LibRetro Default", "Emulation.Option.citra.citra_use_libretro_save_path.Value.LibRetro Default"), new("Citra Default", "Emulation.Option.citra.citra_use_libretro_save_path.Value.Citra Default")]),
        new("citra_is_new_3ds", "Emulation.Option.citra.citra_is_new_3ds", null, "", "Old 3DS", "Old 3DS", [new("Old 3DS", "Emulation.Option.citra.citra_is_new_3ds.Value.Old 3DS"), new("New 3DS", "Emulation.Option.citra.citra_is_new_3ds.Value.New 3DS")]),
        new("citra_region_value", "Emulation.Option.citra.citra_region_value", null, "", "Auto", "Auto", [new("Auto", "Emulation.Option.citra.citra_region_value.Value.Auto"), new("Japan", "Emulation.Option.citra.citra_region_value.Value.Japan"), new("USA", "Emulation.Option.citra.citra_region_value.Value.USA"), new("Europe", "Emulation.Option.citra.citra_region_value.Value.Europe"), new("Australia", "Emulation.Option.citra.citra_region_value.Value.Australia"), new("China", "Emulation.Option.citra.citra_region_value.Value.China"), new("Korea", "Emulation.Option.citra.citra_region_value.Value.Korea"), new("Taiwan", "Emulation.Option.citra.citra_region_value.Value.Taiwan")]),
        new("citra_language", "Emulation.Option.citra.citra_language", null, "", "English", "English", [new("English", "Emulation.Option.citra.citra_language.Value.English"), new("Japanese", "Emulation.Option.citra.citra_language.Value.Japanese"), new("French", "Emulation.Option.citra.citra_language.Value.French"), new("Spanish", "Emulation.Option.citra.citra_language.Value.Spanish"), new("German", "Emulation.Option.citra.citra_language.Value.German"), new("Italian", "Emulation.Option.citra.citra_language.Value.Italian"), new("Dutch", "Emulation.Option.citra.citra_language.Value.Dutch"), new("Portuguese", "Emulation.Option.citra.citra_language.Value.Portuguese"), new("Russian", "Emulation.Option.citra.citra_language.Value.Russian"), new("Korean", "Emulation.Option.citra.citra_language.Value.Korean"), new("Traditional Chinese", "Emulation.Option.citra.citra_language.Value.Traditional Chinese"), new("Simplified Chinese", "Emulation.Option.citra.citra_language.Value.Simplified Chinese")]),
        new("citra_use_gdbstub", "Emulation.Option.citra.citra_use_gdbstub", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.citra.citra_use_gdbstub.Value.disabled"), new("enabled", "Emulation.Option.citra.citra_use_gdbstub.Value.enabled")])
    ];
}
