using GWGUI.Emulation.Constants;

namespace GWGUI.App.Views.Controls.Options.ControllerVisualization;

internal static partial class ControllerArtworkCatalog
{
    private static readonly IReadOnlyDictionary<string, ProfileDefinition> ProfileDefinitions =
        new Dictionary<string, ProfileDefinition>(StringComparer.Ordinal)
        {
            [EmulationControllerVisualIds.NecPcEnginePad] = CreateNecPcEnginePad(),
            [EmulationControllerVisualIds.NecPcEngineTurboPad] = CreateNecPcEngineTurboPad(),
            [EmulationControllerVisualIds.NecTurboGrafxTurboPad] = CreateNecTurboGrafxTurboPad(),
            [EmulationControllerVisualIds.NecCoreGrafxTurboPad] = CreateNecCoreGrafxTurboPad(),
            [EmulationControllerVisualIds.NecCoreGrafxIiTurboPad] = CreateNecCoreGrafxIiTurboPad(),
            [EmulationControllerVisualIds.NecDuoRTurboPad] = CreateNecDuoRTurboPad(),
            [EmulationControllerVisualIds.NecPcEngineTurboPadIi] = CreateNecPcEngineTurboPadIi(),
            [EmulationControllerVisualIds.NecPcEngineTurboStick] = CreateNecPcEngineTurboStick(),
            [EmulationControllerVisualIds.NecAvenuePad3] = CreateNecAvenuePad3(),
            [EmulationControllerVisualIds.NecAvenuePad6] = CreateNecAvenuePad6(),
            [EmulationControllerVisualIds.NecArcadePad6] = CreateNecArcadePad6(),
            [EmulationControllerVisualIds.NecTurboGrafxTurboStick] = CreateNecTurboGrafxTurboStick(),
            [EmulationControllerVisualIds.NecDuoPad] = CreateNecDuoPad(),
            [EmulationControllerVisualIds.NecCordlessPad] = CreateNecCordlessPad(),
            [EmulationControllerVisualIds.NecTurboExpressControls] = CreateNecTurboExpressControls(),
            [EmulationControllerVisualIds.NecPcEngineLtControls] = CreateNecPcEngineLtControls(),
            [EmulationControllerVisualIds.NecPcFxPad] = CreateNecPcFxPad(),
            [EmulationControllerVisualIds.NecPcEngineMouse] = CreateNecPcEngineMouse(),
            [EmulationControllerVisualIds.NecPcFxMouse] = CreateNecPcFxMouse(),
            [EmulationControllerVisualIds.XboxDuke] = CreateXboxDuke(),
            [EmulationControllerVisualIds.XboxControllerS] = CreateXboxControllerS(),
            [EmulationControllerVisualIds.Xbox360TransformingDPad] = CreateXbox360TransformingDPad(),
            [EmulationControllerVisualIds.Xbox360WirelessRacingWheel] = CreateXbox360WirelessRacingWheel(),
            [EmulationControllerVisualIds.Xbox360WirelessSpeedWheel] = CreateXbox360WirelessSpeedWheel(),
            [EmulationControllerVisualIds.Xbox360BigButtonPad] = CreateXbox360BigButtonPad(),
            [EmulationControllerVisualIds.XboxDvdMoviePlaybackKit] = CreateXboxDvdMoviePlaybackKit(),
            [EmulationControllerVisualIds.Xbox360Chatpad] = CreateXbox360Chatpad(),
            [EmulationControllerVisualIds.XboxChatpad] = CreateXboxChatpad(),
            [EmulationControllerVisualIds.SonyPlayStationController] = CreateSonyPlayStationController(),
            [EmulationControllerVisualIds.SonyDualShock1] = CreateSonyDualShock1(),
            [EmulationControllerVisualIds.SonyDualShock2] = CreateSonyDualShock2(),
            [EmulationControllerVisualIds.SonyDualShock4] = CreateSonyDualShock4(),
            [EmulationControllerVisualIds.SonyDualSense] = CreateSonyDualSense(),
            [EmulationControllerVisualIds.SonyPsp1000] = CreateSonyPsp1000(),
            [EmulationControllerVisualIds.NintendoNesPad] = CreateNintendoNesPad(),
            [EmulationControllerVisualIds.NintendoNesMax] = CreateNintendoNesMax(),
            [EmulationControllerVisualIds.NintendoNesAdvantage] = CreateNintendoNesAdvantage(),
            [EmulationControllerVisualIds.NintendoNesDogbonePad] = CreateNintendoNesDogbonePad(),
            [EmulationControllerVisualIds.NintendoFamicomPad1] = CreateNintendoFamicomPad1(),
            [EmulationControllerVisualIds.NintendoSuperNesPad] = CreateNintendoSuperNesPad(),
            [EmulationControllerVisualIds.NintendoSuperFamicomPad] = CreateNintendoSuperFamicomPad(),
            [EmulationControllerVisualIds.NintendoGameBoy] = CreateNintendoGameBoy(),
            [EmulationControllerVisualIds.NintendoGameBoyColor] = CreateNintendoGameBoyColor(),
            [EmulationControllerVisualIds.NintendoGameBoyAdvance] = CreateNintendoGameBoyAdvance(),
            [EmulationControllerVisualIds.Nintendo64Pad] = CreateNintendo64Pad(),
            [EmulationControllerVisualIds.NintendoGameCubePad] = CreateNintendoGameCubePad(),
            [EmulationControllerVisualIds.NintendoGameCubeWaveBird] = CreateNintendoGameCubeWaveBird(),
            [EmulationControllerVisualIds.QuickShot] = CreateQuickShot(),
            [EmulationControllerVisualIds.QuickShotDeluxe] = CreateQuickShotDeluxe(),
            [EmulationControllerVisualIds.QuickShotIiTurbo] = CreateQuickShotIiTurbo(),
            [EmulationControllerVisualIds.CompetitionPro5000] = CreateCompetitionPro5000(),
            [EmulationControllerVisualIds.ZipstikSuperPro] = CreateZipstikSuperPro(),
            [EmulationControllerVisualIds.KonixSpeedkingLeftHand] = CreateKonixSpeedkingLeftHand(),
            [EmulationControllerVisualIds.KonixSpeedkingRightHand] = CreateKonixSpeedkingRightHand(),
            [EmulationControllerVisualIds.KonixSpeedkingAnalog] = CreateKonixSpeedkingAnalog(),
            [EmulationControllerVisualIds.SuncomTac2] = CreateSuncomTac2(),
            [EmulationControllerVisualIds.PowerplayCruiser] = CreatePowerplayCruiser(),
            [EmulationControllerVisualIds.SuzoTheArcadeTurbo] = CreateSuzoTheArcadeTurbo(),
            [EmulationControllerVisualIds.CommodoreCd32] = CreateCommodoreCd32(),
            [EmulationControllerVisualIds.CompetitionProCd32] = CreateCompetitionProCd32(),
            [EmulationControllerVisualIds.AtariCx40] = CreateAtariCx40(),
            [EmulationControllerVisualIds.Atari5200Controller] = CreateAtari5200Controller(),
            [EmulationControllerVisualIds.Atari7800ProLineCx24] = CreateAtari7800ProLineCx24(),
            [EmulationControllerVisualIds.Atari7800ControlPadEurope] = CreateAtari7800ControlPadEurope(),
            [EmulationControllerVisualIds.AtariJaguarController] = CreateAtariJaguarController(),
            [EmulationControllerVisualIds.AtariJaguarProController] = CreateAtariJaguarProController(),
            [EmulationControllerVisualIds.SegaSg1000Joystick] = CreateSegaSg1000Joystick(),
            [EmulationControllerVisualIds.SegaSg1000Ii] = CreateSegaSg1000Ii(),
            [EmulationControllerVisualIds.MasterSystem] = CreateMasterSystem(),
            [EmulationControllerVisualIds.SegaControlStick] = CreateSegaControlStick(),
            [EmulationControllerVisualIds.GameGearControls] = CreateGameGearControls(),
            [EmulationControllerVisualIds.MegaDrive3] = CreateMegaDrive3(),
            [EmulationControllerVisualIds.MegaDrive6] = CreateMegaDrive6(),
            [EmulationControllerVisualIds.SegaArcadePowerStick3] = CreateSegaArcadePowerStick3(),
            [EmulationControllerVisualIds.SegaArcadePowerStick6] = CreateSegaArcadePowerStick6(),
            [EmulationControllerVisualIds.Saturn] = CreateSaturn(),
            [EmulationControllerVisualIds.SegaSaturnVirtuaStickHss0104] = CreateSegaSaturnVirtuaStickHss0104(),
            [EmulationControllerVisualIds.SegaSaturnVirtuaStickHss0136] = CreateSegaSaturnVirtuaStickHss0136(),
            [EmulationControllerVisualIds.Saturn3D] = CreateSaturn3D(),
            [EmulationControllerVisualIds.Dreamcast] = CreateDreamcast(),
            [EmulationControllerVisualIds.FlightStick] = CreateFlightStick(),
            [EmulationControllerVisualIds.RacingWheel] = CreateRacingWheel()
        };
}
