using GWGUI.Emulation.Amiga.Emulators.PUAE.Constants;
using GWGUI.Emulation.Amiga.Emulators.PUAE.Contracts;
using GWGUI.Emulation.Amiga.Emulators.PUAE.Factories;
using GWGUI.Emulation.Amiga.Emulators.PUAE.Functions;
using GWGUI.Emulation.Amiga.Emulators.PUAE.Services;

namespace GWGUI.Emulation.Amiga.Emulators.PUAE.Constants;

internal static class ExternalCoreConstants
{
    internal const string Kick31034A1000 = "kick31034.A1000";
    internal const string Kick32034A1000 = "kick32034.A1000";
    internal const string Kick33180A500 = "kick33180.A500";
    internal const string Kick34005A500 = "kick34005.A500";
    internal const string Kick37175A500 = "kick37175.A500";
    internal const string Kick37350A600 = "kick37350.A600";
    internal const string Kick40063A600 = "kick40063.A600";
    internal const string Kick39106A1200 = "kick39106.A1200";
    internal const string Kick40068A1200 = "kick40068.A1200";
    internal const string Kick39106A4000 = "kick39106.A4000";
    internal const string Kick40068A4000 = "kick40068.A4000";
    internal const string Kick40060CD32 = "kick40060.CD32";
    internal const string ConvertedMedia = "ConvertedMedia";
    internal const string Core = "Core";
    internal const string OptionLibretroDll = "puae_libretro.dll";
    internal const string RomKey = "rom.key";
    internal const string OptionKickstart = "puae_kickstart";
    internal const string Auto = "auto";
    internal const string OptionMapperMouseToggle = "puae_mapper_mouse_toggle";
    internal const string RightControl = "RETROK_RCTRL";
    internal const string RetroApiVersion = "retro_api_version";
    internal const string RetroGetSystemInfo = "retro_get_system_info";
    internal const string Scp = "scp";
    internal const string RetroSetEnvironment = "retro_set_environment";
    internal const string RetroSetVideoRefresh = "retro_set_video_refresh";
    internal const string RetroSetAudioSample = "retro_set_audio_sample";
    internal const string RetroSetAudioSampleBatch = "retro_set_audio_sample_batch";
    internal const string RetroSetInputPoll = "retro_set_input_poll";
    internal const string RetroSetInputState = "retro_set_input_state";
    internal const string RetroDeinit = "retro_deinit";
    internal const string RetroUnloadGame = "retro_unload_game";
    internal const string RetroRun = "retro_run";
    internal const string RetroReset = "retro_reset";
    internal const string RetroSerializeSize = "retro_serialize_size";
    internal const string RetroSerialize = "retro_serialize";
    internal const string RetroUnserialize = "retro_unserialize";
    internal const string RetroGetRegion = "retro_get_region";
    internal const string RetroGetMemoryData = "retro_get_memory_data";
    internal const string RetroGetMemorySize = "retro_get_memory_size";
    internal const string RetroInit = "retro_init";
    internal const string RetroSetControllerPortDevice = "retro_set_controller_port_device";
    internal const string CD32 = "CD32";
    internal const string RetroLoadGame = "retro_load_game";
    internal const string RetroGetSystemAvInfo = "retro_get_system_av_info";
    internal const string A1000 = "A1000";
    internal const string A500PLUS = "A500PLUS";
    internal const string A600 = "A600";
    internal const string A1200 = "A1200";
    internal const string A1200OG = "A1200OG";
    internal const string A3000 = "A3000";
    internal const string A4000 = "A4000";
    internal const string CDTV = "CDTV";
    internal const string CD32FR = "CD32FR";
    internal const string Kick40060CD32Ext = "kick40060.CD32.ext";
    internal const string Kick34005CDTV = "kick34005.CDTV";
    internal const string A500 = "A500";
    internal const string GWGUIMediaMDM3u = "GW GUI media (MD).m3u";
    internal const string GWGUIMediaM3u = "GW GUI media.m3u";
    internal const string Lha = ".lha";
    internal const string Slave = ".slave";
    internal const string Info = ".info";
    internal const string Uae = ".uae";
    internal const string Automatic = "Automatic";
    internal const string RetroPad = "RetroPad";
    internal const string CD32Pad = "CD32 Pad";
    internal const string AnalogJoystick = "Analog Joystick";
    internal const string Joystick = "Joystick";
    internal const string Keyboard = "Keyboard";
}
