using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Mesen.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("mesen_overclock", "Emulation.Option.mesen.mesen_overclock", "Emulation.Option.mesen.mesen_overclock.Help", "system", "None", "None", [new("None", "Emulation.Option.mesen.mesen_overclock.Value.None"), new("Low", "Emulation.Option.mesen.mesen_overclock.Value.Low"), new("Medium", "Emulation.Option.mesen.mesen_overclock.Value.Medium"), new("High", "Emulation.Option.mesen.mesen_overclock.Value.High"), new("Very High", "Emulation.Option.mesen.mesen_overclock.Value.Very High")]),
        new("mesen_overclock_type", "Emulation.Option.mesen.mesen_overclock_type", "Emulation.Option.mesen.mesen_overclock_type.Help", "system", "Before NMI (Recommended)", "Before NMI (Recommended)", [new("Before NMI (Recommended)", "Emulation.Option.mesen.mesen_overclock_type.Value.Before NMI (Recommended)"), new("After NMI", "Emulation.Option.mesen.mesen_overclock_type.Value.After NMI")]),
        new("mesen_region", "Emulation.Option.mesen.mesen_region", "Emulation.Option.mesen.mesen_region.Help", "system", "Auto", "Auto", [new("Auto", "Emulation.Option.mesen.mesen_region.Value.Auto"), new("NTSC", "Emulation.Option.mesen.mesen_region.Value.NTSC"), new("PAL", "Emulation.Option.mesen.mesen_region.Value.PAL"), new("Dendy", "Emulation.Option.mesen.mesen_region.Value.Dendy")]),
        new("mesen_ramstate", "Emulation.Option.mesen.mesen_ramstate", "Emulation.Option.mesen.mesen_ramstate.Help", "system", "All 0s (Default)", "All 0s (Default)", [new("All 0s (Default)", "Emulation.Option.mesen.mesen_ramstate.Value.All 0s (Default)"), new("All 1s", "Emulation.Option.mesen.mesen_ramstate.Value.All 1s"), new("Random Values", "Emulation.Option.mesen.mesen_ramstate.Value.Random Values")]),
        new("mesen_fdsautoinsertdisk", "Emulation.Option.mesen.mesen_fdsautoinsertdisk", "Emulation.Option.mesen.mesen_fdsautoinsertdisk.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen.mesen_fdsautoinsertdisk.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_fdsautoinsertdisk.Value.enabled")]),
        new("mesen_fdsfastforwardload", "Emulation.Option.mesen.mesen_fdsfastforwardload", "Emulation.Option.mesen.mesen_fdsfastforwardload.Help", "system", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen.mesen_fdsfastforwardload.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_fdsfastforwardload.Value.enabled")]),
        new("mesen_ntsc_filter", "Emulation.Option.mesen.mesen_ntsc_filter", "Emulation.Option.mesen.mesen_ntsc_filter.Help", "video", "Disabled", "Disabled", [new("Disabled", "Emulation.Option.mesen.mesen_ntsc_filter.Value.Disabled"), new("Composite (Blargg)", "Emulation.Option.mesen.mesen_ntsc_filter.Value.Composite (Blargg)"), new("S-Video (Blargg)", "Emulation.Option.mesen.mesen_ntsc_filter.Value.S-Video (Blargg)"), new("RGB (Blargg)", "Emulation.Option.mesen.mesen_ntsc_filter.Value.RGB (Blargg)"), new("Monochrome (Blargg)", "Emulation.Option.mesen.mesen_ntsc_filter.Value.Monochrome (Blargg)"), new("Bisqwit 2x", "Emulation.Option.mesen.mesen_ntsc_filter.Value.Bisqwit 2x"), new("Bisqwit 4x", "Emulation.Option.mesen.mesen_ntsc_filter.Value.Bisqwit 4x"), new("Bisqwit 8x", "Emulation.Option.mesen.mesen_ntsc_filter.Value.Bisqwit 8x")]),
        new("mesen_palette", "Emulation.Option.mesen.mesen_palette", null, "video", "Default", "Default", [new("Default", "Emulation.Option.mesen.mesen_palette.Value.Default"), new("Composite Direct (by FirebrandX)", "Emulation.Option.mesen.mesen_palette.Value.Composite Direct (by FirebrandX)"), new("Nes Classic", "Emulation.Option.mesen.mesen_palette.Value.Nes Classic"), new("Nestopia (RGB)", "Emulation.Option.mesen.mesen_palette.Value.Nestopia (RGB)"), new("Original Hardware (by FirebrandX)", "Emulation.Option.mesen.mesen_palette.Value.Original Hardware (by FirebrandX)"), new("PVM Style (by FirebrandX)", "Emulation.Option.mesen.mesen_palette.Value.PVM Style (by FirebrandX)"), new("Sony CXA2025AS", "Emulation.Option.mesen.mesen_palette.Value.Sony CXA2025AS"), new("Unsaturated v6 (by FirebrandX)", "Emulation.Option.mesen.mesen_palette.Value.Unsaturated v6 (by FirebrandX)"), new("YUV v3 (by FirebrandX)", "Emulation.Option.mesen.mesen_palette.Value.YUV v3 (by FirebrandX)"), new("Wavebeam (by nakedarthur)", "Emulation.Option.mesen.mesen_palette.Value.Wavebeam (by nakedarthur)"), new("Custom", "Emulation.Option.mesen.mesen_palette.Value.Custom"), new("Raw", "Emulation.Option.mesen.mesen_palette.Value.Raw")]),
        new("mesen_nospritelimit", "Emulation.Option.mesen.mesen_nospritelimit", "Emulation.Option.mesen.mesen_nospritelimit.Help", "video", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen.mesen_nospritelimit.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_nospritelimit.Value.enabled")]),
        new("mesen_overscan_left", "Emulation.Option.mesen.mesen_overscan_left", "Emulation.Option.mesen.mesen_overscan_left.Help", "video", "None", "None", [new("None", "Emulation.Option.mesen.mesen_overscan_left.Value.None"), new("4px", "4px"), new("8px", "8px"), new("12px", "12px"), new("16px", "16px")]),
        new("mesen_overscan_right", "Emulation.Option.mesen.mesen_overscan_right", "Emulation.Option.mesen.mesen_overscan_right.Help", "video", "None", "None", [new("None", "Emulation.Option.mesen.mesen_overscan_right.Value.None"), new("4px", "4px"), new("8px", "8px"), new("12px", "12px"), new("16px", "16px")]),
        new("mesen_overscan_up", "Emulation.Option.mesen.mesen_overscan_up", "Emulation.Option.mesen.mesen_overscan_up.Help", "video", "None", "None", [new("None", "Emulation.Option.mesen.mesen_overscan_up.Value.None"), new("4px", "4px"), new("8px", "8px"), new("12px", "12px"), new("16px", "16px"), new("20px", "20px"), new("24px", "24px")]),
        new("mesen_overscan_down", "Emulation.Option.mesen.mesen_overscan_down", "Emulation.Option.mesen.mesen_overscan_down.Help", "video", "None", "None", [new("None", "Emulation.Option.mesen.mesen_overscan_down.Value.None"), new("4px", "4px"), new("8px", "8px"), new("12px", "12px"), new("16px", "16px"), new("20px", "20px"), new("24px", "24px")]),
        new("mesen_aspect_ratio", "Emulation.Option.mesen.mesen_aspect_ratio", null, "video", "Auto", "Auto", [new("Auto", "Emulation.Option.mesen.mesen_aspect_ratio.Value.Auto"), new("No Stretching", "Emulation.Option.mesen.mesen_aspect_ratio.Value.No Stretching"), new("NTSC", "Emulation.Option.mesen.mesen_aspect_ratio.Value.NTSC"), new("PAL", "Emulation.Option.mesen.mesen_aspect_ratio.Value.PAL"), new("4:3", "4:3"), new("4:3 (Preserved)", "Emulation.Option.mesen.mesen_aspect_ratio.Value.4:3 (Preserved)"), new("16:9", "16:9"), new("16:9 (Preserved)", "Emulation.Option.mesen.mesen_aspect_ratio.Value.16:9 (Preserved)")]),
        new("mesen_hdpacks", "Emulation.Option.mesen.mesen_hdpacks", null, "video", "enabled", "enabled", [new("disabled", "Emulation.Option.mesen.mesen_hdpacks.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_hdpacks.Value.enabled")]),
        new("mesen_screenrotation", "Emulation.Option.mesen.mesen_screenrotation", "Emulation.Option.mesen.mesen_screenrotation.Help", "video", "None", "None", [new("None", "Emulation.Option.mesen.mesen_screenrotation.Value.None"), new("90 degrees", "Emulation.Option.mesen.mesen_screenrotation.Value.90 degrees"), new("180 degrees", "Emulation.Option.mesen.mesen_screenrotation.Value.180 degrees"), new("270 degrees", "Emulation.Option.mesen.mesen_screenrotation.Value.270 degrees")]),
        new("mesen_fake_stereo", "Emulation.Option.mesen.mesen_fake_stereo", null, "audio", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen.mesen_fake_stereo.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_fake_stereo.Value.enabled")]),
        new("mesen_mute_triangle_ultrasonic", "Emulation.Option.mesen.mesen_mute_triangle_ultrasonic", "Emulation.Option.mesen.mesen_mute_triangle_ultrasonic.Help", "audio", "enabled", "enabled", [new("disabled", "Emulation.Option.mesen.mesen_mute_triangle_ultrasonic.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_mute_triangle_ultrasonic.Value.enabled")]),
        new("mesen_reduce_dmc_popping", "Emulation.Option.mesen.mesen_reduce_dmc_popping", "Emulation.Option.mesen.mesen_reduce_dmc_popping.Help", "audio", "enabled", "enabled", [new("disabled", "Emulation.Option.mesen.mesen_reduce_dmc_popping.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_reduce_dmc_popping.Value.enabled")]),
        new("mesen_swap_duty_cycle", "Emulation.Option.mesen.mesen_swap_duty_cycle", "Emulation.Option.mesen.mesen_swap_duty_cycle.Help", "audio", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen.mesen_swap_duty_cycle.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_swap_duty_cycle.Value.enabled")]),
        new("mesen_disable_noise_mode_flag", "Emulation.Option.mesen.mesen_disable_noise_mode_flag", "Emulation.Option.mesen.mesen_disable_noise_mode_flag.Help", "audio", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen.mesen_disable_noise_mode_flag.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_disable_noise_mode_flag.Value.enabled")]),
        new("mesen_audio_sample_rate", "Emulation.Option.mesen.mesen_audio_sample_rate", null, "audio", "48000", "48000", [new("11025", "11025"), new("22050", "22050"), new("44100", "44100"), new("48000", "48000"), new("96000", "96000")]),
        new("mesen_controllerturbospeed", "Emulation.Option.mesen.mesen_controllerturbospeed", "Emulation.Option.mesen.mesen_controllerturbospeed.Help", "input", "Fast", "Fast", [new("Slow", "Emulation.Option.mesen.mesen_controllerturbospeed.Value.Slow"), new("Normal", "Emulation.Option.mesen.mesen_controllerturbospeed.Value.Normal"), new("Fast", "Emulation.Option.mesen.mesen_controllerturbospeed.Value.Fast"), new("Very Fast", "Emulation.Option.mesen.mesen_controllerturbospeed.Value.Very Fast"), new("Disabled", "Emulation.Option.mesen.mesen_controllerturbospeed.Value.Disabled")]),
        new("mesen_shift_buttons_clockwise", "Emulation.Option.mesen.mesen_shift_buttons_clockwise", null, "input", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen.mesen_shift_buttons_clockwise.Value.disabled"), new("enabled", "Emulation.Option.mesen.mesen_shift_buttons_clockwise.Value.enabled")])
    ];
}
