using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.MesenS.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("mesen-s_ntsc_filter", "Emulation.Option.mesen_s.mesen-s_ntsc_filter", null, "", "Disabled", "Disabled", [new("Disabled", "Emulation.Option.mesen_s.mesen-s_ntsc_filter.Value.Disabled"), new("Composite (Blargg)", "Emulation.Option.mesen_s.mesen-s_ntsc_filter.Value.Composite (Blargg)"), new("S-Video (Blargg)", "Emulation.Option.mesen_s.mesen-s_ntsc_filter.Value.S-Video (Blargg)"), new("RGB (Blargg)", "Emulation.Option.mesen_s.mesen-s_ntsc_filter.Value.RGB (Blargg)"), new("Monochrome (Blargg)", "Emulation.Option.mesen_s.mesen-s_ntsc_filter.Value.Monochrome (Blargg)")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_region", "Emulation.Option.mesen_s.mesen-s_region", null, "", "Auto", "Auto", [new("Auto", "Emulation.Option.mesen_s.mesen-s_region.Value.Auto"), new("NTSC", "Emulation.Option.mesen_s.mesen-s_region.Value.NTSC"), new("PAL", "Emulation.Option.mesen_s.mesen-s_region.Value.PAL")], Tab: EmulationMachineTab.General, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_gbmodel", "Emulation.Option.mesen_s.mesen-s_gbmodel", null, "", "Auto", "Auto", [new("Auto", "Emulation.Option.mesen_s.mesen-s_gbmodel.Value.Auto"), new("Game Boy", "Emulation.Option.mesen_s.mesen-s_gbmodel.Value.Game Boy"), new("Game Boy Color", "Emulation.Option.mesen_s.mesen-s_gbmodel.Value.Game Boy Color"), new("Super Game Boy", "Emulation.Option.mesen_s.mesen-s_gbmodel.Value.Super Game Boy")], Tab: EmulationMachineTab.General, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen-s_sgb2", "Emulation.Option.mesen_s.mesen-s_sgb2", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.mesen_s.mesen-s_sgb2.Value.enabled"), new("disabled", "Emulation.Option.mesen_s.mesen-s_sgb2.Value.disabled")], Tab: EmulationMachineTab.General, MachineIds: OptionMachineConstants.GameBoy),
        new("mesen-s_overscan_vertical", "Emulation.Option.mesen_s.mesen-s_overscan_vertical", null, "", "None", "None", [new("None", "Emulation.Option.mesen_s.mesen-s_overscan_vertical.Value.None"), new("8px", "8px"), new("16px", "16px")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_overscan_horizontal", "Emulation.Option.mesen_s.mesen-s_overscan_horizontal", null, "", "None", "None", [new("None", "Emulation.Option.mesen_s.mesen-s_overscan_horizontal.Value.None"), new("8px", "8px"), new("16px", "16px")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_aspect_ratio", "Emulation.Option.mesen_s.mesen-s_aspect_ratio", null, "", "Auto", "Auto", [new("Auto", "Emulation.Option.mesen_s.mesen-s_aspect_ratio.Value.Auto"), new("No Stretching", "Emulation.Option.mesen_s.mesen-s_aspect_ratio.Value.No Stretching"), new("NTSC", "Emulation.Option.mesen_s.mesen-s_aspect_ratio.Value.NTSC"), new("PAL", "Emulation.Option.mesen_s.mesen-s_aspect_ratio.Value.PAL"), new("4:3", "4:3"), new("16:9", "16:9")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_blend_high_res", "Emulation.Option.mesen_s.mesen-s_blend_high_res", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen_s.mesen-s_blend_high_res.Value.disabled"), new("enabled", "Emulation.Option.mesen_s.mesen-s_blend_high_res.Value.enabled")], Tab: EmulationMachineTab.Video, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_cubic_interpolation", "Emulation.Option.mesen_s.mesen-s_cubic_interpolation", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen_s.mesen-s_cubic_interpolation.Value.disabled"), new("enabled", "Emulation.Option.mesen_s.mesen-s_cubic_interpolation.Value.enabled")], Tab: EmulationMachineTab.Audio, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_overclock", "Emulation.Option.mesen_s.mesen-s_overclock", null, "", "None", "None", [new("None", "Emulation.Option.mesen_s.mesen-s_overclock.Value.None"), new("Low", "Emulation.Option.mesen_s.mesen-s_overclock.Value.Low"), new("Medium", "Emulation.Option.mesen_s.mesen-s_overclock.Value.Medium"), new("High", "Emulation.Option.mesen_s.mesen-s_overclock.Value.High"), new("Very High", "Emulation.Option.mesen_s.mesen-s_overclock.Value.Very High")], Tab: EmulationMachineTab.Cpu, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_overclock_type", "Emulation.Option.mesen_s.mesen-s_overclock_type", null, "", "Before NMI", "Before NMI", [new("Before NMI", "Emulation.Option.mesen_s.mesen-s_overclock_type.Value.Before NMI"), new("After NMI", "Emulation.Option.mesen_s.mesen-s_overclock_type.Value.After NMI")], Tab: EmulationMachineTab.Cpu, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_superfx_overclock", "Emulation.Option.mesen_s.mesen-s_superfx_overclock", null, "", "100%", "100%", [new("100%", "100%"), new("200%", "200%"), new("300%", "300%"), new("400%", "400%"), new("500%", "500%"), new("1000%", "1000%")], Tab: EmulationMachineTab.Cpu, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_ramstate", "Emulation.Option.mesen_s.mesen-s_ramstate", null, "", "Random Values (Default)", "Random Values (Default)", [new("Random Values (Default)", "Emulation.Option.mesen_s.mesen-s_ramstate.Value.Random Values (Default)"), new("All 0s", "Emulation.Option.mesen_s.mesen-s_ramstate.Value.All 0s"), new("All 1s", "Emulation.Option.mesen_s.mesen-s_ramstate.Value.All 1s")], Tab: EmulationMachineTab.Ram, MachineIds: OptionMachineConstants.Snes),
        new("mesen-s_hle_coprocessor", "Emulation.Option.mesen_s.mesen-s_hle_coprocessor", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.mesen_s.mesen-s_hle_coprocessor.Value.disabled"), new("enabled", "Emulation.Option.mesen_s.mesen-s_hle_coprocessor.Value.enabled")], Tab: EmulationMachineTab.Rom, MachineIds: OptionMachineConstants.Snes)
    ];
}
