using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.BeetleVb.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("vb_3dmode", "Emulation.Option.beetle_vb.vb_3dmode", "Emulation.Option.beetle_vb.vb_3dmode.Help", "", "anaglyph", "anaglyph", [new("anaglyph", "Emulation.Option.beetle_vb.vb_3dmode.Value.anaglyph"), new("cyberscope", "Emulation.Option.beetle_vb.vb_3dmode.Value.cyberscope"), new("side-by-side", "Emulation.Option.beetle_vb.vb_3dmode.Value.side-by-side"), new("vli", "Emulation.Option.beetle_vb.vb_3dmode.Value.vli"), new("hli", "Emulation.Option.beetle_vb.vb_3dmode.Value.hli")], Tab: EmulationMachineTab.Video, RequiresRestart: true),
        new("vb_anaglyph_preset", "Emulation.Option.beetle_vb.vb_anaglyph_preset", "Emulation.Option.beetle_vb.vb_anaglyph_preset.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.beetle_vb.vb_anaglyph_preset.Value.disabled"), new("red & blue", "Emulation.Option.beetle_vb.vb_anaglyph_preset.Value.red & blue"), new("red & cyan", "Emulation.Option.beetle_vb.vb_anaglyph_preset.Value.red & cyan"), new("red & electric cyan", "Emulation.Option.beetle_vb.vb_anaglyph_preset.Value.red & electric cyan"), new("green & magenta", "Emulation.Option.beetle_vb.vb_anaglyph_preset.Value.green & magenta"), new("yellow & blue", "Emulation.Option.beetle_vb.vb_anaglyph_preset.Value.yellow & blue")], Tab: EmulationMachineTab.Video),
        new("vb_sidebyside_separation", "Emulation.Option.beetle_vb.vb_sidebyside_separation", "Emulation.Option.beetle_vb.vb_sidebyside_separation.Help", "", "0", "0", [new("0", "0"), new("4", "4"), new("8", "8"), new("12", "12"), new("16", "16"), new("20", "20"), new("24", "24"), new("28", "28"), new("32", "32"), new("36", "36"), new("40", "40"), new("44", "44"), new("48", "48"), new("52", "52"), new("56", "56"), new("60", "60"), new("64", "64"), new("68", "68"), new("72", "72"), new("76", "76"), new("80", "80"), new("84", "84"), new("88", "88"), new("92", "92"), new("96", "96"), new("100", "100"), new("104", "104"), new("108", "108"), new("112", "112"), new("116", "116"), new("120", "120"), new("124", "124"), new("128", "128"), new("132", "132"), new("136", "136"), new("140", "140"), new("144", "144"), new("148", "148"), new("152", "152"), new("156", "156"), new("160", "160"), new("164", "164"), new("168", "168"), new("172", "172"), new("176", "176"), new("180", "180"), new("184", "184"), new("188", "188"), new("192", "192"), new("196", "196"), new("200", "200"), new("204", "204"), new("208", "208"), new("212", "212"), new("216", "216"), new("220", "220"), new("224", "224"), new("228", "228"), new("232", "232"), new("236", "236"), new("240", "240"), new("244", "244"), new("248", "248"), new("252", "252"), new("256", "256")], Tab: EmulationMachineTab.Video),
        new("vb_color_mode", "Emulation.Option.beetle_vb.vb_color_mode", null, "", "black & red", "black & red", [new("black & red", "Emulation.Option.beetle_vb.vb_color_mode.Value.black & red"), new("black & white", "Emulation.Option.beetle_vb.vb_color_mode.Value.black & white"), new("black & blue", "Emulation.Option.beetle_vb.vb_color_mode.Value.black & blue"), new("black & cyan", "Emulation.Option.beetle_vb.vb_color_mode.Value.black & cyan"), new("black & electric cyan", "Emulation.Option.beetle_vb.vb_color_mode.Value.black & electric cyan"), new("black & green", "Emulation.Option.beetle_vb.vb_color_mode.Value.black & green"), new("black & magenta", "Emulation.Option.beetle_vb.vb_color_mode.Value.black & magenta"), new("black & yellow", "Emulation.Option.beetle_vb.vb_color_mode.Value.black & yellow")], Tab: EmulationMachineTab.Video),
        new("vb_right_analog_to_digital", "Emulation.Option.beetle_vb.vb_right_analog_to_digital", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.beetle_vb.vb_right_analog_to_digital.Value.disabled"), new("enabled", "Emulation.Option.beetle_vb.vb_right_analog_to_digital.Value.enabled"), new("invert x", "Emulation.Option.beetle_vb.vb_right_analog_to_digital.Value.invert x"), new("invert y", "Emulation.Option.beetle_vb.vb_right_analog_to_digital.Value.invert y"), new("invert both", "Emulation.Option.beetle_vb.vb_right_analog_to_digital.Value.invert both")], Tab: EmulationMachineTab.Controllers),
        new("vb_opposite_directions", "Emulation.Option.beetle_vb.vb_opposite_directions", "Emulation.Option.beetle_vb.vb_opposite_directions.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.beetle_vb.vb_opposite_directions.Value.disabled"), new("enabled", "Emulation.Option.beetle_vb.vb_opposite_directions.Value.enabled")], Tab: EmulationMachineTab.Controllers),
        new("vb_cpu_emulation", "Emulation.Option.beetle_vb.vb_cpu_emulation", "Emulation.Option.beetle_vb.vb_cpu_emulation.Help", "", "fast", "fast", [new("accurate", "Emulation.Option.beetle_vb.vb_cpu_emulation.Value.accurate"), new("fast", "Emulation.Option.beetle_vb.vb_cpu_emulation.Value.fast")], Tab: EmulationMachineTab.Cpu, RequiresRestart: true)
    ];
}
