namespace GWGUI.Emulation.Sega.Emulators.YabaSanshiro.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("yabasanshiro_force_hle_bios", "Emulation.Option.yabasanshiro.yabasanshiro_force_hle_bios", null, null, "disabled", "disabled", [new("disabled", "Emulation.Option.yabasanshiro.yabasanshiro_force_hle_bios.Value.disabled"), new("enabled", "Emulation.Option.yabasanshiro.yabasanshiro_force_hle_bios.Value.enabled")], Tab: EmulationMachineTab.Rom, RequiresRestart: true),
        new("yabasanshiro_frameskip", "Emulation.Option.yabasanshiro.yabasanshiro_frameskip", null, null, "enabled", "enabled", [new("enabled", "Emulation.Option.yabasanshiro.yabasanshiro_frameskip.Value.enabled"), new("disabled", "Emulation.Option.yabasanshiro.yabasanshiro_frameskip.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("yabasanshiro_addon_cart", "Emulation.Option.yabasanshiro.yabasanshiro_addon_cart", null, null, "4M_extended_ram", "4M_extended_ram", [new("4M_extended_ram", "Emulation.Option.yabasanshiro.yabasanshiro_addon_cart.Value.4M_extended_ram"), new("1M_extended_ram", "Emulation.Option.yabasanshiro.yabasanshiro_addon_cart.Value.1M_extended_ram")], Tab: EmulationMachineTab.Ram, RequiresRestart: true),
        new("yabasanshiro_system_language", "Emulation.Option.yabasanshiro.yabasanshiro_system_language", null, null, "english", "english", [new("english", "Emulation.Option.yabasanshiro.yabasanshiro_system_language.Value.english"), new("deutsch", "Emulation.Option.yabasanshiro.yabasanshiro_system_language.Value.deutsch"), new("french", "Emulation.Option.yabasanshiro.yabasanshiro_system_language.Value.french"), new("spanish", "Emulation.Option.yabasanshiro.yabasanshiro_system_language.Value.spanish"), new("italian", "Emulation.Option.yabasanshiro.yabasanshiro_system_language.Value.italian"), new("japanese", "Emulation.Option.yabasanshiro.yabasanshiro_system_language.Value.japanese")], Tab: EmulationMachineTab.General, RequiresRestart: true),
        new("yabasanshiro_multitap_port1", "Emulation.Option.yabasanshiro.yabasanshiro_multitap_port1", null, null, "disabled", "disabled", [new("disabled", "Emulation.Option.yabasanshiro.yabasanshiro_multitap_port1.Value.disabled"), new("enabled", "Emulation.Option.yabasanshiro.yabasanshiro_multitap_port1.Value.enabled")], Tab: EmulationMachineTab.Controllers, RequiresRestart: false),
        new("yabasanshiro_multitap_port2", "Emulation.Option.yabasanshiro.yabasanshiro_multitap_port2", null, null, "disabled", "disabled", [new("disabled", "Emulation.Option.yabasanshiro.yabasanshiro_multitap_port2.Value.disabled"), new("enabled", "Emulation.Option.yabasanshiro.yabasanshiro_multitap_port2.Value.enabled")], Tab: EmulationMachineTab.Controllers, RequiresRestart: false),
        new("yabasanshiro_polygon_mode", "Emulation.Option.yabasanshiro.yabasanshiro_polygon_mode", null, null, "perspective_correction", "perspective_correction", [new("perspective_correction", "Emulation.Option.yabasanshiro.yabasanshiro_polygon_mode.Value.perspective_correction"), new("gpu_tesselation", "Emulation.Option.yabasanshiro.yabasanshiro_polygon_mode.Value.gpu_tesselation"), new("cpu_tesselation", "Emulation.Option.yabasanshiro.yabasanshiro_polygon_mode.Value.cpu_tesselation")], Tab: EmulationMachineTab.Video, RequiresRestart: true),
        new("yabasanshiro_resolution_mode", "Emulation.Option.yabasanshiro.yabasanshiro_resolution_mode", null, null, "original", "original", [new("original", "Emulation.Option.yabasanshiro.yabasanshiro_resolution_mode.Value.original"), new("2x", "Emulation.Option.yabasanshiro.yabasanshiro_resolution_mode.Value.2x"), new("4x", "Emulation.Option.yabasanshiro.yabasanshiro_resolution_mode.Value.4x"), new("720p", "Emulation.Option.yabasanshiro.yabasanshiro_resolution_mode.Value.720p"), new("1080p", "Emulation.Option.yabasanshiro.yabasanshiro_resolution_mode.Value.1080p"), new("4k", "Emulation.Option.yabasanshiro.yabasanshiro_resolution_mode.Value.4k")], Tab: EmulationMachineTab.Video, RequiresRestart: true),
        new("yabasanshiro_rbg_resolution_mode", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_resolution_mode", null, null, "original", "original", [new("original", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_resolution_mode.Value.original"), new("2x", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_resolution_mode.Value.2x"), new("720p", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_resolution_mode.Value.720p"), new("1080p", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_resolution_mode.Value.1080p"), new("Fit_to_emulation", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_resolution_mode.Value.Fit_to_emulation")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("yabasanshiro_rbg_use_compute_shader", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_use_compute_shader", null, null, "disabled", "disabled", [new("disabled", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_use_compute_shader.Value.disabled"), new("enabled", "Emulation.Option.yabasanshiro.yabasanshiro_rbg_use_compute_shader.Value.enabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
    ];
}
