using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Citra2018.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("citra2018_use_cpu_jit", "Emulation.Option.citra2018.citra2018_use_cpu_jit", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_use_cpu_jit.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_use_cpu_jit.Value.disabled")]),
        new("citra2018_use_hw_renderer", "Emulation.Option.citra2018.citra2018_use_hw_renderer", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_use_hw_renderer.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_use_hw_renderer.Value.disabled")]),
        new("citra2018_use_shader_jit", "Emulation.Option.citra2018.citra2018_use_shader_jit", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_use_shader_jit.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_use_shader_jit.Value.disabled")]),
        new("citra2018_use_hw_shaders", "Emulation.Option.citra2018.citra2018_use_hw_shaders", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_use_hw_shaders.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_use_hw_shaders.Value.disabled")]),
        new("citra2018_use_acc_geo_shaders", "Emulation.Option.citra2018.citra2018_use_acc_geo_shaders", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_use_acc_geo_shaders.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_use_acc_geo_shaders.Value.disabled")]),
        new("citra2018_use_acc_mul", "Emulation.Option.citra2018.citra2018_use_acc_mul", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_use_acc_mul.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_use_acc_mul.Value.disabled")]),
        new("citra2018_resolution_factor", "Emulation.Option.citra2018.citra2018_resolution_factor", null, "", "1x (Native)", "1x (Native)", [new("1x (Native)", "Emulation.Option.citra2018.citra2018_resolution_factor.Value.1x (Native)"), new("2x", "2x"), new("3x", "3x"), new("4x", "4x"), new("5x", "5x"), new("6x", "6x"), new("7x", "7x"), new("8x", "8x"), new("9x", "9x"), new("10x", "10x")]),
        new("citra2018_layout_option", "Emulation.Option.citra2018.citra2018_layout_option", null, "", "Default Top-Bottom Screen", "Default Top-Bottom Screen", [new("Default Top-Bottom Screen", "Emulation.Option.citra2018.citra2018_layout_option.Value.Default Top-Bottom Screen"), new("Single Screen Only", "Emulation.Option.citra2018.citra2018_layout_option.Value.Single Screen Only"), new("Large Screen, Small Screen", "Emulation.Option.citra2018.citra2018_layout_option.Value.Large Screen, Small Screen"), new("Side by Side", "Emulation.Option.citra2018.citra2018_layout_option.Value.Side by Side")]),
        new("citra2018_swap_screen", "Emulation.Option.citra2018.citra2018_swap_screen", null, "", "Top", "Top", [new("Top", "Emulation.Option.citra2018.citra2018_swap_screen.Value.Top"), new("Bottom", "Emulation.Option.citra2018.citra2018_swap_screen.Value.Bottom")]),
        new("citra2018_analog_function", "Emulation.Option.citra2018.citra2018_analog_function", null, "", "C-Stick and Touchscreen Pointer", "C-Stick and Touchscreen Pointer", [new("C-Stick and Touchscreen Pointer", "Emulation.Option.citra2018.citra2018_analog_function.Value.C-Stick and Touchscreen Pointer"), new("Touchscreen Pointer", "Emulation.Option.citra2018.citra2018_analog_function.Value.Touchscreen Pointer"), new("C-Stick", "Emulation.Option.citra2018.citra2018_analog_function.Value.C-Stick")]),
        new("citra2018_deadzone", "Emulation.Option.citra2018.citra2018_deadzone", null, "", "15", "15", [new("15", "15"), new("20", "20"), new("25", "25"), new("30", "30"), new("35", "35"), new("0", "0"), new("5", "5"), new("10", "10")]),
        new("citra2018_mouse_touchscreen", "Emulation.Option.citra2018.citra2018_mouse_touchscreen", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_mouse_touchscreen.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_mouse_touchscreen.Value.disabled")]),
        new("citra2018_mouse_show_pointer", "Emulation.Option.citra2018.citra2018_mouse_show_pointer", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_mouse_show_pointer.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_mouse_show_pointer.Value.disabled")]),
        new("citra2018_use_virtual_sd", "Emulation.Option.citra2018.citra2018_use_virtual_sd", null, "", "enabled", "enabled", [new("enabled", "Emulation.Option.citra2018.citra2018_use_virtual_sd.Value.enabled"), new("disabled", "Emulation.Option.citra2018.citra2018_use_virtual_sd.Value.disabled")]),
        new("citra2018_use_libretro_save_path", "Emulation.Option.citra2018.citra2018_use_libretro_save_path", null, "", "LibRetro Default", "LibRetro Default", [new("LibRetro Default", "Emulation.Option.citra2018.citra2018_use_libretro_save_path.Value.LibRetro Default"), new("Citra Default", "Emulation.Option.citra2018.citra2018_use_libretro_save_path.Value.Citra Default")]),
        new("citra2018_is_new_3ds", "Emulation.Option.citra2018.citra2018_is_new_3ds", null, "", "Old 3DS", "Old 3DS", [new("Old 3DS", "Emulation.Option.citra2018.citra2018_is_new_3ds.Value.Old 3DS"), new("New 3DS", "Emulation.Option.citra2018.citra2018_is_new_3ds.Value.New 3DS")]),
        new("citra2018_region_value", "Emulation.Option.citra2018.citra2018_region_value", null, "", "Auto", "Auto", [new("Auto", "Emulation.Option.citra2018.citra2018_region_value.Value.Auto"), new("Japan", "Emulation.Option.citra2018.citra2018_region_value.Value.Japan"), new("USA", "Emulation.Option.citra2018.citra2018_region_value.Value.USA"), new("Europe", "Emulation.Option.citra2018.citra2018_region_value.Value.Europe"), new("Australia", "Emulation.Option.citra2018.citra2018_region_value.Value.Australia"), new("China", "Emulation.Option.citra2018.citra2018_region_value.Value.China"), new("Korea", "Emulation.Option.citra2018.citra2018_region_value.Value.Korea"), new("Taiwan", "Emulation.Option.citra2018.citra2018_region_value.Value.Taiwan")]),
        new("citra2018_use_gdbstub", "Emulation.Option.citra2018.citra2018_use_gdbstub", null, "", "disabled", "disabled", [new("disabled", "Emulation.Option.citra2018.citra2018_use_gdbstub.Value.disabled"), new("enabled", "Emulation.Option.citra2018.citra2018_use_gdbstub.Value.enabled")])
    ];
}
