using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.Gpsp.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("gpsp_bios", "Emulation.Option.gpsp.gpsp_bios", "Emulation.Option.gpsp.gpsp_bios.Help", "", "auto", "auto", [new("auto", "Emulation.Option.gpsp.gpsp_bios.Value.auto"), new("builtin", "Emulation.Option.gpsp.gpsp_bios.Value.builtin"), new("official", "Emulation.Option.gpsp.gpsp_bios.Value.official")]),
        new("gpsp_boot_mode", "Emulation.Option.gpsp.gpsp_boot_mode", "Emulation.Option.gpsp.gpsp_boot_mode.Help", "", "game", "game", [new("game", "Emulation.Option.gpsp.gpsp_boot_mode.Value.game"), new("bios", "Emulation.Option.gpsp.gpsp_boot_mode.Value.bios")]),
        new("gpsp_drc", "Emulation.Option.gpsp.gpsp_drc", "Emulation.Option.gpsp.gpsp_drc.Help", "", "enabled", "enabled", [new("enabled", "Emulation.Option.gpsp.gpsp_drc.Value.enabled"), new("disabled", "Emulation.Option.gpsp.gpsp_drc.Value.disabled")]),
        new("gpsp_sprlim", "Emulation.Option.gpsp.gpsp_sprlim", "Emulation.Option.gpsp.gpsp_sprlim.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.gpsp.gpsp_sprlim.Value.disabled"), new("enabled", "Emulation.Option.gpsp.gpsp_sprlim.Value.enabled")]),
        new("gpsp_rtc", "Emulation.Option.gpsp.gpsp_rtc", "Emulation.Option.gpsp.gpsp_rtc.Help", "", "auto", "auto", [new("auto", "Emulation.Option.gpsp.gpsp_rtc.Value.auto"), new("enabled", "Emulation.Option.gpsp.gpsp_rtc.Value.enabled"), new("disabled", "Emulation.Option.gpsp.gpsp_rtc.Value.disabled")]),
        new("gpsp_rtc_time_source", "Emulation.Option.gpsp.gpsp_rtc_time_source", "Emulation.Option.gpsp.gpsp_rtc_time_source.Help", "", "deterministic", "deterministic", [new("deterministic", "Emulation.Option.gpsp.gpsp_rtc_time_source.Value.deterministic"), new("system", "Emulation.Option.gpsp.gpsp_rtc_time_source.Value.system")]),
        new("gpsp_serial", "Emulation.Option.gpsp.gpsp_serial", "Emulation.Option.gpsp.gpsp_serial.Help", "", "auto", "auto", [new("auto", "Emulation.Option.gpsp.gpsp_serial.Value.auto"), new("disabled", "Emulation.Option.gpsp.gpsp_serial.Value.disabled"), new("rfu", "Emulation.Option.gpsp.gpsp_serial.Value.rfu"), new("mul_poke", "Emulation.Option.gpsp.gpsp_serial.Value.mul_poke"), new("mul_aw1", "Emulation.Option.gpsp.gpsp_serial.Value.mul_aw1"), new("mul_aw2", "Emulation.Option.gpsp.gpsp_serial.Value.mul_aw2")]),
        new("gpsp_rumble", "Emulation.Option.gpsp.gpsp_rumble", "Emulation.Option.gpsp.gpsp_rumble.Help", "", "auto", "auto", [new("auto", "Emulation.Option.gpsp.gpsp_rumble.Value.auto"), new("enabled", "Emulation.Option.gpsp.gpsp_rumble.Value.enabled"), new("disabled", "Emulation.Option.gpsp.gpsp_rumble.Value.disabled")]),
        new("gpsp_sound_rate", "Emulation.Option.gpsp.gpsp_sound_rate", "Emulation.Option.gpsp.gpsp_sound_rate.Help", "", "32768", "32768", [new("65536", "65536"), new("32768", "32768")]),
        new("gpsp_frameskip", "Emulation.Option.gpsp.gpsp_frameskip", "Emulation.Option.gpsp.gpsp_frameskip.Help", "", "disabled", "disabled", [new("disabled", "Emulation.Option.gpsp.gpsp_frameskip.Value.disabled"), new("auto", "Emulation.Option.gpsp.gpsp_frameskip.Value.auto"), new("auto_threshold", "Emulation.Option.gpsp.gpsp_frameskip.Value.auto_threshold"), new("fixed_interval", "Emulation.Option.gpsp.gpsp_frameskip.Value.fixed_interval")]),
        new("gpsp_frameskip_threshold", "Emulation.Option.gpsp.gpsp_frameskip_threshold", "Emulation.Option.gpsp.gpsp_frameskip_threshold.Help", "", "33", "33", [new("15", "15"), new("18", "18"), new("21", "21"), new("24", "24"), new("27", "27"), new("30", "30"), new("33", "33"), new("36", "36"), new("39", "39"), new("42", "42"), new("45", "45"), new("48", "48"), new("51", "51"), new("54", "54"), new("57", "57"), new("60", "60")]),
        new("gpsp_frameskip_interval", "Emulation.Option.gpsp.gpsp_frameskip_interval", "Emulation.Option.gpsp.gpsp_frameskip_interval.Help", "", "1", "1", [new("0", "0"), new("1", "1"), new("2", "2"), new("3", "3"), new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10")]),
        new("gpsp_color_correction", "Emulation.Option.gpsp.gpsp_color_correction", "Emulation.Option.gpsp.gpsp_color_correction.Help", "", "disabled", "disabled", [new("enabled", "Emulation.Option.gpsp.gpsp_color_correction.Value.enabled"), new("disabled", "Emulation.Option.gpsp.gpsp_color_correction.Value.disabled")]),
        new("gpsp_frame_mixing", "Emulation.Option.gpsp.gpsp_frame_mixing", "Emulation.Option.gpsp.gpsp_frame_mixing.Help", "", "disabled", "disabled", [new("enabled", "Emulation.Option.gpsp.gpsp_frame_mixing.Value.enabled"), new("disabled", "Emulation.Option.gpsp.gpsp_frame_mixing.Value.disabled")]),
        new("gpsp_turbo_period", "Emulation.Option.gpsp.gpsp_turbo_period", "Emulation.Option.gpsp.gpsp_turbo_period.Help", "", "4", "4", [new("4", "4"), new("5", "5"), new("6", "6"), new("7", "7"), new("8", "8"), new("9", "9"), new("10", "10"), new("11", "11"), new("12", "12"), new("13", "13"), new("14", "14"), new("15", "15"), new("16", "16"), new("17", "17"), new("18", "18"), new("19", "19"), new("20", "20"), new("21", "21"), new("22", "22"), new("23", "23"), new("24", "24"), new("25", "25"), new("26", "26"), new("27", "27"), new("28", "28"), new("29", "29"), new("30", "30"), new("31", "31"), new("32", "32"), new("33", "33"), new("34", "34"), new("35", "35"), new("36", "36"), new("37", "37"), new("38", "38"), new("39", "39"), new("40", "40"), new("41", "41"), new("42", "42"), new("43", "43"), new("44", "44"), new("45", "45"), new("46", "46"), new("47", "47"), new("48", "48"), new("49", "49"), new("50", "50"), new("51", "51"), new("52", "52"), new("53", "53"), new("54", "54"), new("55", "55"), new("56", "56"), new("57", "57"), new("58", "58"), new("59", "59"), new("60", "60"), new("61", "61"), new("62", "62"), new("63", "63"), new("64", "64"), new("65", "65"), new("66", "66"), new("67", "67"), new("68", "68"), new("69", "69"), new("70", "70"), new("71", "71"), new("72", "72"), new("73", "73"), new("74", "74"), new("75", "75"), new("76", "76"), new("77", "77"), new("78", "78"), new("79", "79"), new("80", "80"), new("81", "81"), new("82", "82"), new("83", "83"), new("84", "84"), new("85", "85"), new("86", "86"), new("87", "87"), new("88", "88"), new("89", "89"), new("90", "90"), new("91", "91"), new("92", "92"), new("93", "93"), new("94", "94"), new("95", "95"), new("96", "96"), new("97", "97"), new("98", "98"), new("99", "99"), new("100", "100"), new("101", "101"), new("102", "102"), new("103", "103"), new("104", "104"), new("105", "105"), new("106", "106"), new("107", "107"), new("108", "108"), new("109", "109"), new("110", "110"), new("111", "111"), new("112", "112"), new("113", "113"), new("114", "114"), new("115", "115"), new("116", "116"), new("117", "117"), new("118", "118"), new("119", "119"), new("120", "120")])
    ];
}
