namespace GWGUI.Emulation.Amstrad.Common.Machines.Common.Functions;

internal static partial class SettingsDescriptionFunctions
{
    internal static IReadOnlyList<EmulationSettingsBlock> Create(MachineConfiguration configuration)
    {
        var model = ModelCatalog.Get(configuration.Model);
        var options = configuration.Options ?? new Dictionary<string, string>();
        var ram = options.GetValueOrDefault(SettingsConstants.Ram,
            model.RamKib.ToString(System.Globalization.CultureInfo.InvariantCulture));
        return
        [
            Block(SettingsDescriptionFunctionsConstants.General, EmulationMachineTab.General,
                SettingsDescriptionFunctionsConstants.ResourceGeneral,
                SettingsDescriptionFunctionsConstants.IconGeneral, 2,
                Information(SettingsConstants.Model, EmulationMachineTab.General,
                    SettingsDescriptionFunctionsConstants.General,
                    SettingsDescriptionFunctionsConstants.ResourceMachineModel, model.DisplayName),
                Information(SettingsConstants.Emulator, EmulationMachineTab.General,
                    SettingsDescriptionFunctionsConstants.General,
                    SettingsDescriptionFunctionsConstants.ResourceEmulator,
                    SettingsDescriptionFunctionsConstants.Caprice32)),
            Block(SettingsDescriptionFunctionsConstants.Cpu, EmulationMachineTab.Cpu,
                SettingsDescriptionFunctionsConstants.ResourceCpuProcessor,
                SettingsDescriptionFunctionsConstants.IconCpu, 2,
                Information(SettingsConstants.Model + ".cpu", EmulationMachineTab.Cpu,
                    SettingsDescriptionFunctionsConstants.Cpu,
                    SettingsDescriptionFunctionsConstants.ResourceCpuModel,
                    SettingsDescriptionFunctionsConstants.Z80A),
                Information(SettingsConstants.Model + ".frequency", EmulationMachineTab.Cpu,
                    SettingsDescriptionFunctionsConstants.Cpu,
                    SettingsDescriptionFunctionsConstants.ResourceCpuSpeed,
                    SettingsDescriptionFunctionsConstants.CpuFrequency)),
            Block(SettingsDescriptionFunctionsConstants.Memory, EmulationMachineTab.Ram,
                SettingsDescriptionFunctionsConstants.ResourceMemoryMain,
                SettingsDescriptionFunctionsConstants.IconMemory, 1,
                Select(SettingsConstants.Ram, EmulationMachineTab.Ram,
                    SettingsDescriptionFunctionsConstants.Memory,
                    SettingsDescriptionFunctionsConstants.ResourceMemoryMain, ram,
                    new[] { 64, 128, 192, 576 }.Where(value => value >= model.RamKib)
                        .Select(value => Invariant(value.ToString(), $"{value} KiB", value)), true)),
            Block(SettingsDescriptionFunctionsConstants.Firmware, EmulationMachineTab.Rom,
                SettingsDescriptionFunctionsConstants.ResourceRom,
                SettingsDescriptionFunctionsConstants.IconFirmware, 2,
                Information(SettingsConstants.Model + ".rom", EmulationMachineTab.Rom,
                    SettingsDescriptionFunctionsConstants.Firmware,
                    SettingsDescriptionFunctionsConstants.ResourceFirmwareSystemRom,
                    SettingsDescriptionFunctionsConstants.Caprice32)),
            Block(SettingsDescriptionFunctionsConstants.Video, EmulationMachineTab.Video,
                SettingsDescriptionFunctionsConstants.ResourceVideo,
                SettingsDescriptionFunctionsConstants.IconVideo, 2,
                Select(SettingsConstants.VideoResolution, EmulationMachineTab.Video,
                    SettingsDescriptionFunctionsConstants.Video,
                    SettingsDescriptionFunctionsConstants.ResourceVideoResolution,
                    options.GetValueOrDefault(SettingsConstants.VideoResolution,
                        SettingsDescriptionFunctionsConstants.Resolution384),
                    InvariantChoices(SettingsDescriptionFunctionsConstants.Resolution384,
                        SettingsDescriptionFunctionsConstants.Resolution400)),
                Select(SettingsConstants.VideoMonitor, EmulationMachineTab.Video,
                    SettingsDescriptionFunctionsConstants.Video,
                    SettingsDescriptionFunctionsConstants.ResourceVideoMonitor,
                    options.GetValueOrDefault(SettingsConstants.VideoMonitor,
                        SettingsDescriptionFunctionsConstants.Color),
                    [new(SettingsDescriptionFunctionsConstants.Color,
                        SettingsDescriptionFunctionsConstants.ResourceColor),
                     new(SettingsDescriptionFunctionsConstants.Green,
                        SettingsDescriptionFunctionsConstants.ResourceGreen),
                     new(SettingsDescriptionFunctionsConstants.White,
                        SettingsDescriptionFunctionsConstants.ResourceWhite)]),
                Select(SettingsConstants.VideoIntensity, EmulationMachineTab.Video,
                    SettingsDescriptionFunctionsConstants.Video,
                    SettingsDescriptionFunctionsConstants.ResourceVideoIntensity,
                    options.GetValueOrDefault(SettingsConstants.VideoIntensity, "8"),
                    Enumerable.Range(5, 11).Select(value => Invariant(value.ToString(), value.ToString()))),
                Toggle(SettingsConstants.VideoCrop, EmulationMachineTab.Video,
                    SettingsDescriptionFunctionsConstants.Video,
                    SettingsDescriptionFunctionsConstants.ResourceVideoCrop,
                    options.GetValueOrDefault(SettingsConstants.VideoCrop,
                        SettingsDescriptionFunctionsConstants.Disabled)
                        == SettingsDescriptionFunctionsConstants.Enabled)),
            Block(SettingsDescriptionFunctionsConstants.Audio, EmulationMachineTab.Audio,
                SettingsDescriptionFunctionsConstants.ResourceAudio,
                SettingsDescriptionFunctionsConstants.IconAudio, 2,
                Toggle(SettingsConstants.AudioEnabled, EmulationMachineTab.Audio,
                    SettingsDescriptionFunctionsConstants.Audio,
                    SettingsDescriptionFunctionsConstants.ResourceAudioEnabled,
                    configuration.AudioEnabled),
                AudioOutput(configuration.Audio?.OutputDeviceId),
                Select(SettingsConstants.AudioLatency, EmulationMachineTab.Audio,
                    SettingsDescriptionFunctionsConstants.Audio,
                    SettingsDescriptionFunctionsConstants.ResourceAudioLatency,
                    (configuration.Audio?.LatencyMilliseconds ?? 50).ToString(),
                    new[] { 20, 35, 50, 75, 100, 150, 250 }
                        .Select(value => Invariant(value.ToString(), $"{value} ms", value))),
                Toggle(SettingsConstants.FloppySound, EmulationMachineTab.Audio,
                    SettingsDescriptionFunctionsConstants.Audio,
                    SettingsDescriptionFunctionsConstants.ResourceAudioFloppySound,
                    options.GetValueOrDefault(SettingsConstants.FloppySound,
                        SettingsDescriptionFunctionsConstants.Enabled)
                        == SettingsDescriptionFunctionsConstants.Enabled))
        ];
    }
}
