using GWGUI.Domain.Commands.Building;
using GWGUI.Domain.Commands.Execution;
using GWGUI.Domain.Formats;
using GWGUI.Domain.Formats.Detection;
using GWGUI.Domain.Hardware;
using GWGUI.Domain.HostTools;
using GWGUI.Domain.Profiles;
using GWGUI.Domain.Settings;
using GWGUI.App.Contracts.Services.Hardware;
using GWGUI.App.Contracts.Dialogs;
using GWGUI.App.Contracts.Visualization;
using GWGUI.App.Controllers.MainWindow;
using GWGUI.App.Dictionaries.Options;
using GWGUI.App.Enums.Services.Dialogs;
using GWGUI.App.Interfaces.Services.Dialogs;
using GWGUI.App.Interfaces.Services.Navigation;
using GWGUI.App.Localization.Extensions;
using GWGUI.App.Functions.Localization;
using GWGUI.App.Presenters.Conversion;
using GWGUI.App.Services.Dialogs;
using GWGUI.App.Services.DiskImages;
using GWGUI.App.Services.Documentation;
using GWGUI.App.Services.Emulation;
using GWGUI.App.Services.Hardware;
using GWGUI.App.Services.Logging;
using GWGUI.App.Services.Maintenance;
using GWGUI.App.Services.Operations;
using GWGUI.App.Services.Profiles;
using GWGUI.App.Services.Storage;
using GWGUI.App.Services.Terminal;
using GWGUI.App.Services.Visualization;
using GWGUI.App.Services.Windows;
using GWGUI.App.Services.Updates;
using GWGUI.App.ViewModels.Main;
using GWGUI.App.Views.Controls.Common;
using GWGUI.App.Views.Controls.Conversion;
using GWGUI.App.Views.Controls.Options;
using GWGUI.App.Views.Controls.Read;
using GWGUI.App.Views.Controls.Visualization;
using GWGUI.App.Views.Controls.Write;
using GWGUI.App.Views.Dialogs.Common;
using GWGUI.MediaEngine.Visualization;
using System.ComponentModel;
using GWGUI.MediaEngine.Exploration.Results;
using System.IO;
using System.Net.Http;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using GWGUI.MediaEngine;
using GWGUI.MediaEngine.Composition;
using GWGUI.MediaEngine.Decoding;
using GWGUI.MediaEngine.Exploration;
using GWGUI.Infrastructure.Processes;
using GWGUI.Infrastructure.Settings;
using GWGUI.Infrastructure.HostTools;
using GWGUI.Infrastructure.Hardware;
namespace GWGUI.App.Views.Windows.Shell;

public partial class MainWindow : Window
{
    private ReadImageSection ReadImageBlock => ReadTabBlock.ImageBlock;
    private ProfileSection ReadProfileBlock => ReadTabBlock.ProfileBlock;
    private PathSection ReadFolderBlock => ReadTabBlock.FolderBlock;
    private ReadFileNameSection ReadFileNameBlock => ReadTabBlock.FileNameBlock;
    private ReadAdvancedSection ReadAdvancedBlock => ReadTabBlock.AdvancedBlock;
    private ReadCompletionBanner ReadCompletionBlock => ReadTabBlock.CompletionBlock;
    private Button ReadExecuteButton => ReadTabBlock.ExecuteActionButton;
    private WriteAdvancedSection WriteAdvancedBlock => WriteTabBlock.AdvancedBlock;
    private PathSection WriteSourceBlock => WriteTabBlock.SourceBlock;
    private ProfileSection WriteProfileBlock => WriteTabBlock.ProfileBlock;
    private WriteFormatSection WriteFormatBlock => WriteTabBlock.FormatBlock;
    private Button WriteExecuteButton => WriteTabBlock.ExecuteActionButton;
    private ConversionAdvancedSection ConvertAdvancedBlock => ConvertTabBlock.AdvancedBlock;
    private PathSection ConvertSourceBlock => ConvertTabBlock.SourceBlock;
    private ProfileSection ConvertProfileBlock => ConvertTabBlock.ProfileBlock;
    private ConversionOutputSection ConvertOutputBlock => ConvertTabBlock.OutputBlock;
    private ConversionFormatsSection ConvertFormatsBlock => ConvertTabBlock.FormatsBlock;
    private Button ConvertExecuteButton => ConvertTabBlock.ExecuteActionButton;
    private VisualizerHeaderSection VisualizerHeader => VisualizerTabBlock.Header;
    private VisualizerTrackOverview VisualizerTrackOverview => VisualizerTabBlock.Overview;
    private ListBox ToolsList => ToolsTabBlock.ToolsList;
    private Border ErasePanel => ToolsTabBlock.ErasePanel;
    private CheckBox EraseTracksEnabled => ToolsTabBlock.EraseTracksEnabled;
    private TextBox EraseTracksValue => ToolsTabBlock.EraseTracksValue;
    private CheckBox EraseRevsEnabled => ToolsTabBlock.EraseRevsEnabled;
    private TextBox EraseRevsValue => ToolsTabBlock.EraseRevsValue;
    private TextBox EraseExpertArguments => ToolsTabBlock.EraseExpertArguments;
    private Button EraseExecuteButton => ToolsTabBlock.EraseExecuteButton;
    private Border CleanPanel => ToolsTabBlock.CleanPanel;
    private CheckBox CleanCylindersEnabled => ToolsTabBlock.CleanCylindersEnabled;
    private TextBox CleanCylindersValue => ToolsTabBlock.CleanCylindersValue;
    private CheckBox CleanPassesEnabled => ToolsTabBlock.CleanPassesEnabled;
    private TextBox CleanPassesValue => ToolsTabBlock.CleanPassesValue;
    private CheckBox CleanLingerEnabled => ToolsTabBlock.CleanLingerEnabled;
    private TextBox CleanLingerValue => ToolsTabBlock.CleanLingerValue;
    private TextBox CleanExpertArguments => ToolsTabBlock.CleanExpertArguments;
    private Button CleanExecuteButton => ToolsTabBlock.CleanExecuteButton;
    private RadioButton RawScpRadio => ReadImageBlock.RawScpRadio;
    private RadioButton KnownFormatRadio => ReadImageBlock.KnownFormatRadio;
    private Grid KnownFormatPanel => ReadImageBlock.KnownFormatPanel;
    private ComboBox ReadFamilyCombo => ReadImageBlock.FamilyCombo;
    private ComboBox ReadFormatCombo => ReadImageBlock.FormatCombo;
    private ComboBox ReadExtensionCombo => ReadImageBlock.ExtensionCombo;
    private ComboBox ReadProfileCombo => ReadProfileBlock.ProfileCombo;
    private ComboBox WriteProfileCombo => WriteProfileBlock.ProfileCombo;
    private TextBox WriteSourceText => WriteSourceBlock.Input;
    private TextBlock WriteDetectionText => WriteFormatBlock.DetectionText;
    private ComboBox WriteFormatCombo => WriteFormatBlock.FormatCombo;
    private CheckBox WriteNoVerify => WriteAdvancedBlock.NoVerifyCheckBox;
    private CheckBox WriteDiskDefsEnabled => WriteAdvancedBlock.DiskDefinitionsEnabled;
    private TextBox WriteDiskDefsValue => WriteAdvancedBlock.DiskDefinitionsValue;
    private ComboBox ConvertProfileCombo => ConvertProfileBlock.ProfileCombo;
    private TextBox ConvertSourceText => ConvertSourceBlock.Input;
    private TextBox ConvertOutputName => ConvertOutputBlock.OutputNameTextBox;
    private CheckBox ConvertTags => ConvertOutputBlock.TagsCheckBox;
    private TextBlock ConvertSourceInfo => ConvertOutputBlock.SourceInformation;
    private CheckBox ConvertTracksEnabled => ConvertAdvancedBlock.TracksEnabledCheckBox;
    private CheckBox ConvertDiskDefsEnabled => ConvertAdvancedBlock.DiskDefinitionsEnabled;
    private TextBox ConvertDiskDefsValue => ConvertAdvancedBlock.DiskDefinitionsValue;
    private TextBox ReadFolder => ReadFolderBlock.Input;
    private TextBox ReadFileName => ReadFileNameBlock.FileNameTextBox;
    private TextBox ReadExtensionText => ReadFileNameBlock.ExtensionTextBox;
    private CheckBox ReadRevsEnabled => ReadAdvancedBlock.RevsEnabledCheckBox;
    private TextBox CommandPreview => TerminalBlock?.CommandTextBox!;
    private TextBox LogOutput => TerminalBlock?.OutputTextBox!;
    private ComboBox ScpDecoderCombo => VisualizerHeader.DecoderCombo;
    private TextBlock HardwareStatusText => StatusBarBlock.HardwareText;
    private ComboBox HardwareSelector => StatusBarBlock.HardwareChoices;
    private StatusBarItem ProfileStatusItem => StatusBarBlock.ProfileItem;
    private ProgressBar OperationProgress => StatusBarBlock.ProgressBar;
    private TrackProgressStrip Face0TrackProgress => StatusBarBlock.Face0Progress;
}
