namespace GWGUI.Emulation.Sega.Emulators.ClownMDEmu.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("clownmdemu_disable_sprite_plane", "Emulation.Option.clownmdemu.clownmdemu_disable_sprite_plane", "Emulation.Option.clownmdemu.clownmdemu_disable_sprite_plane.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_sprite_plane.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_sprite_plane.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("clownmdemu_disable_window_plane", "Emulation.Option.clownmdemu.clownmdemu_disable_window_plane", "Emulation.Option.clownmdemu.clownmdemu_disable_window_plane.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_window_plane.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_window_plane.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("clownmdemu_disable_plane_a", "Emulation.Option.clownmdemu.clownmdemu_disable_plane_a", "Emulation.Option.clownmdemu.clownmdemu_disable_plane_a.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_plane_a.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_plane_a.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("clownmdemu_disable_plane_b", "Emulation.Option.clownmdemu.clownmdemu_disable_plane_b", "Emulation.Option.clownmdemu.clownmdemu_disable_plane_b.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_plane_b.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_plane_b.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("clownmdemu_disable_fm1", "Emulation.Option.clownmdemu.clownmdemu_disable_fm1", "Emulation.Option.clownmdemu.clownmdemu_disable_fm1.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm1.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm1.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_fm2", "Emulation.Option.clownmdemu.clownmdemu_disable_fm2", "Emulation.Option.clownmdemu.clownmdemu_disable_fm2.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm2.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm2.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_fm3", "Emulation.Option.clownmdemu.clownmdemu_disable_fm3", "Emulation.Option.clownmdemu.clownmdemu_disable_fm3.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm3.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm3.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_fm4", "Emulation.Option.clownmdemu.clownmdemu_disable_fm4", "Emulation.Option.clownmdemu.clownmdemu_disable_fm4.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm4.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm4.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_fm5", "Emulation.Option.clownmdemu.clownmdemu_disable_fm5", "Emulation.Option.clownmdemu.clownmdemu_disable_fm5.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm5.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm5.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_fm6", "Emulation.Option.clownmdemu.clownmdemu_disable_fm6", "Emulation.Option.clownmdemu.clownmdemu_disable_fm6.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm6.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_fm6.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_dac", "Emulation.Option.clownmdemu.clownmdemu_disable_dac", "Emulation.Option.clownmdemu.clownmdemu_disable_dac.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_dac.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_dac.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_psg1", "Emulation.Option.clownmdemu.clownmdemu_disable_psg1", "Emulation.Option.clownmdemu.clownmdemu_disable_psg1.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_psg1.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_psg1.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_psg2", "Emulation.Option.clownmdemu.clownmdemu_disable_psg2", "Emulation.Option.clownmdemu.clownmdemu_disable_psg2.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_psg2.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_psg2.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_psg3", "Emulation.Option.clownmdemu.clownmdemu_disable_psg3", "Emulation.Option.clownmdemu.clownmdemu_disable_psg3.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_psg3.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_psg3.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_psg_noise", "Emulation.Option.clownmdemu.clownmdemu_disable_psg_noise", "Emulation.Option.clownmdemu.clownmdemu_disable_psg_noise.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_psg_noise.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_psg_noise.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_pcm1", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm1", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm1.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm1.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm1.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_pcm2", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm2", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm2.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm2.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm2.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_pcm3", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm3", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm3.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm3.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm3.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_pcm4", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm4", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm4.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm4.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm4.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_pcm5", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm5", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm5.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm5.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm5.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_pcm6", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm6", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm6.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm6.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm6.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_pcm7", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm7", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm7.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm7.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm7.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_pcm8", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm8", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm8.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm8.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_pcm8.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_disable_cdda", "Emulation.Option.clownmdemu.clownmdemu_disable_cdda", "Emulation.Option.clownmdemu.clownmdemu_disable_cdda.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_disable_cdda.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_disable_cdda.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_tv_standard", "Emulation.Option.clownmdemu.clownmdemu_tv_standard", "Emulation.Option.clownmdemu.clownmdemu_tv_standard.Description", null, "ntsc", "ntsc", [new("pal", "Emulation.Option.clownmdemu.clownmdemu_tv_standard.Value.pal"), new("ntsc", "Emulation.Option.clownmdemu.clownmdemu_tv_standard.Value.ntsc")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("clownmdemu_overseas_region", "Emulation.Option.clownmdemu.clownmdemu_overseas_region", "Emulation.Option.clownmdemu.clownmdemu_overseas_region.Description", null, "elsewhere", "elsewhere", [new("elsewhere", "Emulation.Option.clownmdemu.clownmdemu_overseas_region.Value.elsewhere"), new("japan", "Emulation.Option.clownmdemu.clownmdemu_overseas_region.Value.japan")], Tab: EmulationMachineTab.General, RequiresRestart: false),
        new("clownmdemu_input_protocol", "Emulation.Option.clownmdemu.clownmdemu_input_protocol", "Emulation.Option.clownmdemu.clownmdemu_input_protocol.Description", null, "standard", "standard", [new("standard", "Emulation.Option.clownmdemu.clownmdemu_input_protocol.Value.standard"), new("sega", "Emulation.Option.clownmdemu.clownmdemu_input_protocol.Value.sega"), new("ea", "Emulation.Option.clownmdemu.clownmdemu_input_protocol.Value.ea")], Tab: EmulationMachineTab.Controllers, RequiresRestart: false),
        new("clownmdemu_cd_addon", "Emulation.Option.clownmdemu.clownmdemu_cd_addon", "Emulation.Option.clownmdemu.clownmdemu_cd_addon.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_cd_addon.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_cd_addon.Value.disabled")], Tab: EmulationMachineTab.General, RequiresRestart: false),
        new("clownmdemu_tall_interlace_mode_2", "Emulation.Option.clownmdemu.clownmdemu_tall_interlace_mode_2", "Emulation.Option.clownmdemu.clownmdemu_tall_interlace_mode_2.Description", null, "disabled", "disabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_tall_interlace_mode_2.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_tall_interlace_mode_2.Value.disabled")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("clownmdemu_widescreen_tiles", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Description", null, "0", "0", [new("0", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.0"), new("1", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.1"), new("2", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.2"), new("3", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.3"), new("4", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.4"), new("5", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.5"), new("6", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.6"), new("7", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.7"), new("8", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.8"), new("9", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.9"), new("10", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.10"), new("11", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.11"), new("12", "Emulation.Option.clownmdemu.clownmdemu_widescreen_tiles.Value.12")], Tab: EmulationMachineTab.Video, RequiresRestart: false),
        new("clownmdemu_lowpass_filter", "Emulation.Option.clownmdemu.clownmdemu_lowpass_filter", "Emulation.Option.clownmdemu.clownmdemu_lowpass_filter.Description", null, "enabled", "enabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_lowpass_filter.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_lowpass_filter.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
        new("clownmdemu_ladder_effect", "Emulation.Option.clownmdemu.clownmdemu_ladder_effect", "Emulation.Option.clownmdemu.clownmdemu_ladder_effect.Description", null, "enabled", "enabled", [new("enabled", "Emulation.Option.clownmdemu.clownmdemu_ladder_effect.Value.enabled"), new("disabled", "Emulation.Option.clownmdemu.clownmdemu_ladder_effect.Value.disabled")], Tab: EmulationMachineTab.Audio, RequiresRestart: false),
    ];
}
