using GWGUI.Emulation.Nec.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nec.Emulators.NekoProjectII.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOptionDefinition> All { get; } =
    [
        new("np2_model", "Emulation.Nec.CoreOptions.np2_model", "VX", EmulationMachineTab.Cpu,
            [new("VX", "Emulation.Nec.CoreOptions.np2_model.Choice0"), new("EPSON", "Emulation.Nec.CoreOptions.np2_model.Choice1"), new("VM", "Emulation.Nec.CoreOptions.np2_model.Choice2")]),
        new("np2_clk_base", "Emulation.Nec.CoreOptions.np2_clk_base", "2.4576 MHz", EmulationMachineTab.Cpu,
            [new("2.4576 MHz", "2.4576 MHz", IsInvariant: true), new("1.9968 MHz", "1.9968 MHz", IsInvariant: true)]),
        new("np2_clk_mult", "Emulation.Nec.CoreOptions.np2_clk_mult", "4", EmulationMachineTab.Cpu,
            [new("4", "4", IsInvariant: true), new("5", "5", IsInvariant: true), new("6", "6", IsInvariant: true), new("7", "7", IsInvariant: true), new("8", "8", IsInvariant: true), new("9", "9", IsInvariant: true), new("10", "10", IsInvariant: true), new("11", "11", IsInvariant: true), new("12", "12", IsInvariant: true), new("13", "13", IsInvariant: true), new("14", "14", IsInvariant: true), new("15", "15", IsInvariant: true), new("16", "16", IsInvariant: true), new("17", "17", IsInvariant: true), new("18", "18", IsInvariant: true), new("19", "19", IsInvariant: true), new("20", "20", IsInvariant: true), new("21", "21", IsInvariant: true), new("22", "22", IsInvariant: true), new("23", "23", IsInvariant: true), new("24", "24", IsInvariant: true), new("25", "25", IsInvariant: true), new("26", "26", IsInvariant: true), new("27", "27", IsInvariant: true), new("28", "28", IsInvariant: true), new("29", "29", IsInvariant: true), new("30", "30", IsInvariant: true), new("31", "31", IsInvariant: true), new("32", "32", IsInvariant: true), new("1", "1", IsInvariant: true), new("2", "2", IsInvariant: true), new("3", "3", IsInvariant: true)]),
        new("np2_ExMemory", "Emulation.Nec.CoreOptions.np2_ExMemory", "2", EmulationMachineTab.Ram,
            [new("2", "2", IsInvariant: true), new("3", "3", IsInvariant: true), new("4", "4", IsInvariant: true), new("5", "5", IsInvariant: true), new("6", "6", IsInvariant: true), new("7", "7", IsInvariant: true), new("8", "8", IsInvariant: true), new("9", "9", IsInvariant: true), new("10", "10", IsInvariant: true), new("11", "11", IsInvariant: true), new("12", "12", IsInvariant: true), new("13", "13", IsInvariant: true), new("14", "14", IsInvariant: true), new("15", "15", IsInvariant: true), new("16", "16", IsInvariant: true), new("24", "24", IsInvariant: true), new("32", "32", IsInvariant: true), new("48", "48", IsInvariant: true), new("64", "64", IsInvariant: true), new("1", "1", IsInvariant: true)]),
        new("np2_skipline", "Emulation.Nec.CoreOptions.np2_skipline", "Full 255 lines", EmulationMachineTab.Video,
            [new("Full 255 lines", "Emulation.Nec.CoreOptions.np2_skipline.Choice0"), new("ON", "Emulation.Nec.CoreOptions.np2_skipline.Choice1"), new("OFF", "Emulation.Nec.CoreOptions.np2_skipline.Choice2")]),
        new("np2_SNDboard", "Emulation.Nec.CoreOptions.np2_SNDboard", "PC9801-86", EmulationMachineTab.Audio,
            [new("PC9801-86", "PC9801-86", IsInvariant: true), new("PC9801-26K + 86", "PC9801-26K + 86", IsInvariant: true), new("PC9801-86 + Chibi-Oto", "PC9801-86 + Chibi-Oto", IsInvariant: true), new("PC9801-118", "PC9801-118", IsInvariant: true), new("Speak Board", "Emulation.Nec.CoreOptions.np2_SNDboard.Choice4"), new("Spark Board", "Emulation.Nec.CoreOptions.np2_SNDboard.Choice5"), new("Sound Orchestra", "Emulation.Nec.CoreOptions.np2_SNDboard.Choice6"), new("Sound Orchestra-V", "Emulation.Nec.CoreOptions.np2_SNDboard.Choice7"), new("AMD-98", "Emulation.Nec.CoreOptions.np2_SNDboard.Choice8"), new("None", "Emulation.Nec.CoreOptions.np2_SNDboard.Choice9"), new("PC9801-14", "PC9801-14", IsInvariant: true), new("PC9801-26K", "PC9801-26K", IsInvariant: true)]),
        new("np2_jast_snd", "Emulation.Nec.CoreOptions.np2_jast_snd", "OFF", EmulationMachineTab.Audio,
            [new("OFF", "Emulation.Nec.CoreOptions.np2_jast_snd.Choice0"), new("ON", "Emulation.Nec.CoreOptions.np2_jast_snd.Choice1")]),
        new("np2_volume_F", "Emulation.Nec.CoreOptions.np2_volume_F", "64", EmulationMachineTab.Audio,
            [new("64", "64", IsInvariant: true), new("68", "68", IsInvariant: true), new("72", "72", IsInvariant: true), new("76", "76", IsInvariant: true), new("80", "80", IsInvariant: true), new("84", "84", IsInvariant: true), new("88", "88", IsInvariant: true), new("92", "92", IsInvariant: true), new("96", "96", IsInvariant: true), new("100", "100", IsInvariant: true), new("104", "104", IsInvariant: true), new("108", "108", IsInvariant: true), new("112", "112", IsInvariant: true), new("116", "116", IsInvariant: true), new("120", "120", IsInvariant: true), new("124", "124", IsInvariant: true), new("128", "128", IsInvariant: true), new("0", "0", IsInvariant: true), new("4", "4", IsInvariant: true), new("8", "8", IsInvariant: true), new("12", "12", IsInvariant: true), new("16", "16", IsInvariant: true), new("20", "20", IsInvariant: true), new("24", "24", IsInvariant: true), new("28", "28", IsInvariant: true), new("32", "32", IsInvariant: true), new("36", "36", IsInvariant: true), new("40", "40", IsInvariant: true), new("44", "44", IsInvariant: true), new("48", "48", IsInvariant: true), new("52", "52", IsInvariant: true), new("56", "56", IsInvariant: true), new("60", "60", IsInvariant: true)]),
        new("np2_volume_S", "Emulation.Nec.CoreOptions.np2_volume_S", "64", EmulationMachineTab.Audio,
            [new("64", "64", IsInvariant: true), new("68", "68", IsInvariant: true), new("72", "72", IsInvariant: true), new("76", "76", IsInvariant: true), new("80", "80", IsInvariant: true), new("84", "84", IsInvariant: true), new("88", "88", IsInvariant: true), new("92", "92", IsInvariant: true), new("96", "96", IsInvariant: true), new("100", "100", IsInvariant: true), new("104", "104", IsInvariant: true), new("108", "108", IsInvariant: true), new("112", "112", IsInvariant: true), new("116", "116", IsInvariant: true), new("120", "120", IsInvariant: true), new("124", "124", IsInvariant: true), new("128", "128", IsInvariant: true), new("0", "0", IsInvariant: true), new("4", "4", IsInvariant: true), new("8", "8", IsInvariant: true), new("12", "12", IsInvariant: true), new("16", "16", IsInvariant: true), new("20", "20", IsInvariant: true), new("24", "24", IsInvariant: true), new("28", "28", IsInvariant: true), new("32", "32", IsInvariant: true), new("36", "36", IsInvariant: true), new("40", "40", IsInvariant: true), new("44", "44", IsInvariant: true), new("48", "48", IsInvariant: true), new("52", "52", IsInvariant: true), new("56", "56", IsInvariant: true), new("60", "60", IsInvariant: true)]),
        new("np2_volume_A", "Emulation.Nec.CoreOptions.np2_volume_A", "64", EmulationMachineTab.Audio,
            [new("64", "64", IsInvariant: true), new("68", "68", IsInvariant: true), new("72", "72", IsInvariant: true), new("76", "76", IsInvariant: true), new("80", "80", IsInvariant: true), new("84", "84", IsInvariant: true), new("88", "88", IsInvariant: true), new("92", "92", IsInvariant: true), new("96", "96", IsInvariant: true), new("100", "100", IsInvariant: true), new("104", "104", IsInvariant: true), new("108", "108", IsInvariant: true), new("112", "112", IsInvariant: true), new("116", "116", IsInvariant: true), new("120", "120", IsInvariant: true), new("124", "124", IsInvariant: true), new("128", "128", IsInvariant: true), new("0", "0", IsInvariant: true), new("4", "4", IsInvariant: true), new("8", "8", IsInvariant: true), new("12", "12", IsInvariant: true), new("16", "16", IsInvariant: true), new("20", "20", IsInvariant: true), new("24", "24", IsInvariant: true), new("28", "28", IsInvariant: true), new("32", "32", IsInvariant: true), new("36", "36", IsInvariant: true), new("40", "40", IsInvariant: true), new("44", "44", IsInvariant: true), new("48", "48", IsInvariant: true), new("52", "52", IsInvariant: true), new("56", "56", IsInvariant: true), new("60", "60", IsInvariant: true)]),
        new("np2_volume_P", "Emulation.Nec.CoreOptions.np2_volume_P", "64", EmulationMachineTab.Audio,
            [new("64", "64", IsInvariant: true), new("68", "68", IsInvariant: true), new("72", "72", IsInvariant: true), new("76", "76", IsInvariant: true), new("80", "80", IsInvariant: true), new("84", "84", IsInvariant: true), new("88", "88", IsInvariant: true), new("92", "92", IsInvariant: true), new("96", "96", IsInvariant: true), new("100", "100", IsInvariant: true), new("104", "104", IsInvariant: true), new("108", "108", IsInvariant: true), new("112", "112", IsInvariant: true), new("116", "116", IsInvariant: true), new("120", "120", IsInvariant: true), new("124", "124", IsInvariant: true), new("128", "128", IsInvariant: true), new("0", "0", IsInvariant: true), new("4", "4", IsInvariant: true), new("8", "8", IsInvariant: true), new("12", "12", IsInvariant: true), new("16", "16", IsInvariant: true), new("20", "20", IsInvariant: true), new("24", "24", IsInvariant: true), new("28", "28", IsInvariant: true), new("32", "32", IsInvariant: true), new("36", "36", IsInvariant: true), new("40", "40", IsInvariant: true), new("44", "44", IsInvariant: true), new("48", "48", IsInvariant: true), new("52", "52", IsInvariant: true), new("56", "56", IsInvariant: true), new("60", "60", IsInvariant: true)]),
        new("np2_volume_R", "Emulation.Nec.CoreOptions.np2_volume_R", "64", EmulationMachineTab.Audio,
            [new("64", "64", IsInvariant: true), new("68", "68", IsInvariant: true), new("72", "72", IsInvariant: true), new("76", "76", IsInvariant: true), new("80", "80", IsInvariant: true), new("84", "84", IsInvariant: true), new("88", "88", IsInvariant: true), new("92", "92", IsInvariant: true), new("96", "96", IsInvariant: true), new("100", "100", IsInvariant: true), new("104", "104", IsInvariant: true), new("108", "108", IsInvariant: true), new("112", "112", IsInvariant: true), new("116", "116", IsInvariant: true), new("120", "120", IsInvariant: true), new("124", "124", IsInvariant: true), new("128", "128", IsInvariant: true), new("0", "0", IsInvariant: true), new("4", "4", IsInvariant: true), new("8", "8", IsInvariant: true), new("12", "12", IsInvariant: true), new("16", "16", IsInvariant: true), new("20", "20", IsInvariant: true), new("24", "24", IsInvariant: true), new("28", "28", IsInvariant: true), new("32", "32", IsInvariant: true), new("36", "36", IsInvariant: true), new("40", "40", IsInvariant: true), new("44", "44", IsInvariant: true), new("48", "48", IsInvariant: true), new("52", "52", IsInvariant: true), new("56", "56", IsInvariant: true), new("60", "60", IsInvariant: true)]),
        new("np2_Seek_Snd", "Emulation.Nec.CoreOptions.np2_Seek_Snd", "OFF", EmulationMachineTab.Audio,
            [new("OFF", "Emulation.Nec.CoreOptions.np2_Seek_Snd.Choice0"), new("ON", "Emulation.Nec.CoreOptions.np2_Seek_Snd.Choice1")]),
        new("np2_Seek_Vol", "Emulation.Nec.CoreOptions.np2_Seek_Vol", "80", EmulationMachineTab.Audio,
            [new("80", "80", IsInvariant: true), new("84", "84", IsInvariant: true), new("88", "88", IsInvariant: true), new("92", "92", IsInvariant: true), new("96", "96", IsInvariant: true), new("100", "100", IsInvariant: true), new("104", "104", IsInvariant: true), new("108", "108", IsInvariant: true), new("112", "112", IsInvariant: true), new("116", "116", IsInvariant: true), new("120", "120", IsInvariant: true), new("124", "124", IsInvariant: true), new("128", "128", IsInvariant: true), new("0", "0", IsInvariant: true), new("4", "4", IsInvariant: true), new("8", "8", IsInvariant: true), new("12", "12", IsInvariant: true), new("16", "16", IsInvariant: true), new("20", "20", IsInvariant: true), new("24", "24", IsInvariant: true), new("28", "28", IsInvariant: true), new("32", "32", IsInvariant: true), new("36", "36", IsInvariant: true), new("40", "40", IsInvariant: true), new("44", "44", IsInvariant: true), new("48", "48", IsInvariant: true), new("52", "52", IsInvariant: true), new("56", "56", IsInvariant: true), new("60", "60", IsInvariant: true), new("64", "64", IsInvariant: true), new("68", "68", IsInvariant: true), new("72", "72", IsInvariant: true), new("76", "76", IsInvariant: true)]),
        new("np2_BEEP_vol", "Emulation.Nec.CoreOptions.np2_BEEP_vol", "3", EmulationMachineTab.Audio,
            [new("3", "3", IsInvariant: true), new("0", "0", IsInvariant: true), new("1", "1", IsInvariant: true), new("2", "2", IsInvariant: true)]),
        new("np2_GUI_controller", "Emulation.Nec.CoreOptions.np2_GUI_controller", "MOUSE", EmulationMachineTab.Video,
            [new("MOUSE", "Emulation.Nec.CoreOptions.np2_GUI_controller.Choice0"), new("JOY0", "Emulation.Nec.CoreOptions.np2_GUI_controller.Choice1")]),
        new("np2_GUIJOY_PAS", "Emulation.Nec.CoreOptions.np2_GUIJOY_PAS", "3", EmulationMachineTab.Controllers,
            [new("3", "3", IsInvariant: true), new("4", "4", IsInvariant: true), new("5", "5", IsInvariant: true), new("1", "1", IsInvariant: true), new("2", "2", IsInvariant: true)]),
    ];
}
