using GWGUI.Emulation.Nintendo.Emulators.Common.Interop.Contracts;

namespace GWGUI.Emulation.Nintendo.Emulators.BsnesJg.Constants;

internal static class OptionConstants
{
    internal static IReadOnlyList<CoreOption> All { get; } =
    [
        new("bsnes_jg_coproc_delaysync", "Emulation.Option.bsnes_jg.bsnes_jg_coproc_delaysync", "Emulation.Option.bsnes_jg.bsnes_jg_coproc_delaysync.Help", "", "off", "off", [new("off", "Emulation.Option.bsnes_jg.bsnes_jg_coproc_delaysync.Value.off"), new("on", "Emulation.Option.Common.Value.Enabled")]),
        new("bsnes_jg_coproc_preferhle", "Emulation.Option.bsnes_jg.bsnes_jg_coproc_preferhle", "Emulation.Option.bsnes_jg.bsnes_jg_coproc_preferhle.Help", "", "off", "off", [new("off", "Emulation.Option.bsnes_jg.bsnes_jg_coproc_preferhle.Value.off"), new("on", "Emulation.Option.Common.Value.Enabled")]),
        new("bsnes_jg_hotfixes", "Emulation.Option.bsnes_jg.bsnes_jg_hotfixes", "Emulation.Option.bsnes_jg.bsnes_jg_hotfixes.Help", "", "off", "off", [new("off", "Emulation.Option.bsnes_jg.bsnes_jg_hotfixes.Value.off"), new("on", "Emulation.Option.Common.Value.Enabled")]),
        new("bsnes_jg_runahead", "Emulation.Option.bsnes_jg.bsnes_jg_runahead", "Emulation.Option.bsnes_jg.bsnes_jg_runahead.Help", "", "0", "0", [new("0", "Emulation.Option.bsnes_jg.bsnes_jg_runahead.Value.0"), new("1", "Emulation.Option.bsnes_jg.bsnes_jg_runahead.Value.1"), new("2", "Emulation.Option.bsnes_jg.bsnes_jg_runahead.Value.2"), new("3", "Emulation.Option.bsnes_jg.bsnes_jg_runahead.Value.3"), new("4", "Emulation.Option.bsnes_jg.bsnes_jg_runahead.Value.4")]),
        new("bsnes_jg_low_latency_audio", "Emulation.Option.bsnes_jg.bsnes_jg_low_latency_audio", "Emulation.Option.bsnes_jg.bsnes_jg_low_latency_audio.Help", "", "off", "off", [new("off", "Emulation.Option.bsnes_jg.bsnes_jg_low_latency_audio.Value.off"), new("on", "Emulation.Option.Common.Value.Enabled")]),
        new("bsnes_jg_rsqual", "Emulation.Option.bsnes_jg.bsnes_jg_rsqual", "Emulation.Option.bsnes_jg.bsnes_jg_rsqual.Help", "", "fast", "fast", [new("fast", "Emulation.Option.bsnes_jg.bsnes_jg_rsqual.Value.fast"), new("medium", "Emulation.Option.bsnes_jg.bsnes_jg_rsqual.Value.medium"), new("best", "Emulation.Option.bsnes_jg.bsnes_jg_rsqual.Value.best")]),
        new("bsnes_jg_spc_interp", "Emulation.Option.bsnes_jg.bsnes_jg_spc_interp", "Emulation.Option.bsnes_jg.bsnes_jg_spc_interp.Help", "", "gaussian", "gaussian", [new("gaussian", "Emulation.Option.bsnes_jg.bsnes_jg_spc_interp.Value.gaussian"), new("sinc", "Emulation.Option.bsnes_jg.bsnes_jg_spc_interp.Value.sinc")]),
        new("bsnes_jg_aspect", "Emulation.Option.bsnes_jg.bsnes_jg_aspect", "Emulation.Option.bsnes_jg.bsnes_jg_aspect.Help", "", "Auto", "Auto", [new("Auto", "Emulation.Option.bsnes_jg.bsnes_jg_aspect.Value.Auto"), new("1:1", "Emulation.Option.bsnes_jg.bsnes_jg_aspect.Value.1:1"), new("8:7", "Emulation.Option.bsnes_jg.bsnes_jg_aspect.Value.8:7"), new("11:8", "Emulation.Option.bsnes_jg.bsnes_jg_aspect.Value.11:8"), new("4:3", "Emulation.Option.bsnes_jg.bsnes_jg_aspect.Value.4:3")]),
        new("bsnes_jg_overscan_t", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_t", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_t.Help", "", "8", "8", [new("0", "0"), new("4", "4"), new("8", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_t.Value.8"), new("12", "12"), new("16", "16"), new("20", "20")]),
        new("bsnes_jg_overscan_b", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_b", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_b.Help", "", "8", "8", [new("0", "0"), new("4", "4"), new("8", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_b.Value.8"), new("12", "12"), new("16", "16"), new("20", "20"), new("21", "21")]),
        new("bsnes_jg_overscan_l", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_l", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_l.Help", "", "0", "0", [new("0", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_l.Value.0"), new("4", "4"), new("8", "8")]),
        new("bsnes_jg_overscan_r", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_r", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_r.Help", "", "0", "0", [new("0", "Emulation.Option.bsnes_jg.bsnes_jg_overscan_r.Value.0"), new("4", "4"), new("8", "8")]),
        new("bsnes_jg_luminance", "Emulation.Option.bsnes_jg.bsnes_jg_luminance", "Emulation.Option.bsnes_jg.bsnes_jg_luminance.Help", "", "100", "100", [new("0", "0%"), new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "Emulation.Option.bsnes_jg.bsnes_jg_luminance.Value.100")]),
        new("bsnes_jg_saturation", "Emulation.Option.bsnes_jg.bsnes_jg_saturation", "Emulation.Option.bsnes_jg.bsnes_jg_saturation.Help", "", "100", "100", [new("0", "0%"), new("10", "10%"), new("20", "20%"), new("30", "30%"), new("40", "40%"), new("50", "50%"), new("60", "60%"), new("70", "70%"), new("80", "80%"), new("90", "90%"), new("100", "Emulation.Option.bsnes_jg.bsnes_jg_saturation.Value.100"), new("110", "110%"), new("120", "120%"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%")]),
        new("bsnes_jg_gamma", "Emulation.Option.bsnes_jg.bsnes_jg_gamma", "Emulation.Option.bsnes_jg.bsnes_jg_gamma.Help", "", "120", "120", [new("100", "100%"), new("110", "110%"), new("120", "Emulation.Option.bsnes_jg.bsnes_jg_gamma.Value.120"), new("130", "130%"), new("140", "140%"), new("150", "150%"), new("160", "160%"), new("170", "170%"), new("180", "180%"), new("190", "190%"), new("200", "200%")]),
        new("bsnes_jg_competition_timer", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Help", "", "6", "6", [new("3", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.3"), new("4", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.4"), new("5", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.5"), new("6", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.6"), new("7", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.7"), new("8", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.8"), new("9", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.9"), new("10", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.10"), new("11", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.11"), new("12", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.12"), new("13", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.13"), new("14", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.14"), new("15", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.15"), new("16", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.16"), new("17", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.17"), new("18", "Emulation.Option.bsnes_jg.bsnes_jg_competition_timer.Value.18")])
    ];
}
