using GWGUI.Emulation.Constants;

namespace GWGUI.Emulation.Nintendo.Common.Machines.Common.Constants;

internal static class InputSettingsFunctionsConstants
{
    internal const string Up = EmulationControllerCommandIds.Up;
    internal const string Down = EmulationControllerCommandIds.Down;
    internal const string Left = EmulationControllerCommandIds.Left;
    internal const string Right = EmulationControllerCommandIds.Right;
    internal const string A = EmulationControllerCommandIds.A;
    internal const string B = EmulationControllerCommandIds.B;
    internal const string Start = EmulationControllerCommandIds.Start;
    internal const string ResourceControllerActionUp = "Emulation.Controller.Action.Up";
    internal const string ResourceControllerActionDown = "Emulation.Controller.Action.Down";
    internal const string ResourceControllerActionLeft = "Emulation.Controller.Action.Left";
    internal const string ResourceControllerActionRight = "Emulation.Controller.Action.Right";
    internal const string ResourceControllerActionFire1 = "Emulation.Controller.Action.Fire1";
    internal const string ResourceControllerActionFire2 = "Emulation.Controller.Action.Fire2";
    internal const string ButtonB = "B";
    internal const string ButtonA = "A";
    internal const string ButtonY = "Y";
    internal const string ButtonX = "X";
    internal const string ButtonSelect = "SELECT";
    internal const string ButtonStart = "START";
    internal const string ButtonL = "L";
    internal const string ButtonR = "R";
    internal const string Nintendo64A = "N64A";
    internal const string Nintendo64B = "N64B";
    internal const string Nintendo64CUp = "N64CUp";
    internal const string Nintendo64CDown = "N64CDown";
    internal const string Nintendo64CLeft = "N64CLeft";
    internal const string Nintendo64CRight = "N64CRight";
    internal const string Nintendo64StickUp = "N64StickUp";
    internal const string Nintendo64StickDown = "N64StickDown";
    internal const string Nintendo64StickLeft = "N64StickLeft";
    internal const string Nintendo64StickRight = "N64StickRight";
    internal const string Nintendo64ButtonZ = "Z";
    internal const string Nintendo64CUpLabel = "C ↑";
    internal const string Nintendo64CDownLabel = "C ↓";
    internal const string Nintendo64CLeftLabel = "C ←";
    internal const string Nintendo64CRightLabel = "C →";
    internal const string Nintendo64StickUpLabel = "STICK ↑";
    internal const string Nintendo64StickDownLabel = "STICK ↓";
    internal const string Nintendo64StickLeftLabel = "STICK ←";
    internal const string Nintendo64StickRightLabel = "STICK →";
    internal const string ResourceControllerAutomatic = "Emulation.Controller.Automatic";
    internal const string ResourceControllerNone = "Emulation.Controller.None";
    internal const string ResourceControllerJoystick = "Controllers.Enum.Joystick";
    internal const string ResourceNesPad = "Emulation.Nintendo.Controller.NesPad";
    internal const string ResourceSuperNesPad = "Emulation.Nintendo.Controller.SuperNesPad";
    internal const string ResourceGameBoy = "Emulation.Nintendo.Controller.GameBoy";
    internal const string ResourceGameBoyColor = "Emulation.Nintendo.Controller.GameBoyColor";
    internal const string ResourceGameBoyAdvance = "Emulation.Nintendo.Controller.GameBoyAdvance";
    internal const string ResourceNintendo64Pad = "Emulation.Nintendo.Controller.Nintendo64Pad";
    internal const string ResourceControllerKeyboard = "Emulation.Tab.Keyboard";
    internal const string ResourceMouseButtonLeft = "Emulation.Mouse.Button.Left";
    internal const string ResourceMouseButtonRight = "Emulation.Mouse.Button.Right";
    internal const string MouseLeft = "Mouse:Left";
    internal const string MouseRight = "Mouse:Right";
}
